{{- $deploytype:= include "getDeployType" . | default "" }}
{{- if eq $deploytype "d9"}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-pm-protection-service
  namespace: dpa
spec:
  entryPoints:
    - third
    - third6
    - third_node
    - internal
  routes:
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/slas`) && !Path(`/v1/slas/cyber`,`/v1/slas/{slaId}/cyber`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/qos`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/restores`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`POST`) && PathPrefix(`/v1/replication`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`POST`) && Path(`/v1/archive/manual`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`POST`) && Path(`/v1/archive/dispatch`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
  tls:
    secretName: secret-pm-tls
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-pm-protection-service-locks
  namespace: dpa
spec:
  entryPoints:
    - agent
    - agent6
  routes:
    - match: Host(`CDMWebServer`) && Method(`POST`) && Path(`/v1/internal/locks`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
  tls:
    secretName: secret-pm-tls
    options:
      name: tls-option-pm-mtls
{{- end }}