apiVersion: skaffold/v1
build:
  artifacts:
  - context: .
    docker:
      dockerfile: docker/Dockerfile
    image: emei-il.huawei.com/dev/skaffold/sample-user/emeistor-gui
deploy:
  helm:
    releases:
    - chartPath: helm/gui
      imageStrategy:
        helm:
          explicitRegistry: true
      name: gui
      namespace: default
      values:
        image: emei-il.huawei.com/dev/gui
kind: Config
metadata:
  name: es-ms-java-boilerplate
