apiVersion: skaffold/v1
kind: Config
metadata:
  name: es-ms-java-boilerplate
build:
  artifacts:
  - image: emei-il.huawei.com/dev/skaffold/sample-user/emeistor-gui
    context: .
    docker:
        dockerfile: docker/Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml

