swagger: '2.0'
info:
  version: v1
  title: ApplicationTitle
  description: GroupDesc
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: api-SAML
paths:
  /v1/users/saml:
    post:
      x-dr-role: 'Y'
      tags:
        - api-SAML
      x-product: OceanProtect X8000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      operationId: CreateSamlUserUsingPost
      summary: 灾备管理平台调用创建SAML用户，SAML用户默认密码永不过期开关打开
      description: 支持系统管理员和灾备管理员创建SAML用户，SAML用户默认密码永不过期开关打开
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - name: samlUserRequest
          in: body
          required: true
          schema:
            $ref: '#/definitions/SamlUserRequest'
          description: 创建SAML用户时传入的SamlUserRequest对象
      responses:
        '200':
          description: 创建的SAML用户的userId
          schema:
            $ref: '#/definitions/UuidObject'
        '400':
          description: Error response
          schema:
            $ref: '#/definitions/ErrorRsp'
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking. Format is request_uuid-timestamp-hostname.
  /v1/demos/{demo_id}: {}
  /v1/users/saml/{userId}/action/delete-copies:
    delete:
      x-dr-role: 'Y'
      tags:
        - api-SAML
      x-product: OceanProtect X8000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      operationId: DeleteSamlUserCopiesUsingDelete
      summary: 根据用户id以及副本类型删除指定用户指定副本，仅能删除SAML用户副本
      description: 根据用户id以及副本类型删除指定用户该指定副本的所有资源，支持系统管理员和灾备管理员调用接口，灾备管理员仅能删除SAML用户该副本类型的所有资源
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - name: userId
          in: path
          required: true
          type: string
          description: 指定用户的id
        - name: copyGeneratedBy
          in: query
          required: true
          description: 要删除的副本类型
          type: string
      responses:
        '200':
          description: void无返回值
          schema:
            type: string
        '400':
          description: Error response
          schema:
            $ref: '#/definitions/ErrorRsp'
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking. Format is request_uuid-timestamp-hostname.
definitions:
  DemoInfo:
    description: This is a demo
    required:
      - name
    properties:
      id:
        type: string
        description: 唯一标识ID
        minLength: 32
        maxLength: 36
        readOnly: true
        example: 28f61af50fc9452aa0ed5ea25c3cc3d3
      name:
        type: string
        description: 名称
        minLength: 2
        maxLength: 64
        example: MyDemo
      description:
        type: string
        description: 描述
        minLength: 2
        maxLength: 512
        example: this is a demo
  ErrorRsp:
    description: 失败时返回的错误对象
    required:
      - error_code
      - error_msg
    properties:
      error_code:
        description: 错误码
        type: string
        minLength: 8
        maxLength: 36
      error_msg:
        description: 错误描述
        type: string
        minLength: 2
        maxLength: 512
  SamlUserRequest:
    type: object
    properties:
      userId:
        type: string
        description: '[0-9a-f]{32}'
      userName:
        type: string
        description: ^[a-zA-Z0-9_\u4e00-\u9fa5]{1}[\u4e00-\u9fa5\w-]*$
      userRole:
        type: string
        description: ^1|2$
    required:
      - userId
      - userName
      - userRole
  UuidObject:
    type: object
    properties:
      uuid:
        type: string
        description: '[0-9a-f]{32}'
