swagger: '2.0'
info:
  version: v1
  title: ApplicationTitle
  description: GroupDesc
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: ${clusters-api}
paths:
  /v1/internal/storage-role/add-permit:
    put:
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 30081
      x-auth-required: 'N'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'N'
      x-sysadmin-role: 'N'
      tags:
        - ${clusters-api}
      summary: 增加底座角色权限
      description: 增加底座角色权限，1.3版本新增一个权限，1.2升级上来的用户没有新增的权限，提供给复制微服务用的
      operationId: AddStorageRolePermitUsingPut
      parameters:
        - name: addPermitParams
          in: body
          required: true
          description: 增加底座角色权限DoradoAddPermitParams对象
          schema:
            $ref: '#/definitions/DoradoAddPermitParams'
      responses:
        '200':
          description: 无返回值
definitions:
  StorageUserInfo:
    properties:
      createTime:
        type: string
        description: 用户创建时间
        minLength: 1
        maxLength: 100
      roleId:
        type: string
        description: 存储用户角色ID
        minLength: 1
        maxLength: 256
      userId:
        type: string
        description: 存储管理员用户ID
        minLength: 1
        maxLength: 256
      userType:
        type: string
        description: |-
          用户类型
          DEVICE_ADMIN_TYPE:系统角色
          USER_DEFINED_TYPE:自定义角色
        enum:
          - DEVICE_ADMIN_TYPE
          - USER_DEFINED_TYPE
      esn:
        type: string
        description: 存储esn
        minLength: 1
        maxLength: 256
    title: StorageUserInfo
  DoradoAccountRequest:
    properties:
      description:
        type: string
        description: 描述信息
        minLength: 1
        maxLength: 256
      password:
        type: string
        description: 密码
        minLength: 1
        maxLength: 256
      userName:
        type: string
        description: 用户名
        minLength: 1
        maxLength: 256
      userType:
        type: string
        description: |-
          用户类型
          DEVICE_ADMIN_TYPE：系统角色
          USER_DEFINED_TYPE：用户自定义角色
        enum:
          - DEVICE_ADMIN_TYPE
          - USER_DEFINED_TYPE
      esn:
        type: string
        description: 存储esn
        minLength: 1
        maxLength: 256
    title: DoradoAccountRequest
  DoradoAddPermitParams:
    type: object
    required:
      - id
      - permitList
    properties:
      id:
        type: string
        description: 角色id
      permitList:
        type: string
        description: 权限
      esn:
        type: string
        description: 集群esn
