swagger: '2.0'
info:
  version: v1
  title: LDAP服务配置接口
host: localhost
basePath: /
schemes:
  - https
tags:
  - name: LDAP API
paths:
  /v1/ldap/config:
    post:
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - LDAP API
      operationId: modifyLdapConfig
      summary: 修改LDAP服务配置
      description: 修改LDAP服务配置
      produces:
        - application/json
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
        - in: body
          name: ldapConfig
          description: 修改LDAP配置请求
          required: true
          schema:
            $ref: '#/definitions/LdapConfigRequest'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
    get:
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - LDAP API
      operationId: queryLdapConfig
      summary: 查询LDAP服务配置
      description: 查询LDAP服务配置
      produces:
        - application/json
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/LdapConfig'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /v1/ldap/config/check:
    post:
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - LDAP API
      operationId: testLdapConfig
      summary: 测试LDAP服务配置
      description: 测试LDAP服务配置
      produces:
        - application/json
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
        - in: body
          name: ldapConfig
          description: 修改LDAP配置请求
          required: true
          schema:
            $ref: '#/definitions/TestLdapConfigRequest'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
  /v1/ldap/config/change:
    post:
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - LDAP API
      operationId: changeLdapConfig
      summary: 开启或关闭LDAP配置
      description: 开启或关闭LDAP配置
      parameters:
        - name: isLdapEnable
          in: query
          required: true
          type: boolean
      responses:
        '200':
          description: ''
          schema:
            type: object
definitions:
  LdapConfigRequest:
    required:
      - ldapEnable
      - ldapEnableGroup
      - ldapType
      - ldapProtocol
      - ldapBindDn
      - ldapBindPswd
      - ldapAddrType
      - ldapPort
      - ldapAddr
      - ldapUserPath
      - ldapUserName
      - ldapUserObjectType
    properties:
      ldapEnable:
        type: boolean
        description: 是否开启LDAP
      ldapEnableGroup:
        type: boolean
        description: 是否开启LDAP组
      ldapType:
        type: string
        enum:
          - LDAP_SERVICE
        description: LDAP类型
      ldapProtocol:
        type: string
        enum:
          - LDAP
          - LDAPS
        description: LDAP协议
      ldapBindDn:
        type: string
        description: LDAP绑定DN
      ldapBindPswd:
        type: string
        description: LDAP绑定密码
      ldapAddrType:
        type: string
        enum:
          - IP
          - 域名
        description: LDAP地址类型
      ldapPort:
        type: integer
        description: LDAP端口
      ldapAddr:
        type: string
        description: LDAP地址列表（"addr","addr2"）
      ldapUserPath:
        type: string
        description: LDAP用户路径
      ldapUserName:
        type: string
        description: LDAP用户名称属性
      ldapUserObjectType:
        type: string
        description: LDAP用户对象类型
      ldapGroupPath:
        type: string
        description: LDAP用户组路径
      ldapGroupName:
        type: string
        description: LDAP用户组名称属性
      ldapGroupMember:
        type: string
        description: LDAP用户组成员属性
      ldapGroupObjectType:
        type: string
        description: LDAP用户组对象类型
    type: object
  LdapConfig:
    properties:
      ldapEnable:
        type: boolean
        description: 是否开启LDAP
      ldapEnableGroup:
        type: boolean
        description: 是否开启LDAP组
      ldapType:
        type: string
        enum:
          - LDAP_SERVICE
        description: LDAP类型
      ldapProtocol:
        type: string
        enum:
          - LDAP
          - LDAPS
        description: LDAP协议
      ldapBindDn:
        type: string
        description: LDAP绑定DN
      ldapAddrType:
        type: string
        enum:
          - IP
          - 域名
        description: LDAP地址类型
      ldapPort:
        type: integer
        description: LDAP端口
      ldapAddr:
        type: string
        description: LDAP地址列表（"addr","addr2"）
      ldapUserPath:
        type: string
        description: LDAP用户路径
      ldapUserName:
        type: string
        description: LDAP用户名称属性
      ldapUserObjectType:
        type: string
        description: LDAP用户对象类型
      ldapGroupPath:
        type: string
        description: LDAP用户组路径
      ldapGroupName:
        type: string
        description: LDAP用户组名称属性
      ldapGroupMember:
        type: string
        description: LDAP用户组成员属性
      ldapGroupObjectType:
        type: string
        description: LDAP用户组对象类型
  TestLdapConfigRequest:
    required:
      - ldapType
      - ldapProtocol
      - ldapBindDn
      - ldapBindPswd
      - ldapAddrType
      - ldapPort
      - ldapAddr
    properties:
      ldapType:
        type: string
        enum:
          - LDAP_SERVICE
        description: LDAP类型
      ldapProtocol:
        type: string
        enum:
          - LDAP
          - LDAPS
        description: LDAP协议
      ldapBindDn:
        type: string
        description: LDAP绑定DN
      ldapBindPswd:
        type: string
        description: LDAP绑定密码
      ldapAddrType:
        type: string
        enum:
          - IP
          - 域名
        description: LDAP地址类型
      ldapPort:
        type: integer
        description: LDAP端口
      ldapAddr:
        type: string
        description: LDAP地址列表（"addr","addr2"）
    type: object
