swagger: '2.0'
info:
  version: v1
  title: ApplicationTitle
  description: GroupDesc
schemes:
  - https
host: localhost.com
basePath: /
paths:
  /v1/auth/saml/login:
    get:
      x-dr-role: 'Y'
      x-product: OceanProtect X
      x-dm-role: 'Y'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'N'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'N'
      operationId: saml_login
      summary: saml请求登录
      description: saml请求登录
      produces:
        - application/json
      parameters:
        - in: body
          name: CreateDemoInfoRequestBody
          description: DemoInfo object that needs to be created
          required: true
          schema:
            $ref: '#/definitions/DemoInfo'
      responses:
        '302':
          description: 重定向到灾备系统的登录页面，登录认证
          schema:
            type: string
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking. Format is request_uuid-timestamp-hostname.
  /v1/auth/saml/AssertionConsumer:
    post:
      x-dr-role: 'N'
      x-product: OceanProtect X
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'N'
      x-request-examples-url-1: https://8.40.99.132:25081/v1/auth/saml/AssertionConsumer
      x-request-examples-text-1: >-
        SAMLResponse=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c2FtbDJwOlJlc3BvbnNlIHhtbG5zOnNhbWwycD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIiBEZXN0aW5hdGlvbj0iaHR0cHM6Ly84LjQwLjk5LjEzMjoyNTA4MS92MS9hdXRoL3NhbWwvQXNzZXJ0aW9uQ29uc3VtZXIiIElEPSJfYnZ1azA2dWtkZTllNm10ajQ3ZzQybXJ1dGZjYWlyYzVtcHNhIiBJblJlc3BvbnNlVG89ImY0YzQzOWEyMTNmYzRkMTg5MjhiMWFiNTU2NTU0MDBmIiBJc3N1ZUluc3RhbnQ9IjIwMjMtMDMtMDFUMTQ6Mjg6NDUuNjMzWiIgVmVyc2lvbj0iMi4wIiB4bWxuczp4c2Q9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIj48c2FtbDI6SXNzdWVyIHhtbG5zOnNhbWwyPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIj5odHRwczovLzguNDYuMjUyLjE4NTozMTk0Mzwvc2FtbDI6SXNzdWVyPjxkczpTaWduYXR1cmUgeG1sbnM6ZHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyMiPgo8ZHM6U2lnbmVkSW5mbz4KPGRzOkNhbm9uaWNhbGl6YXRpb25NZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz4KPGRzOlNpZ25hdHVyZU1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMDQveG1sZHNpZy1tb3JlI3JzYS1zaGEyNTYiLz4KPGRzOlJlZmVyZW5jZSBVUkk9IiNfYnZ1azA2dWtkZTllNm10ajQ3ZzQybXJ1dGZjYWlyYzVtcHNhIj4KPGRzOlRyYW5zZm9ybXM%2BCjxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjZW52ZWxvcGVkLXNpZ25hdHVyZSIvPgo8ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIj48ZWM6SW5jbHVzaXZlTmFtZXNwYWNlcyB4bWxuczplYz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIiBQcmVmaXhMaXN0PSJ4c2QiLz48L2RzOlRyYW5zZm9ybT4KPC9kczpUcmFuc2Zvcm1zPgo8ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjc2hhMjU2Ii8%2BCjxkczpEaWdlc3RWYWx1ZT5uYmwxVHFML0p0YlhWRUREa3Nla2tJMCtGUDMzdnROc3VpeERGZEZsbm00PTwvZHM6RGlnZXN0VmFsdWU%2BCjwvZHM6UmVmZXJlbmNlPgo8L2RzOlNpZ25lZEluZm8%2BCjxkczpTaWduYXR1cmVWYWx1ZT4KQklSU2R1QWJIREJGSlFvcWI1UVdpNStjYUxoamJHaHRmYndsK1kwcWxodzZZejZweUplSi9NTEpWMUxjQXBIMjk3dytSZHo5MEVzbSYjMTM7ClhCNElQYldTNForUFBMcnROZVhEWitzVU52a3d2QkdDazAvelpmd1VUeFVmZEVFOVhHdnFwZmpjZlJuV0lvS1p5L3BiejZiRStRT2EmIzEzOwp5bnpxV0JvZzNzWDZ5cG1jOUUxN1VSZnNNMTJVaWFSMlFpMHBCVjU2QnZBTXBNSS9RQktSVVVFa0lBR1RqN1JtekJmMXEydVREL3YxJiMxMzsKQTYzRDRZLzN4VU1iMlpkT1ROdlBVZ3RFNGdFQWJTWkU0OThzTC9qQzUrb1VVazcxNXVJZzI2d1FOcGxOTXpMbGlsSHVGZTdhcm1tZyYjMTM7ClgrZXhwTjM4WGdGVldJTkFlRlVDaXRrUWxwTDRxWWdzSzhpd0h1aGoxWVRodmFlMElqY2VpSjhvQkF5SmhQT1pIT09Xang1bzM1b0cmIzEzOwp3RVJKU1kyWTlTSTFTeGZBYTFZeWdhTE5mbnQ2cWdOWWdQRi81bTFrK2t2RE9nRmh2WEloUm11T3ZaWVRrRnJjRUZzdS9adU4yakpOJiMxMzsKa01VSWlPbDE1S3VCZUFIQW5vak9JZkdyNUdkSnRYN3ozM3lJZGQrbjU5cVlIc3JvdEZXNkdtWkIKPC9kczpTaWduYXR1cmVWYWx1ZT4KPC9kczpTaWduYXR1cmU%2BPHNhbWwycDpTdGF0dXM%2BPHNhbWwycDpTdGF0dXNDb2RlIFZhbHVlPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6c3RhdHVzOlN1Y2Nlc3MiLz48L3NhbWwycDpTdGF0dXM%2BPHNhbWwyOkFzc2VydGlvbiB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiIgSUQ9Il81aW80czkxY2hlcnRsZTVobzV0Z3Rpdnc5aWp0ZGc5Z2c2bGYiIElzc3VlSW5zdGFudD0iMjAyMy0wMy0wMVQxNDoyODo0NS42MzNaIiBWZXJzaW9uPSIyLjAiIHhtbG5zOnhzZD0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiPjxzYW1sMjpJc3N1ZXI%2BaHR0cHM6Ly84LjQ2LjI1Mi4xODU6MzE5NDM8L3NhbWwyOklzc3Vlcj48ZHM6U2lnbmF0dXJlIHhtbG5zOmRzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIj4KPGRzOlNpZ25lZEluZm8%2BCjxkczpDYW5vbmljYWxpemF0aW9uTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIi8%2BCjxkczpTaWduYXR1cmVNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Ii8%2BCjxkczpSZWZlcmVuY2UgVVJJPSIjXzVpbzRzOTFjaGVydGxlNWhvNXRndGl2dzlpanRkZzlnZzZsZiI%2BCjxkczpUcmFuc2Zvcm1zPgo8ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI2VudmVsb3BlZC1zaWduYXR1cmUiLz4KPGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyI%2BPGVjOkluY2x1c2l2ZU5hbWVzcGFjZXMgeG1sbnM6ZWM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIgUHJlZml4TGlzdD0ieHNkIi8%2BPC9kczpUcmFuc2Zvcm0%2BCjwvZHM6VHJhbnNmb3Jtcz4KPGRzOkRpZ2VzdE1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMDQveG1sZW5jI3NoYTI1NiIvPgo8ZHM6RGlnZXN0VmFsdWU%2Ba29RQjhwMDNGWGJLVDZwcVhDNkhwa09ock5QQmJOV05TODBUNERBYTBCbz08L2RzOkRpZ2VzdFZhbHVlPgo8L2RzOlJlZmVyZW5jZT4KPC9kczpTaWduZWRJbmZvPgo8ZHM6U2lnbmF0dXJlVmFsdWU%2BCkRNdDZyNy92WUtFb1lmakVBc1RMSkdTWGFCMmVtZFM4aStaV3lHWmJqSkJhcnRtcFdGVkRHMm9zdkVobVE3aE5GT0c4RVo1RWhsZ0smIzEzOwpGRWg5YVpXQmxJRFpicGxjZExVajVoYldCV0hhS3l4aW5JRHZ4LzByZUZvUlJjOFdtOUQzU3QyM1c2ekVTT2M5emZnSHpxb2czVEtxJiMxMzsKT2lYMUE3VnE5UmVJQzY5eHlnaTNjcXZPY1pzYmEwUEw4YXZPY3lCbERvR2FMeDZNbFg3aHkzVUU4TjlzbGtvVFk0RThjcTg5TFlpdCYjMTM7ClhyeUZaV3NRaVFQRklTYldZOGVldWtDZFhGb3M5akljQTkzSXllUzFud05zakxacDJsN0VEcGlvYlc0b2x4NTg5U0s5SzM4cVpFMEUmIzEzOwpoUzdaV2V5NytpY3VSQVJIZlVHdVkvczRPZndDTmRYaFBjVDBTVEV2V2RYM2ErUjdpRC9DTzJFWXZ4M3Blb2hxeUlUTk8xK2RDbEJQJiMxMzsKaXJMdUpiYnV1N0VFeFBUaWJvemh5RWZvMmFaYlVPblNFL3ptRStWdnBCK1I2UXZ2SUQ1OWt3V1hvQkE2YWxLOHo5T3lNdkgvalpSdCYjMTM7CjZYVHUvUEdxb0hmNXV2Q3ozZDV2MkMxSEpPOU1nMDJzVE5IUE13WXlXaGpmY080Y1JzdGI5YXhZCjwvZHM6U2lnbmF0dXJlVmFsdWU%2BCjwvZHM6U2lnbmF0dXJlPjxzYW1sMjpTdWJqZWN0PjxzYW1sMjpOYW1lSUQgRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6bmFtZWlkLWZvcm1hdDp0cmFuc2llbnQiIFNQTmFtZVF1YWxpZmllcj0iaHR0cHM6Ly84LjQwLjk5LjEzMjoyNTA4MSI%2BZDhjNDQ3ZjYtOTRlMi00ZWUxLWI5MGMtN2IxNDExMzEyYjgyPC9zYW1sMjpOYW1lSUQ%2BPHNhbWwyOlN1YmplY3RDb25maXJtYXRpb24gTWV0aG9kPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6Y206YmVhcmVyIj48c2FtbDI6U3ViamVjdENvbmZpcm1hdGlvbkRhdGEgSW5SZXNwb25zZVRvPSJmNGM0MzlhMjEzZmM0ZDE4OTI4YjFhYjU1NjU1NDAwZiIgTm90T25PckFmdGVyPSIyMDIzLTAzLTAxVDE0OjMzOjQ1LjYzM1oiIFJlY2lwaWVudD0iaHR0cHM6Ly84LjQwLjk5LjEzMjoyNTA4MS92MS9hdXRoL3NhbWwvQXNzZXJ0aW9uQ29uc3VtZXIiLz48L3NhbWwyOlN1YmplY3RDb25maXJtYXRpb24%2BPC9zYW1sMjpTdWJqZWN0PjxzYW1sMjpDb25kaXRpb25zIE5vdEJlZm9yZT0iMjAyMy0wMy0wMVQxNDoyODo0NS42MzNaIiBOb3RPbk9yQWZ0ZXI9IjIwMjMtMDMtMDFUMTQ6MzM6NDUuNjMzWiI%2BPHNhbWwyOkF1ZGllbmNlUmVzdHJpY3Rpb24%2BPHNhbWwyOkF1ZGllbmNlPmh0dHBzOi8vOC40MC45OS4xMzI6MjUwODE8L3NhbWwyOkF1ZGllbmNlPjwvc2FtbDI6QXVkaWVuY2VSZXN0cmljdGlvbj48L3NhbWwyOkNvbmRpdGlvbnM%2BPHNhbWwyOkF0dHJpYnV0ZVN0YXRlbWVudD48c2FtbDI6QXR0cmlidXRlIE5hbWU9InByb2plY3RJZHMiIE5hbWVGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphdHRybmFtZS1mb3JtYXQ6YmFzaWMiPjxzYW1sMjpBdHRyaWJ1dGVWYWx1ZSB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6dHlwZT0ieHNkOnN0cmluZyI%2BY2IxMmY5NWVkYWNjNGJjZDkxMjRlNWIzMTkyMzcwMWM8L3NhbWwyOkF0dHJpYnV0ZVZhbHVlPjwvc2FtbDI6QXR0cmlidXRlPjxzYW1sMjpBdHRyaWJ1dGUgTmFtZT0icm9sZU5hbWVzIiBOYW1lRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXR0cm5hbWUtZm9ybWF0OmJhc2ljIj48c2FtbDI6QXR0cmlidXRlVmFsdWUgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeHNpOnR5cGU9InhzZDpzdHJpbmciPnRlX2FkbWluPC9zYW1sMjpBdHRyaWJ1dGVWYWx1ZT48c2FtbDI6QXR0cmlidXRlVmFsdWUgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeHNpOnR5cGU9InhzZDpzdHJpbmciPnZkY19hZG08L3NhbWwyOkF0dHJpYnV0ZVZhbHVlPjwvc2FtbDI6QXR0cmlidXRlPjxzYW1sMjpBdHRyaWJ1dGUgTmFtZT0idXNlcm5hbWUiIE5hbWVGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphdHRybmFtZS1mb3JtYXQ6YmFzaWMiPjxzYW1sMjpBdHRyaWJ1dGVWYWx1ZSB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6dHlwZT0ieHNkOnN0cmluZyI%2BdGVzdF9wdWI8L3NhbWwyOkF0dHJpYnV0ZVZhbHVlPjwvc2FtbDI6QXR0cmlidXRlPjwvc2FtbDI6QXR0cmlidXRlU3RhdGVtZW50PjxzYW1sMjpBdXRoblN0YXRlbWVudCBBdXRobkluc3RhbnQ9IjIwMjMtMDMtMDFUMTQ6Mjg6NDUuNjMzWiIgU2Vzc2lvbkluZGV4PSJfaXJwamFwaGVydzN6Y2E2cDlqbWxrNmp1cGU4Nm9hYndkaW1rIiBTZXNzaW9uTm90T25PckFmdGVyPSIyMDIzLTAzLTAxVDE0OjMzOjQ1LjYzM1oiPjxzYW1sMjpBdXRobkNvbnRleHQ%2BPHNhbWwyOkF1dGhuQ29udGV4dENsYXNzUmVmPnVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphYzpjbGFzc2VzOlBhc3N3b3JkUHJvdGVjdGVkVHJhbnNwb3J0PC9zYW1sMjpBdXRobkNvbnRleHRDbGFzc1JlZj48L3NhbWwyOkF1dGhuQ29udGV4dD48L3NhbWwyOkF1dGhuU3RhdGVtZW50Pjwvc2FtbDI6QXNzZXJ0aW9uPjwvc2FtbDJwOlJlc3BvbnNlPg%3D%3D
      x-request-examples-1: >-
        SAMLResponse=PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48c2FtbDJwOlJlc3BvbnNlIHhtbG5zOnNhbWwycD0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOnByb3RvY29sIiBEZXN0aW5hdGlvbj0iaHR0cHM6Ly84LjQwLjk5LjEzMjoyNTA4MS92MS9hdXRoL3NhbWwvQXNzZXJ0aW9uQ29uc3VtZXIiIElEPSJfYnZ1azA2dWtkZTllNm10ajQ3ZzQybXJ1dGZjYWlyYzVtcHNhIiBJblJlc3BvbnNlVG89ImY0YzQzOWEyMTNmYzRkMTg5MjhiMWFiNTU2NTU0MDBmIiBJc3N1ZUluc3RhbnQ9IjIwMjMtMDMtMDFUMTQ6Mjg6NDUuNjMzWiIgVmVyc2lvbj0iMi4wIiB4bWxuczp4c2Q9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hIj48c2FtbDI6SXNzdWVyIHhtbG5zOnNhbWwyPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXNzZXJ0aW9uIj5odHRwczovLzguNDYuMjUyLjE4NTozMTk0Mzwvc2FtbDI6SXNzdWVyPjxkczpTaWduYXR1cmUgeG1sbnM6ZHM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvMDkveG1sZHNpZyMiPgo8ZHM6U2lnbmVkSW5mbz4KPGRzOkNhbm9uaWNhbGl6YXRpb25NZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzEwL3htbC1leGMtYzE0biMiLz4KPGRzOlNpZ25hdHVyZU1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMDQveG1sZHNpZy1tb3JlI3JzYS1zaGEyNTYiLz4KPGRzOlJlZmVyZW5jZSBVUkk9IiNfYnZ1azA2dWtkZTllNm10ajQ3ZzQybXJ1dGZjYWlyYzVtcHNhIj4KPGRzOlRyYW5zZm9ybXM%2BCjxkczpUcmFuc2Zvcm0gQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjZW52ZWxvcGVkLXNpZ25hdHVyZSIvPgo8ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIj48ZWM6SW5jbHVzaXZlTmFtZXNwYWNlcyB4bWxuczplYz0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIiBQcmVmaXhMaXN0PSJ4c2QiLz48L2RzOlRyYW5zZm9ybT4KPC9kczpUcmFuc2Zvcm1zPgo8ZHM6RGlnZXN0TWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8wNC94bWxlbmMjc2hhMjU2Ii8%2BCjxkczpEaWdlc3RWYWx1ZT5uYmwxVHFML0p0YlhWRUREa3Nla2tJMCtGUDMzdnROc3VpeERGZEZsbm00PTwvZHM6RGlnZXN0VmFsdWU%2BCjwvZHM6UmVmZXJlbmNlPgo8L2RzOlNpZ25lZEluZm8%2BCjxkczpTaWduYXR1cmVWYWx1ZT4KQklSU2R1QWJIREJGSlFvcWI1UVdpNStjYUxoamJHaHRmYndsK1kwcWxodzZZejZweUplSi9NTEpWMUxjQXBIMjk3dytSZHo5MEVzbSYjMTM7ClhCNElQYldTNForUFBMcnROZVhEWitzVU52a3d2QkdDazAvelpmd1VUeFVmZEVFOVhHdnFwZmpjZlJuV0lvS1p5L3BiejZiRStRT2EmIzEzOwp5bnpxV0JvZzNzWDZ5cG1jOUUxN1VSZnNNMTJVaWFSMlFpMHBCVjU2QnZBTXBNSS9RQktSVVVFa0lBR1RqN1JtekJmMXEydVREL3YxJiMxMzsKQTYzRDRZLzN4VU1iMlpkT1ROdlBVZ3RFNGdFQWJTWkU0OThzTC9qQzUrb1VVazcxNXVJZzI2d1FOcGxOTXpMbGlsSHVGZTdhcm1tZyYjMTM7ClgrZXhwTjM4WGdGVldJTkFlRlVDaXRrUWxwTDRxWWdzSzhpd0h1aGoxWVRodmFlMElqY2VpSjhvQkF5SmhQT1pIT09Xang1bzM1b0cmIzEzOwp3RVJKU1kyWTlTSTFTeGZBYTFZeWdhTE5mbnQ2cWdOWWdQRi81bTFrK2t2RE9nRmh2WEloUm11T3ZaWVRrRnJjRUZzdS9adU4yakpOJiMxMzsKa01VSWlPbDE1S3VCZUFIQW5vak9JZkdyNUdkSnRYN3ozM3lJZGQrbjU5cVlIc3JvdEZXNkdtWkIKPC9kczpTaWduYXR1cmVWYWx1ZT4KPC9kczpTaWduYXR1cmU%2BPHNhbWwycDpTdGF0dXM%2BPHNhbWwycDpTdGF0dXNDb2RlIFZhbHVlPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6c3RhdHVzOlN1Y2Nlc3MiLz48L3NhbWwycDpTdGF0dXM%2BPHNhbWwyOkFzc2VydGlvbiB4bWxuczpzYW1sMj0idXJuOm9hc2lzOm5hbWVzOnRjOlNBTUw6Mi4wOmFzc2VydGlvbiIgSUQ9Il81aW80czkxY2hlcnRsZTVobzV0Z3Rpdnc5aWp0ZGc5Z2c2bGYiIElzc3VlSW5zdGFudD0iMjAyMy0wMy0wMVQxNDoyODo0NS42MzNaIiBWZXJzaW9uPSIyLjAiIHhtbG5zOnhzZD0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEiPjxzYW1sMjpJc3N1ZXI%2BaHR0cHM6Ly84LjQ2LjI1Mi4xODU6MzE5NDM8L3NhbWwyOklzc3Vlcj48ZHM6U2lnbmF0dXJlIHhtbG5zOmRzPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwLzA5L3htbGRzaWcjIj4KPGRzOlNpZ25lZEluZm8%2BCjxkczpDYW5vbmljYWxpemF0aW9uTWV0aG9kIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS8xMC94bWwtZXhjLWMxNG4jIi8%2BCjxkczpTaWduYXR1cmVNZXRob2QgQWxnb3JpdGhtPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNyc2Etc2hhMjU2Ii8%2BCjxkczpSZWZlcmVuY2UgVVJJPSIjXzVpbzRzOTFjaGVydGxlNWhvNXRndGl2dzlpanRkZzlnZzZsZiI%2BCjxkczpUcmFuc2Zvcm1zPgo8ZHM6VHJhbnNmb3JtIEFsZ29yaXRobT0iaHR0cDovL3d3dy53My5vcmcvMjAwMC8wOS94bWxkc2lnI2VudmVsb3BlZC1zaWduYXR1cmUiLz4KPGRzOlRyYW5zZm9ybSBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyI%2BPGVjOkluY2x1c2l2ZU5hbWVzcGFjZXMgeG1sbnM6ZWM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMTAveG1sLWV4Yy1jMTRuIyIgUHJlZml4TGlzdD0ieHNkIi8%2BPC9kczpUcmFuc2Zvcm0%2BCjwvZHM6VHJhbnNmb3Jtcz4KPGRzOkRpZ2VzdE1ldGhvZCBBbGdvcml0aG09Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvMDQveG1sZW5jI3NoYTI1NiIvPgo8ZHM6RGlnZXN0VmFsdWU%2Ba29RQjhwMDNGWGJLVDZwcVhDNkhwa09ock5QQmJOV05TODBUNERBYTBCbz08L2RzOkRpZ2VzdFZhbHVlPgo8L2RzOlJlZmVyZW5jZT4KPC9kczpTaWduZWRJbmZvPgo8ZHM6U2lnbmF0dXJlVmFsdWU%2BCkRNdDZyNy92WUtFb1lmakVBc1RMSkdTWGFCMmVtZFM4aStaV3lHWmJqSkJhcnRtcFdGVkRHMm9zdkVobVE3aE5GT0c4RVo1RWhsZ0smIzEzOwpGRWg5YVpXQmxJRFpicGxjZExVajVoYldCV0hhS3l4aW5JRHZ4LzByZUZvUlJjOFdtOUQzU3QyM1c2ekVTT2M5emZnSHpxb2czVEtxJiMxMzsKT2lYMUE3VnE5UmVJQzY5eHlnaTNjcXZPY1pzYmEwUEw4YXZPY3lCbERvR2FMeDZNbFg3aHkzVUU4TjlzbGtvVFk0RThjcTg5TFlpdCYjMTM7ClhyeUZaV3NRaVFQRklTYldZOGVldWtDZFhGb3M5akljQTkzSXllUzFud05zakxacDJsN0VEcGlvYlc0b2x4NTg5U0s5SzM4cVpFMEUmIzEzOwpoUzdaV2V5NytpY3VSQVJIZlVHdVkvczRPZndDTmRYaFBjVDBTVEV2V2RYM2ErUjdpRC9DTzJFWXZ4M3Blb2hxeUlUTk8xK2RDbEJQJiMxMzsKaXJMdUpiYnV1N0VFeFBUaWJvemh5RWZvMmFaYlVPblNFL3ptRStWdnBCK1I2UXZ2SUQ1OWt3V1hvQkE2YWxLOHo5T3lNdkgvalpSdCYjMTM7CjZYVHUvUEdxb0hmNXV2Q3ozZDV2MkMxSEpPOU1nMDJzVE5IUE13WXlXaGpmY080Y1JzdGI5YXhZCjwvZHM6U2lnbmF0dXJlVmFsdWU%2BCjwvZHM6U2lnbmF0dXJlPjxzYW1sMjpTdWJqZWN0PjxzYW1sMjpOYW1lSUQgRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6bmFtZWlkLWZvcm1hdDp0cmFuc2llbnQiIFNQTmFtZVF1YWxpZmllcj0iaHR0cHM6Ly84LjQwLjk5LjEzMjoyNTA4MSI%2BZDhjNDQ3ZjYtOTRlMi00ZWUxLWI5MGMtN2IxNDExMzEyYjgyPC9zYW1sMjpOYW1lSUQ%2BPHNhbWwyOlN1YmplY3RDb25maXJtYXRpb24gTWV0aG9kPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6Y206YmVhcmVyIj48c2FtbDI6U3ViamVjdENvbmZpcm1hdGlvbkRhdGEgSW5SZXNwb25zZVRvPSJmNGM0MzlhMjEzZmM0ZDE4OTI4YjFhYjU1NjU1NDAwZiIgTm90T25PckFmdGVyPSIyMDIzLTAzLTAxVDE0OjMzOjQ1LjYzM1oiIFJlY2lwaWVudD0iaHR0cHM6Ly84LjQwLjk5LjEzMjoyNTA4MS92MS9hdXRoL3NhbWwvQXNzZXJ0aW9uQ29uc3VtZXIiLz48L3NhbWwyOlN1YmplY3RDb25maXJtYXRpb24%2BPC9zYW1sMjpTdWJqZWN0PjxzYW1sMjpDb25kaXRpb25zIE5vdEJlZm9yZT0iMjAyMy0wMy0wMVQxNDoyODo0NS42MzNaIiBOb3RPbk9yQWZ0ZXI9IjIwMjMtMDMtMDFUMTQ6MzM6NDUuNjMzWiI%2BPHNhbWwyOkF1ZGllbmNlUmVzdHJpY3Rpb24%2BPHNhbWwyOkF1ZGllbmNlPmh0dHBzOi8vOC40MC45OS4xMzI6MjUwODE8L3NhbWwyOkF1ZGllbmNlPjwvc2FtbDI6QXVkaWVuY2VSZXN0cmljdGlvbj48L3NhbWwyOkNvbmRpdGlvbnM%2BPHNhbWwyOkF0dHJpYnV0ZVN0YXRlbWVudD48c2FtbDI6QXR0cmlidXRlIE5hbWU9InByb2plY3RJZHMiIE5hbWVGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphdHRybmFtZS1mb3JtYXQ6YmFzaWMiPjxzYW1sMjpBdHRyaWJ1dGVWYWx1ZSB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6dHlwZT0ieHNkOnN0cmluZyI%2BY2IxMmY5NWVkYWNjNGJjZDkxMjRlNWIzMTkyMzcwMWM8L3NhbWwyOkF0dHJpYnV0ZVZhbHVlPjwvc2FtbDI6QXR0cmlidXRlPjxzYW1sMjpBdHRyaWJ1dGUgTmFtZT0icm9sZU5hbWVzIiBOYW1lRm9ybWF0PSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6YXR0cm5hbWUtZm9ybWF0OmJhc2ljIj48c2FtbDI6QXR0cmlidXRlVmFsdWUgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeHNpOnR5cGU9InhzZDpzdHJpbmciPnRlX2FkbWluPC9zYW1sMjpBdHRyaWJ1dGVWYWx1ZT48c2FtbDI6QXR0cmlidXRlVmFsdWUgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeHNpOnR5cGU9InhzZDpzdHJpbmciPnZkY19hZG08L3NhbWwyOkF0dHJpYnV0ZVZhbHVlPjwvc2FtbDI6QXR0cmlidXRlPjxzYW1sMjpBdHRyaWJ1dGUgTmFtZT0idXNlcm5hbWUiIE5hbWVGb3JtYXQ9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphdHRybmFtZS1mb3JtYXQ6YmFzaWMiPjxzYW1sMjpBdHRyaWJ1dGVWYWx1ZSB4bWxuczp4c2k9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNlIiB4c2k6dHlwZT0ieHNkOnN0cmluZyI%2BdGVzdF9wdWI8L3NhbWwyOkF0dHJpYnV0ZVZhbHVlPjwvc2FtbDI6QXR0cmlidXRlPjwvc2FtbDI6QXR0cmlidXRlU3RhdGVtZW50PjxzYW1sMjpBdXRoblN0YXRlbWVudCBBdXRobkluc3RhbnQ9IjIwMjMtMDMtMDFUMTQ6Mjg6NDUuNjMzWiIgU2Vzc2lvbkluZGV4PSJfaXJwamFwaGVydzN6Y2E2cDlqbWxrNmp1cGU4Nm9hYndkaW1rIiBTZXNzaW9uTm90T25PckFmdGVyPSIyMDIzLTAzLTAxVDE0OjMzOjQ1LjYzM1oiPjxzYW1sMjpBdXRobkNvbnRleHQ%2BPHNhbWwyOkF1dGhuQ29udGV4dENsYXNzUmVmPnVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphYzpjbGFzc2VzOlBhc3N3b3JkUHJvdGVjdGVkVHJhbnNwb3J0PC9zYW1sMjpBdXRobkNvbnRleHRDbGFzc1JlZj48L3NhbWwyOkF1dGhuQ29udGV4dD48L3NhbWwyOkF1dGhuU3RhdGVtZW50Pjwvc2FtbDI6QXNzZXJ0aW9uPjwvc2FtbDJwOlJlc3BvbnNlPg%3D%3D
      summary: saml认证
      description: saml认证
      operationId: samlAssertion
      parameters:
        - name: SAMLResponse
          in: query
          required: true
          type: string
      responses:
        '302':
          description: 重定向到登录页面 /console/rest/v1/auth/saml/login
          schema:
            type: string
  /v1/auth/saml/samlToken:
    post:
      x-dr-role: 'N'
      x-product: OceanProtect X8000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'N'
      x-request-examples-url-1: https://8.40.99.132:25081/v1/auth/saml/samlToken
      summary: 获取saml登录token
      description: 获取saml登录token
      operationId: samlToken
      parameters:
        - name: SAMLResponse
          in: query
          required: true
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/LoginResponse'
definitions:
  DemoInfo:
    description: This is a demo
    required:
      - name
    properties:
      id:
        type: string
        description: 唯一标识ID
        minLength: 32
        maxLength: 36
        readOnly: true
        example: 28f61af50fc9452aa0ed5ea25c3cc3d3
      name:
        type: string
        description: 名称
        minLength: 2
        maxLength: 64
        example: MyDemo
      description:
        type: string
        description: 描述
        minLength: 2
        maxLength: 512
        example: this is a demo
  ErrorRsp:
    description: 失败时返回的错误对象
    required:
      - error_code
      - error_msg
    properties:
      error_code:
        description: 错误码
        type: string
        minLength: 8
        maxLength: 36
      error_msg:
        description: 错误描述
        type: string
        minLength: 2
        maxLength: 512
  LoginResponse:
    type: object
    properties:
      token:
        type: string
        description: token
      modifyPassword:
        type: string
        description: modifyPassword
      expireDay:
        type: integer
        format: int64
        description: expireDay
      userId:
        type: string
      deployType:
        type: string
      timeZone:
        type: string
