swagger: '2.0'
info:
  title: 资源管理（数据库实例）
  version: v1
paths:
  /v1/db-instances/:
    get:
      produces:
        - application/json
      parameters:
        - description: 主机ID
          in: query
          maxLength: 128
          minLength: 1
          name: host_id
          required: false
          type: string
        - description: 数据库类型
          in: query
          maxLength: 128
          minLength: 1
          name: db_type
          required: false
          type: string
        - description: 操作系统类型
          in: query
          maxLength: 128
          minLength: 1
          name: os_type
          required: false
          type: string
        - description: 访问令牌
          in: header
          name: X-Auth-Token
          required: true
      responses:
        '200':
          description: The response is the list of all instance info
          schema:
            items:
              $ref: '#/definitions/InstanceInfo'
            title: Response Query Instance Infos V1 Db Instances  Get
            type: array
        '404':
          description: Not found
        '422':
          description: Validation Error
          schema:
            $ref: '#/definitions/HTTPValidationError'
        '500':
          description: Internal Server Error
      tags:
        - db-instance
      operationId: query_instance_infos_v1_db_instances__get
      summary: 查询数据库实例信息列表
    post:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - description: 访问令牌
          in: header
          name: X-Auth-Token
          required: true
        - in: body
          name: body
          required: true
          schema:
            allOf:
              - $ref: '#/definitions/InstanceVerifyRequest'
            description: 数据库实例认证信息
            title: Instance Verify Request
      responses:
        '200':
          description: The response is verify result
          schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          schema:
            $ref: '#/definitions/HTTPValidationError'
        '500':
          description: Internal Server Error
      tags:
        - db-instance
      operationId: create_instance_verify_v1_db_instances__post
      summary: 新增数据库实例认证信息
    put:
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - description: 访问令牌
          in: header
          name: X-Auth-Token
          required: true
        - in: body
          name: body
          required: true
          schema:
            allOf:
              - $ref: '#/definitions/InstanceVerifyRequest'
            description: 数据库实例认证信息
            title: Instance Verify Request
      responses:
        '200':
          description: The response is verify result
          schema: {}
        '404':
          description: Not found
        '422':
          description: Validation Error
          schema:
            $ref: '#/definitions/HTTPValidationError'
        '500':
          description: Internal Server Error
      tags:
        - db-instance
      operationId: instance_verify_v1_db_instances__put
      summary: 修改数据库实例认证信息
  /v1/readiness:
    get:
      produces:
        - application/json
      parameters: []
      responses:
        '200':
          description: Successful Response
          schema: {}
      operationId: readiness_v1_readiness_get
      summary: Readiness
definitions:
  AuthType:
    description: An enumeration.
    enum:
      - using_winAuth
      - using_sqlAuth
    title: AuthType
    type: string
  DatabaseInfo:
    properties:
      database_name:
        description: 数据库名称
        title: Database Name
        type: string
      db_id:
        description: 数据库标识ID
        title: Db Id
        type: string
      db_type:
        description: 数据库类型
        title: Db Type
        type: string
      host_endpoint:
        description: 主机地址
        title: Host Endpoint
        type: string
      host_id:
        description: 主机ID
        title: Host Id
        type: string
      host_name:
        description: 主机名称
        title: Host Name
        type: string
      instance_name:
        description: 实例名
        title: Instance Name
        type: string
      is_register:
        description: 是否注册
        title: Is Register
        type: boolean
    required:
      - database_name
    title: DatabaseInfo
    type: object
  HTTPValidationError:
    properties:
      detail:
        items:
          $ref: '#/definitions/ValidationError'
        title: Detail
        type: array
    title: HTTPValidationError
    type: object
  InstanceInfo:
    properties:
      auth_type:
        description: 认证方式
        title: Auth Type
        type: string
      db_infos:
        description: 数据库信息列表
        items:
          $ref: '#/definitions/DatabaseInfo'
        title: Db Infos
        type: array
      file_size:
        description: 数据文件大小
        title: File Size
        type: string
      host_endpoint:
        description: 主机地址
        title: Host Endpoint
        type: string
      host_id:
        description: 主机ID
        title: Host Id
        type: string
      host_name:
        description: 主机名称
        title: Host Name
        type: string
      instance_name:
        description: 实例名
        title: Instance Name
        type: string
      is_authorized:
        description: 是否认证
        title: Is Authorized
        type: boolean
      log_mode:
        description: 日志模式
        title: Log Mode
        type: string
      os_username:
        description: 实例所属操作系统用户
        title: Os Username
        type: string
      real_size:
        description: 实际数据量
        title: Real Size
        type: string
      status:
        description: 实例状态
        title: Status
        type: string
      username:
        description: 认证的用户名
        title: Username
        type: string
    title: InstanceInfo
    type: object
  InstanceVerifyRequest:
    properties:
      customer:
        $ref: '#/definitions/AuthType'
      db_type:
        $ref: '#/definitions/ResourceSubTypeEnum'
      host_id:
        description: 主机ID
        maxLength: 64
        minLength: 1
        title: Host Id
        type: string
      host_name:
        description: 主机名称
        maxLength: 64
        minLength: 1
        title: Host Name
        type: string
      instance_name:
        description: 实例名
        maxLength: 64
        minLength: 1
        title: Instance Name
        type: string
      is_manual:
        default: false
        description: '添加实例: True, 认证实例: False'
        title: Is Manual
        type: boolean
      istest:
        description: 是否测试连接
        title: Istest
        type: boolean
      mysql_sock:
        description: 端口文件路径
        maxLength: 512
        minLength: 0
        title: Mysql Sock
        type: string
      os_type:
        description: 操作系统类型
        maxLength: 64
        minLength: 0
        title: Os Type
        type: string
      os_username:
        description: 实例所属操作系统用户
        maxLength: 64
        minLength: 0
        title: Os Username
        type: string
      password:
        description: 密码
        maxLength: 64
        minLength: 1
        title: Password
        type: string
      port:
        default: 3306
        description: 端口号
        maximum: 65535
        minimum: 1000
        title: Port
        type: integer
      username:
        description: 用户名
        maxLength: 64
        minLength: 1
        title: Username
        type: string
    required:
      - host_id
      - instance_name
      - istest
      - username
      - password
    title: InstanceVerifyRequest
    type: object
  ResourceSubTypeEnum:
    description: An enumeration.
    enum:
      - DBBackupAgent
      - VMBackupAgent
      - ABBackupClient
      - DWSBackupAgent
      - Fileset
      - HDFSFileset
      - DFSFileset
      - Oracle
      - OracleApp
      - SQLServer
      - DB2
      - MySQL
      - GaussDB
      - SAP HANA
      - Kingbase
      - Sybase IQ
      - Informix
      - TimesTen
      - GBase
      - Dameng
      - Cassandra
      - OscarDB
      - Exchange
      - VMware vCenter Server
      - VMware
      - VMware ESX
      - VMware ESXi
      - Hyper-V
      - HDFS
      - ms.HostSystem
      - FusionSphere
      - vim.ClusterComputeResource
      - vim.HostSystem
      - vim.Folder
      - vim.ResourcePool
      - OpenStack
      - HuaweiCloudStack
      - vim.VirtualMachine
      - ms.VirtualMachine
      - Hadoop
      - FusionInsight
      - vim.VirtualApp
      - vim.Datacenter
      - Common
      - Replica
      - K8S-Common-dataset
      - K8S-MySQL-dataset
      - K8S-cluster
      - K8S-namespace
      - ImportCopy
    title: ResourceSubTypeEnum
    type: string
  ValidationError:
    properties:
      loc:
        items:
          type: string
        title: Location
        type: array
      msg:
        title: Message
        type: string
      type:
        title: Error Type
        type: string
    required:
      - loc
      - msg
      - type
    title: ValidationError
    type: object
x-components: {}

