apiVersion: v1
kind: ConfigMap
metadata:
  name: kmc-conf
  namespace: dpa
data:
  kmc.properties: |
    primary_key_store_file=./master.ks
    standby_key_store_file=./backup.ks
    auto_update_mk_enabled=false
    crypt_key_lifetime_days=180
    crypt_process_perms=0660
    domain_count=8