apiVersion: v1
kind: Service
metadata:
  labels:
    app: pm-scheduler
  name: pm-scheduler
  namespace: dpa
spec:
  ports:
    - name: pm-scheduler-port
      port: 30096
      protocol: TCP
    - name: debug
      port: 8195
      protocol: TCP
  clusterIP: None
  selector:
    app: pm-scheduler