apiVersion: v1
data:
  tls.ca: dGVzdA==
kind: Secret
metadata:
  name: secret-pm-mtls
  namespace: dpa
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": "hook-failed"
type: Opaque
