/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 *
 * @file com_huawei_oceanprotect_sdk_agent_plugin_lib_security_ability_definition_SecurityUtil.h
 * @brief  The implemention about security
 * @version 1.0.0.0
 * @date 2021-10-13
 * @author hwx886037
 */
 
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huawei_oceanprotect_sdk_agent_plugin_lib_security_ability_definition_SecurityUtil */

#ifndef Included_com_huawei_oceanprotect_sdk_agent_plugin_lib_security_ability_definition_SecurityUtil
#define Included_com_huawei_oceanprotect_sdk_agent_plugin_lib_security_ability_definition_SecurityUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huawei_oceanprotect_sdk_agent_plugin_lib_security_ability_definition_SecurityUtil
 * Method:    opaInitialize
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
 Java_com_huawei_oceanprotect_sdk_agent_plugin_lib_security_ability_definition_SecurityUtil_opaInitialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_huawei_oceanprotect_sdk_agent_plugin_lib_security_ability_definition_SecurityUtil
 * Method:    getSecurityItemValue
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
 Java_com_huawei_oceanprotect_sdk_agent_plugin_lib_security_ability_definition_SecurityUtil_getSecurityItemValue
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_huawei_oceanprotect_sdk_agent_plugin_lib_security_ability_definition_SecurityUtil
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
 Java_com_huawei_oceanprotect_sdk_agent_plugin_lib_security_ability_definition_SecurityUtil_decrypt
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
