---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: pm-system-base
  name: pm-system-base
  namespace: default
spec:
  replicas: 1
  selector:
      matchLabels:
          k8s-app: pm-system-base
  template:
    metadata:
      labels:
        k8s-app: pm-system-base
      annotations:
        co.elastic.logs/processors.decode_json_fields.fields.1: message
        co.elastic.logs/processors.decode_json_fields.target: ""
        co.elastic.logs/processors.decode_json_fields.overwrite_keys: "true"
    spec:
      containers:
      - name: pm-system-base
        image: emei-il.huawei.com/pm-system-base:native
        #image: emei-il.huawei.com/<IMAGENAME>
        env:
            - name: SERVICE_MODE
              value: real
            - name: LOGLEVEL
              valueFrom:
                  configMapKeyRef:
                      name: service-env-config
                      key: LOGLEVEL
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: pm-system-base-config
data:
  DEV_MODE: 'true'
  SERVICE.USER-MANAGER: http://user-manager
  SERVICE.ALARM-MANAGER: http://alarm-manager
  SERVICE.BACKUP-REPO-MANAGER: http://backup-repository-mgr
  SERVICE.LOCAL-CLUSTER-MANAGER: http://local-cluster-manager
---
apiVersion: v1
kind: Service
metadata:
  name: pm-system-base
  labels:
    k8s-app: pm-system-base
spec:
  ports:
   - port: 80
     targetPort: 8080
     protocol: TCP
     nodePort: 30888
  type: NodePort
  selector:
    k8s-app: pm-system-base
