swagger: '2.0'
info:
  version: v1
  title: 恢复接口V2
  description: GroupDesc
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: restore-api-v2
    description: V2版本恢复API
paths:
  /v2/restore/jobs:
    post:
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      x-dp-admin-role: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - restore-api-v2
      summary: 创建恢复
      description: 创建恢复，该接口当前仅适用于创建HDFS，HBase，NAS的恢复。
      operationId: CreateRestoreTask
      parameters:
        - name: CreateRestoreTaskRequestBody
          in: body
          required: true
          description: 创建恢复请求体
          schema:
            $ref: '#/definitions/RestoreRequest'
      responses:
        '200':
          description: 创建恢复任务响应对象
          schema:
            $ref: '#/definitions/UuidObject'
definitions:
  RestoreRequest:
    description: 恢复请求体
    properties:
      copyId:
        type: string
        description: 副本ID
        minLength: 32
        maxLength: 64
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
      restoreType:
        type: string
        description: |-
          恢复方式
          CR：普通恢复
          IR：即时恢复
          FLR：细粒度恢复（文件级恢复）
        enum:
          - CR
          - IR
          - FLR
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
        x-dp-admin-role: 'Y'
        x-sysadmin-role: 'Y'
        x-impact-subsystem: 不影响
      targetLocation:
        type: string
        description: '恢复的目标位置，original - 原位置，new - 新位置, native-恢复到A8000本机'
        enum:
          - original
          - new
          - native
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
      subObjects:
        type: array
        items:
          type: string
        description: |-
          恢复子对象列表，细粒度恢复时指定要具体恢复的子对象，如
          恢复子对象列表，细粒度恢复时指定要具体恢复的子对象，如：
          1、文件系统恢复时可以指定只恢复哪些目录
          2、虚拟机恢复时指定恢复哪些磁盘
          3、数据库实例恢复时指定恢复实例下的某个数据库
      targetEnv:
        type: string
        description: 恢复的目标环境的ID
        minLength: 32
        maxLength: 64
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
      targetObject:
        type: string
        description: |-
          恢复的目标对象ID，如：
          1、虚拟机恢复时可以目标主机或集群的ID，或虚拟机ID
          2、文件系统恢复时，为目标的目录地址
          3、数据库恢复时为目标实例ID
        minLength: 2
        maxLength: 256
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
      agents:
        type: array
        items:
          type: string
        description: 恢复时保护代理的ID列表
      extendInfo:
        type: object
        description: 恢复参数，以key/value键值对存放
      filters:
        type: array
        items:
          $ref: '#/definitions/Filter'
        description: |-
          恢复时对某些要恢复的对象进行过滤，比如：
          比如根据一定的过滤规则只恢复某些类型文件或目录
    required:
      - copyId
      - restoreType
      - targetLocation
      - targetEnv
      - targetObject
  Filter:
    properties:
      filterBy:
        type: string
        description: >-
          根据什么进行过滤，取值：Name-名称；ID-标识；Format-文件的格式；ModifyTime-修改时间；CreateTime-创建时间，AccessTime
          访问时间
        enum:
          - Name
          - ID
          - Format
          - ModifyTime
          - CreateTime
          - AccessTime
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
        x-impact-subsystem: 不影响
      filterType:
        type: string
        description: 过滤的资源类型，取值：VM-虚拟机；Disk-磁盘；File-文件；Dir-目录
        enum:
          - Disk
          - File
          - Dir
          - VM
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
        x-impact-subsystem: 不影响
      rule:
        type: string
        description: 过滤规则：如模糊匹配、全匹配、正则表达式等。Fuzzy-模糊匹配；Exact-精确匹配；Regex-正则表达式
        enum:
          - Fuzzy
          - Exact
          - Regex
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
      mode:
        type: string
        description: 过滤类型：INCLUDE-包含；EXCLUDE-排除
        enum:
          - INCLUDE
          - EXCLUDE
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
        x-impact-subsystem: 不影响
      values:
        type: array
        items:
          type: string
        description: 过滤的具体内容
    required:
      - filterBy
      - filterType
      - rule
      - mode
      - values
  UuidObject:
    properties:
      uuid:
        type: string
        description: 恢复job的id
        minLength: 32
        maxLength: 64
        x-impact-subsystem: 不影响
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
    required:
      - uuid
