swagger: '2.0'
info:
  version: v1
  title: ApplicationTitle
  description: GroupDesc
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: '${system-api}'
paths:
  /v1/system/network/service-ip-count:
    get:
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      x-rd-admin-role: 'Y'
      tags:
        - '${system-api}'
      summary: 初始化网络需要配置的服务IP段个数
      description: |-
        通过查询当前的节点个数来确定需要配置几个服务IP段;
        双控需要配置 1个服务IP段
        四控需要配置 2个服务IP段
      operationId: ListServiceIpCountGET
      parameters:
        - name: X-Auth-Token
          in: header
          required: true
          description: Access token
          type: string
      responses:
        '200':
          description: 需要返回的Ip个数
          schema:
            $ref: '#/definitions/IpCountResponse'
definitions:
  IpCountResponse:
    description: 当前需要配置的IP段的个数
    properties:
      ipCount:
        type: integer
        format: int32
        description: 返回的IP段个数
        minimum: 1
        maximum: 2
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
    required:
      - ipCount
