swagger: '2.0'
info:
  version: v1
  title: DEE Base Parser API Document
  contact: {}
  license: {}
host: localhost
basePath: /
tags:
  - name: Download Management
    description: Download Controller
paths: {}
securityDefinitions:
  Authorization:
    type: apiKey
    name: TOKEN
    in: header
definitions:
  StatusResponse:
    type: object
    properties:
      errorCode:
        type: string
      errorMessage:
        type: string
      file_name:
        type: string
      file_status:
        type: string
      request_id:
        type: string
    title: StatusResponse
