swagger: '2.0'
info:
  version: v1
  title: ApplicationTitle
  description: GroupDesc
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: copies
paths:
  '/v1/copies/{copy_id}/detect-reports':
    get:
      tags:
        - copies
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      operationId: ShowDetectionReport
      summary: 获得副本防勒索检测报告
      description: 根据副本id获得防勒索检测报告
      produces:
        - application/json
      parameters:
        - name: copy_id
          in: path
          required: true
          type: string
          description: 副本ID
          minLength: 0
          maxLength: 64
          x-access-port: 25081
          x-auth-required: 'Y'
          x-public-api: 'Y'
        - name: X-Auth-Token
          in: header
          required: true
          description: 访问令牌
          type: string
      responses:
        '200':
          description: Demo Information
          schema:
            $ref: '#/definitions/CopyAntiRansomwareReport'
          headers:
            X-request-id:
              type: string
              description: >-
                This field is the request ID number for task tracking. Format is
                request_uuid-timestamp-hostname.
        '400':
          description: Error response
          schema:
            $ref: '#/definitions/ErrorRsp'
          headers:
            X-request-id:
              type: string
              description: >-
                This field is the request ID number for task tracking. Format is
                request_uuid-timestamp-hostname.
  /v1/copies/detect-details:
    get:
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      tags:
        - copies
      summary: 获得副本防勒索详细信息
      description: 获取副本的防勒索病毒的详细信息
      operationId: ShowDetectionDetails
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: resource_id
          in: query
          required: true
          description: 资源的uuid
          type: string
        - name: page_size
          in: query
          required: true
          description: 每页条数
          type: string
        - name: page_no
          in: query
          required: true
          description: 当前页
          type: string
        - name: orders
          in: query
          required: false
          description: 排序字段：timestamp、detectiontime
          type: string
        - name: conditions
          in: query
          required: false
          description: 筛选条件：status、detection_model_version
          type: string
        - name: X-Auth-Token
          in: header
          required: true
          description: 访问令牌
          type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/CopyAntiRansomwar'
          headers:
            X-request-id:
              description: >-
                This field is the request ID number for task tracking. Format is
                request_uuid-timestamp-hostname.
              type: string
  /v1/copies/detection-statistics:
    get:
      tags:
        - copies
      summary: 获得资源副本防勒索统计列表
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      description: 获得资源副本防勒索统计列表
      operationId: ShowDetectionStatistics
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: X-Auth-Token
          in: header
          required: true
          description: 访问令牌
          type: string
        - name: res_type
          in: query
          required: true
          description: 资源类型
          type: string
        - name: page_no
          in: query
          required: true
          description: 分页页面编码
          type: string
        - name: page_size
          in: query
          required: true
          description: 分页数据条数
          type: string
        - name: orders
          in: query
          required: false
          description: >-
            排序字段：repicas、infectedrepicas、uninfectedrepicas、detectinfreplicas、uninspectedrepicas
          type: string
        - name: conditions
          in: query
          required: false
          description: '筛选条件：name,location'
          type: string
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/CopyAntiRansomwarStatistics'
          headers:
            X-request-id:
              description: >-
                This field is the request ID number for task tracking. Format is
                request_uuid-timestamp-hostname.
              type: string
  /v1/copies/action/detect-status:
    put:
      tags:
        - copies
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      summary: 更改副本勒索状态
      description: 更改副本勒索状态
      operationId: UpdateDetectionStatus
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - name: UpdateDetectionStatusRequestBody
          in: body
          required: true
          schema:
            $ref: '#/definitions/UpdateDetectionStatusRequestBody'
          description: 修改报告的副本信息
        - name: X-Auth-Token
          in: header
          required: true
          description: 访问令牌
          type: string
      responses:
        '200':
          description: ''
          schema:
            type: string
          headers:
            X-request-id:
              description: >-
                This field is the request ID number for task tracking. Format is
                request_uuid-timestamp-hostname.
              type: string
definitions:
  DemoInfo:
    description: This is a demo
    required:
      - name
    properties:
      id:
        type: string
        description: 唯一标识ID
        minLength: 32
        maxLength: 36
        readOnly: true
        example: 28f61af50fc9452aa0ed5ea25c3cc3d3
      name:
        type: string
        description: 名称
        minLength: 2
        maxLength: 64
        example: MyDemo
      description:
        type: string
        description: 描述
        minLength: 2
        maxLength: 512
        example: this is a demo
  ErrorRsp:
    description: 失败时返回的错误对象
    required:
      - error_code
      - error_msg
    properties:
      error_code:
        description: 错误码
        type: string
        minLength: 8
        maxLength: 36
      error_msg:
        description: 错误描述
        type: string
        minLength: 2
        maxLength: 512
  CopyAntiRansomwareReport:
    description: 副本检测报告
    required:
      - copy_id
      - timestamp
      - model
      - status
      - detection_time
      - last_tested_time
    properties:
      copy_id:
        type: string
        description: 副本id
      timestamp:
        type: string
        description: 副本时间戳
      model:
        type: string
        description: 防勒索检测模型
      status:
        type: string
        description: 检测状态
      detection_duration:
        type: string
        description: 检测持续时间
      detection_time:
        type: string
        description: 副本检测时间
      report:
        type: string
        description: 防勒索检测报告
      last_tested_time:
        type: string
        description: 防勒索最新检测时间
  CopyAntiRansomwar:
    description: 副本防勒索详细信息
    required:
      - copy_id
      - timestamp
      - location
    properties:
      copy_id:
        type: string
        description: 副本ID
      timestamp:
        type: string
        description: 副本时间戳
      location:
        type: string
        description: 副本位置
      model:
        type: string
        description: 防勒索检测模型
      status:
        type: string
        description: 检测状态
      detection_time:
        type: string
        description: 副本检测时间
  CopyAntiRansomwarStatistics:
    properties:
      resource_id:
        type: string
        description: 资源ID
      name:
        type: string
        description: 资源名称
      location:
        type: string
        description: 资源位置
      repicas:
        type: string
        description: 副本总数量
      infectedRepicas:
        type: string
        description: 感染副本数量
      uninfectedRepicas:
        type: string
        description: 未感染副本数量
      detectingRepicas:
        type: string
        description: 正在检测副本数量
      uninspectedRepicas:
        type: string
        description: 未检测副本数量
  UpdateDetectionStatusRequestBody:
    description: 更改勒索状态副本信息
    properties:
      resource_type:
        type: string
        description: 资源类型
      name:
        type: string
        description: 资源名称
      copy_ids:
        type: array
        items:
          type: string
        description: 副本id列表
    required:
      - resource_type
      - name
      - copy_ids
  CopyAntiRansomwareTable:
    description: 副本防勒索信息
    required:
      - copy_id
      - status
      - model
      - detection_start_time
      - detection_end_time
      - report
    properties:
      copy_id:
        type: string
        description: 副本ID
      status:
        type: string
        description: 状态
      model:
        type: string
        description: 检测模型
      detection_start_time:
        type: string
        description: 开始检测时间
      detection_end_time:
        type: string
        description: 检测结束时间
      report:
        type: string
        description: 报告
