---
swagger: "2.0"
info:
  version: "1.0"
  title: "基础设施管理接口"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"
basePath: "/"
tags:
- name: "log-manager-api"
  description: "Log Manager Controller"
- name: "inspect-info-api"
  description: "Inspect Info Controller"
- name: "collect-info-api"
  description: "Collect Info Controller"
- name: "data-manager-api"
  description: "Data Manager Controller"
paths:
  /v1/infra/logs/level/info:
    get:
      tags:
      - "log-manager-api"
      summary: "查询当前日志级别"
      x-swagger-router-controller: "service.apis.controllers.set_controller"
      operationId: "query_current_level"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/LogInfoResponse'
        "400":
          description: "Bad Request"
  /v1/infra/logs/level/setup:
    post:
      tags:
      - "log-manager-api"
      summary: "设置日志级别"
      x-swagger-router-controller: "service.apis.controllers.set_controller"
      operationId: "set_log_level"
      parameters:
        - name: "body"
          in: "body"
          required: true
          description: "日志级别请求参数格式"
          schema:
            $ref: "#/definitions/LogLevelParam"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
  /v1/infra/logs/export_package:
    get:
      tags:
      - "log-manager-api"
      summary: "日志导出功能api"
      x-swagger-router-controller: "service.apis.controllers.logs_controller"
      operationId: "export_log_file"
      parameters:
        - name: "nodeName"
          in: "query"
          description: "节点名称列表"
          type: "array"
          items:
            type: "string"
        - name: "componentName"
          in: "query"
          description: "子系统模块名称[取值范围]，INFRA代表基础设施，DME代表数据保护引擎，
          DEE代表数据使能，PM代表管理服务"
          required: false
          type: "array"
          items:
            type: "string"
            enum:
              - "INFRA"
              - "DME"
              - "DEE"
              - "PM"
          collectionFormat: "multi"
        - name: "step"
          in: "query"
          required: true
          type: string
          description: "收集步骤"
          enum:
            - package
            - package_progress
          collectionFormat: "multi"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/LogPackageResponse'
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"

  /v1/infra/logs/export:
    get:
      tags:
        - "log-manager-api"
      summary: "日志导出功能下载api"
      x-swagger-router-controller: "service.apis.controllers.logs_controller"
      operationId: "export_download"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "500":
          description: "Server Wrong"

  /v1/infra/inspect/service/status:
    get:
      tags:
      - "inspect-info-api"
      summary: "POD状态检查"
      x-swagger-router-controller: "service.apis.controllers.inspect_controller"
      operationId: "check_service_status"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/NodeListServiceResponse'
        "400":
          description: "Bad Request"
  /v1/infra/inspect/config/status:
    get:
      tags:
      - "inspect-info-api"
      summary: "配置信息检查"
      x-swagger-router-controller: "service.apis.controllers.inspect_controller"
      operationId: "check_config_status"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/NodeListConfigResponse'
        "400":
          description: "Bad Request"
  /v1/infra/inspect/resource/status:
    get:
      tags:
      - "inspect-info-api"
      summary: "资源状态检查"
      x-swagger-router-controller: "service.apis.controllers.inspect_controller"
      operationId: "check_resource_status"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/NodeListResourceResponse'
        "400":
          description: "Bad Request"
  /v1/infra/collect/all/info:
    get:
      tags:
      - "collect-info-api"
      summary: "获取所有信息"
      x-swagger-router-controller: "service.apis.controllers.collect_controller"
      operationId: "collect_all_info"
      parameters:
        - name: "type"
          in: "query"
          required: true
          type: string
          description: "收集步骤"
          enum:
            - package
            - package_progress
            - download
            - remove
        - name: "nodeName"
          in: "query"
          description: "节点名称列表"
          type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
  /v1/infra/collect/node/info:
    get:
      tags:
      - "log-manager-api"
      - "collect-info-api"
      summary: "获取节点信息"
      x-swagger-router-controller: "service.apis.controllers.collect_controller"
      operationId: "collect_node_info"
      parameters:
        - name: "nodeName"
          in: "query"
          description: "节点名称"
          type: string
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/NodeInfoListResponse'
        "400":
          description: "Bad Request"
  /v1/infra/data/db/backup:
    get:
      tags:
      - "data-manager-api"
      summary: "备份db数据"
      x-swagger-router-controller: "service.apis.controllers.manage_data_controller"
      operationId: "backup_db_data"
      parameters:
        - $ref: "#/parameters/path"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/DataSuccessResponse'
        "400":
          description: "Bad Request"
  /v1/infra/data/db/recover:
    get:
      tags:
      - "data-manager-api"
      summary: "恢复db数据"
      x-swagger-router-controller: "service.apis.controllers.manage_data_controller"
      operationId: "recover_db_data"
      parameters:
        - $ref: "#/parameters/path"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/DataSuccessResponse'
        "400":
          description: "Bad Request"
  /v1/infra/pod/info:
    get:
      tags:
        - "pod-manager-api"
      summary: "查询所有pod"
      x-swagger-router-controller: "service.apis.controllers.pod_controller"
      operationId: "query_pod_status"
      parameters:
        - name: "nodeName"
          in: "query"
          description: "节点名称"
          type: string
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/NodeListPodResponse'
        "400":
          description: "Bad Request"
  /v1/infra/pod/stop:
    get:
      tags:
      - "pod-manager-api"
      summary: "停止pod"
      x-swagger-router-controller: "service.apis.controllers.pod_controller"
      operationId: "stop_pod"
      parameters:
        - name: "step"
          in: "query"
          description: "停止阶段"
          required: true
          type: string
          enum:
            - phase_1
            - phase_2
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/DataSuccessResponse'
        "400":
          description: "Bad Request"
  /v1/infra/configmap/info:
    get:
      tags:
      - "configMap-manager-api"
      summary: "查询configMap对象"
      x-swagger-router-controller: "service.apis.controllers.configmap_controller"
      operationId: "query_config_map_data"
      parameters:
        - name: "nameSpace"
          in: "query"
          description: "命名空间"
          required: true
          type: string
        - name: "configMap"
          in: "query"
          description: "configMap"
          required: true
          type: string
        - name: "configKey"
          in: "query"
          description: "configMap对象"
          type: string
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/ConfigMapInfoResponse'
        "400":
          description: "Bad Request"
  /v1/infra/configmap/create:
    post:
      tags:
      - "configMap-manager-api"
      summary: "增加configMap对象"
      x-swagger-router-controller: "service.apis.controllers.configmap_controller"
      operationId: "add_config_map_data"
      parameters:
        - name: "nameSpace"
          in: "query"
          description: "命名空间"
          required: true
          type: string
        - name: "configMap"
          in: "query"
          description: "configMap"
          required: true
          type: string
        - name: "configKey"
          in: "query"
          description: "configMap对象"
          required: true
          type: string
        - name: "configValue"
          in: "query"
          description: "configMap对象值"
          required: true
          type: string
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
  /v1/infra/configmap/delete:
    post:
      tags:
      - "configMap-manager-api"
      summary: "删除configMap对象"
      x-swagger-router-controller: "service.apis.controllers.configmap_controller"
      operationId: "delete_config_map_data"
      parameters:
        - name: "nameSpace"
          in: "query"
          description: "命名空间"
          required: true
          type: string
        - name: "configMap"
          in: "query"
          description: "configMap"
          required: true
          type: string
        - name: "configKey"
          in: "query"
          description: "configMap对象"
          required: true
          type: string
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
  /v1/infra/pvc/info:
    get:
      tags:
        - "pvc-manager-api"
      summary: "查询PVC对象"
      x-swagger-router-controller: "service.apis.controllers.pvc_controller"
      operationId: "query_pvc_data"
      parameters:
        - name: "nameSpace"
          in: "query"
          description: "命名空间"
          required: true
          type: string
        - name: "pvcName"
          in: "query"
          description: "pvc name"
          required: true
          type: string
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/PvcInfoResponse'
        "400":
          description: "Bad Request"
  /v1/infra/service/update/databasepwd:
    post:
      tags:
        - "service-manager-api"
      summary: "更新gaussdb密码"
      x-swagger-router-controller: "service.apis.controllers.status_controller"
      operationId: "update_password"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: '#/definitions/DataSuccessResponse'
        "400":
          description: "Bad Request"
definitions:
  ErrorResponse:
    type: "object"
    properties:
      errId:
        type: "integer"
        format: "int64"
        description: "错误码"
      errMsg:
        type: "string"
        description: "错误信息"
  NodeListServiceResponse:
    type: "object"
    properties:
      data:
        type: "array"
        description: "节点上pod和container的服务状态列表"
        items:
          $ref: "#/definitions/PodListServiceStatus"
      error:
        $ref: "#/definitions/ErrorResponse"
  NodeListPodResponse:
    type: "object"
    properties:
      data:
        type: "array"
        description: "节点上pod的状态列表"
        items:
          $ref: "#/definitions/PodListAllStatus"
      error:
        $ref: "#/definitions/ErrorResponse"
  PodListAllStatus:
    type: "object"
    properties:
      nodeName:
        type: "string"
        description: "节点名称"
      nameSpace:
        type: "string"
        description: "空间名"
      podName:
        type: "string"
        description: "pod名称"
      podStatus:
        type: "string"
        description: "pod状态"
  ConfigMapInfoResponse:
    type: "object"
    properties:
      data:
        type: "array"
        description: "configmap的信息列表"
        items:
          $ref: "#/definitions/MapDataInfo"
      error:
        $ref: "#/definitions/ErrorResponse"
  MapDataInfo:
    type: "object"
    properties:
      key:
        type: "string"
        description: "键"
      value:
        type: "string"
        description: "值"
  PvcInfoResponse:
    type: "object"
    properties:
      data:
        $ref: "#/definitions/PvcDataInfo"
      error:
        $ref: "#/definitions/ErrorResponse"
  PvcDataInfo:
    type: "object"
    properties:
      name:
        type: "string"
        description: "内置持久卷名称"
      volume_name:
        type: "string"
        description: "卷名称"
      volume_mode:
        type: "string"
        description: "卷模式"
      storage_class_name:
        type: "string"
        description: "存储类型"
  PodListServiceStatus:
    type: "object"
    properties:
      nodeName:
        type: "string"
        description: "节点名称"
      namespace:
        type: "string"
        description: "空间名"
      podName:
        type: "string"
        description: "pod名称"
      podStatus:
        type: "string"
        description: "pod状态"
      containerInfo:
        type: "array"
        description: "节点上pod中包含的容器服务状态列表"
        items:
          $ref: "#/definitions/ContainerServiceStatus"
  ContainerServiceStatus:
    type: "object"
    properties:
      containerStatus:
        type: "string"
        description: "容器状态"
      containerName:
        type: "string"
        description: "容器名称"
  NodeListConfigResponse:
    type: "object"
    properties:
      data:
        type: "array"
        description: "节点上pod关键配置状态列表"
        items:
          $ref: "#/definitions/KeyConfigStatus"
      error:
        $ref: "#/definitions/ErrorResponse"
  KeyConfigStatus:
    type: "object"
    properties:
      logLevel:
        type: "string"
        description: "日志级别"
      dbState:
        type: "array"
        description: "数据库更新状态列表"
        items:
          $ref: "#/definitions/DbStateInfo"
  DbStateInfo:
    type: "object"
    properties:
      dbName:
       type: "string"
       description: "数据库名称"
      dbState:
        type: "string"
        description: "数据库更新状态"
  NodeListResourceResponse:
    type: "object"
    properties:
      data:
        type: "array"
        description: "节点上pod CPU、内存、磁盘资源状态列表"
        items:
          $ref: "#/definitions/ResourceStatus"
      error:
        $ref: "#/definitions/ErrorResponse"
  ResourceStatus:
    type: "object"
    properties:
      resourceType:
        type: "string"
        description: "资源类型"
      resourceName:
        type: "string"
        description: "资源名称"
      used:
        type: "number"
        format: "string"
        description: "使用的资源"
      total:
        type: "number"
        format: "string"
        description: "分配的资源"
      usedPercentage:
        type: "number"
        format: "float"
        description: "资源使用占比"
      usedMark:
        type: "number"
        format: "float"
        description: "资源使用占比水位线"
  NodeInfoListResponse:
    type: "object"
    properties:
      data:
        type: "array"
        description: "节点信息列表"
        items:
          $ref: "#/definitions/NodeInfo"
      error:
        $ref: "#/definitions/ErrorResponse"
  NodeInfo:
    type: "object"
    properties:
      nodeName:
        type: "string"
        description: "控制器名称"
      nodeStatus:
        type: "string"
        description: "节点状态"
      hostname:
        type: "string"
        description: "节点名称"
      address:
        type: "string"
        description: "业务IP地址"
      componentList:
        type: "object"
        description: "组件名称列表，[取值范围]INFRA,DME,DEE,PM"
  LogLevelParam:
    properties:
      log_level:
        type: "string"
        description: "日志级别"
        enum:
          - "INFO"
          - "WARN"
          - "ERROR"
          - "DEBUG"
  LogInfoResponse:
    type: "object"
    properties:
      data:
        type: "object"
        properties:
          logLevel:
            description: "日志级别"
            type: "string"
      error:
        $ref: "#/definitions/ErrorResponse"
  LogPackageResponse:
    type: "object"
    properties:
      progress:
        description: "日志级别"
        type: "string"
      error:
        $ref: "#/definitions/ErrorResponse"

  DataSuccessResponse:
    type: object
    required:
      - success
    properties:
      success:
        type: boolean
        description: "结果为True或者是False"
      code:
        type: string
        description: "错误码"
      message:
        type: string
        maxLength: 512
        description: "错误信息"
parameters:
  path:
    name: "path"
    in: "query"
    required: true
    type: string
    description: "数据目录路径"
    maxLength: 256