swagger: '2.0'
info:
  version: v1
  title: 副本管理接口
  description: GroupDesc
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: tape_archive_copies_download
paths:
  /v1/archive/action/download-to-dpa:
    post:
      x-impact-subsystem: 影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      tags:
        - tape_archive_copies_download
      operationId: DownloadTapeCopyDWS
      summary: DWS磁带归档副本下载
      description: 将DWS归档到磁带的副本下载到数据保护一体机
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - name: RestoreDownloadRequest
          in: body
          required: true
          description: 归档副本ID
          schema:
            $ref: '#/definitions/DownloadTapeCopyDWSRequestBody'
        - name: X-Auth-Token
          in: header
          required: true
          type: string
      responses:
        '200':
          description: ok
        '500':
          description: ''
          schema:
            $ref: '#/definitions/RspMsg'
definitions:
  ErrorRsp:
    description: 失败时返回的错误对象
    required:
      - error_code
      - error_msg
    properties:
      error_code:
        description: 错误码
        type: string
        minLength: 8
        maxLength: 36
      error_msg:
        description: 错误描述
        type: string
        minLength: 2
        maxLength: 512
  DownloadTapeCopyDWSRequestBody:
    properties:
      copyId:
        type: string
        description: 副本ID
    required:
      - copyId
  ProgressModel:
    description: 恢复进度查询模型
    required:
      - process
      - status
    properties:
      process:
        type: integer
        format: int32
        description: 进度
      status:
        type: integer
        format: int32
        description: 状态
  RspMsg:
    description: 响应模型
    required:
      - errorCode
    properties:
      errorCode:
        type: string
        description: 错误码，成功是0
      errorMessage:
        type: string
        description: 错误描述信息
      detailParams:
        type: array
        items:
          type: string
        description: 返回参数
  DownloadTapeCopyNASRequestBody:
    description: 磁带副本下载参数模型
    properties:
      requestId:
        type: string
        description: 任务ID
      fileSystem:
        type: string
        description: 文件系统名
      copyId:
        type: string
        description: 副本ID
    required:
      - requestId
      - fileSystem
      - copyId
