swagger: '2.0'
info:
  title: 资源管理（hyper-v）
  version: v1
tags:
  - name: hyper-v
paths:
  /v1/hyper-v/networks:
    get:
      produces:
        - application/json
      parameters:
        - description: 客户机ID
          in: query
          maxLength: 64
          minLength: 1
          name: client_id
          required: true
          type: string
        - description: 平台ID
          in: query
          maxLength: 64
          minLength: 1
          name: platform_id
          required: true
          type: string
        - description: 访问令牌
          in: header
          name: X-Auth-Token
          required: true
      responses:
        '200':
          description: Successful Response
          schema:
            items:
              type: string
            title: Response Get Hyper V Network V1 Hyper V Networks Get
            type: array
        '404':
          description: Not found
        '422':
          description: Validation Error
          schema:
            $ref: '#/definitions/HTTPValidationError'
      tags:
        - hyper-v
      description: 查询Hyper-V虚拟化环境资源的网络信息列表
      operationId: get_hyper_v_network_v1_hyper_v_networks_get
      summary: 查询Hyper-V虚拟化环境资源的网络信息列表
  /v1/hyper-v/resources:
    get:
      produces:
        - application/json
      parameters:
        - description: 分页页面编码
          in: query
          minimum: 0
          name: page_no
          required: true
          type: integer
        - description: 分页数据条数
          in: query
          maximum: 200
          minimum: 0
          name: page_size
          required: true
          type: integer
        - collectionFormat: multi
          description: 排序字段：
          in: query
          items:
            type: string
          name: orders
          required: false
          type: array
        - description: 条件参数：
          in: query
          name: conditions
          required: false
          type: string
        - description: 访问令牌
          in: header
          name: X-Auth-Token
          required: true
      responses:
        '200':
          description: Successful Response
          schema:
            $ref: '#/definitions/BasePage_HyperVResourceSchema_'
        '404':
          description: Not found
        '422':
          description: Validation Error
          schema:
            $ref: '#/definitions/HTTPValidationError'
      tags:
        - hyper-v
      operationId: query_resources_v1_hyper_v_resources_get
      summary: 查询Hyper-V虚拟化环境资源信息列表
definitions:
  BasePage_HyperVResourceSchema_:
    properties:
      items:
        description: 数据列表
        items:
          $ref: '#/definitions/HyperVResourceSchema'
        title: Items
        type: array
      page_no:
        description: 页面编号
        title: Page No
        type: integer
      page_size:
        description: 每页数据量
        title: Page Size
        type: integer
      pages:
        description: 总页数
        title: Pages
        type: integer
      total:
        description: 总的数据条数
        title: Total
        type: integer
    required:
      - total
      - pages
      - page_size
      - page_no
      - items
    title: 'BasePage[HyperVResourceSchema]'
    type: object
  HTTPValidationError:
    properties:
      detail:
        items:
          $ref: '#/definitions/ValidationError'
        title: Detail
        type: array
    title: HTTPValidationError
    type: object
  HyperVResourceSchema:
    properties:
      alias_type:
        description: 类型别名
        title: Alias Type
        type: string
      alias_value:
        description: 值别名
        title: Alias Value
        type: string
      authorized_user:
        description: 被授权用户
        title: Authorized User
        type: string
      capacity:
        default: 0
        description: 容量，仅用于数据存储
        title: Capacity
        type: integer
      children:
        description: 子资源的数量
        title: Children
        type: integer
      children_uuids:
        description: 子资源ID列表
        items: {}
        title: Children Uuids
        type: array
      created_time:
        description: 资源创建时间
        format: date-time
        title: Created Time
        type: string
      env_ip:
        description: 对应的保护环境IP
        title: Env Ip
        type: string
      environment_endpoint:
        description: 环境IP
        title: Environment Endpoint
        type: string
      environment_is_cluster:
        description: 集群环境标识
        title: Environment Is Cluster
        type: string
      environment_name:
        description: 环境名称
        title: Environment Name
        type: string
      environment_os_name:
        description: 环境系统名称
        title: Environment Os Name
        type: string
      environment_os_type:
        description: 环境系统类型
        title: Environment Os Type
        type: string
      environment_sub_type:
        description: 环境资源子类型
        title: Environment Sub Type
        type: string
      environment_type:
        description: 环境资源大类型
        title: Environment Type
        type: string
      environment_uuid:
        description: 环境ID
        title: Environment Uuid
        type: string
      ext_parameters:
        description: 扩展属性
        format: json-string
        title: Ext Parameters
        type: string
      free_space:
        default: 0
        description: 空闲容量，仅用于数据存储
        title: Free Space
        type: integer
      is_template:
        default: false
        description: 是否未模板虚拟机
        title: Is Template
        type: boolean
      link_status:
        description: 资源状态，0-在线 1-离线
        title: Link Status
        type: integer
      mo_id:
        description: 虚拟机的moId
        title: Mo Id
        type: string
      name:
        description: 资源名称
        title: Name
        type: string
      os_type:
        description: 操作系统类型
        title: Os Type
        type: string
      parent_name:
        description: 父资源名称
        title: Parent Name
        type: string
      parent_uuid:
        description: 父资源ID
        title: Parent Uuid
        type: string
      partitions:
        description: 数据存储的磁盘分区列表
        items:
          type: string
        title: Partitions
        type: array
      path:
        description: 资源位置
        title: Path
        type: string
      protection_status:
        description: 保护状态
        title: Protection Status
        type: integer
      ref_client_uuid:
        description: 关联的HyperV主机的UUID
        title: Ref Client Uuid
        type: string
      root_uuid:
        description: 环境ID
        title: Root Uuid
        type: string
      sla_compliance:
        description: SLA遵从度
        title: Sla Compliance
        type: boolean
      sla_id:
        description: SLA ID
        title: Sla Id
        type: string
      sla_name:
        description: SLA名称
        title: Sla Name
        type: string
      sla_status:
        description: 保护激活状态
        title: Sla Status
        type: boolean
      sub_type:
        description: 资源子类型
        title: Sub Type
        type: string
      type:
        description: 资源类型
        title: Type
        type: string
      uncommitted:
        default: 0
        description: 未提交容量，仅用于数据存储
        title: Uncommitted
        type: integer
      user_id:
        description: 用户ID
        title: User Id
        type: string
      uuid:
        title: Uuid
        type: string
      version:
        description: 资源版本号
        title: Version
        type: string
      vm_ip:
        description: 虚拟机的IP地址
        title: Vm Ip
        type: string
    required:
      - name
      - uuid
    title: HyperVResourceSchema
    type: object
  ValidationError:
    properties:
      loc:
        items:
          type: string
        title: Location
        type: array
      msg:
        title: Message
        type: string
      type:
        title: Error Type
        type: string
    required:
      - loc
      - msg
      - type
    title: ValidationError
    type: object
x-components: {}
