swagger: '2.0'
info:
  version: v1
  title: 勒索软件防护接口
  contact: {}
  license: {}
host: localhost
basePath: /
tags:
  - name: Config Management
    description: Config Controller
  - name: Model Management
    description: Model Controller
paths:
  /v1/anti/ransomware/config:
    get:
      x-impact-subsystem: 影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      x-dp-admin-role: 'Y'
      x-auditor-role: 'Y'
      tags:
        - Config Management
      summary: 获取配置
      operationId: getConfigUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Config'
            originalRef: Config
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization:
            - global
    put:
      x-impact-subsystem: 影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Config Management
      summary: 设置配置
      operationId: setConfigUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
        - in: body
          name: config
          description: 配置参数
          required: true
          schema:
            $ref: '#/definitions/Config'
            originalRef: Config
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Config'
            originalRef: Config
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization:
            - global
  /v1/anti/ransomware/model:
    post:
      x-impact-subsystem: 影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Model Management
      summary: 增加模型
      operationId: addModelInfoUsingPOST
      consumes:
        - multipart/form-data
      produces:
        - '*/*'
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
        - name: modelFile
          in: formData
          description: 模型文件
          required: true
          type: file
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ModelInfo'
            originalRef: ModelInfo
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization:
            - global
    delete:
      x-impact-subsystem: 影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Model Management
      summary: 删除模型
      operationId: deleteModelUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
        - in: body
          name: deleteModelRequest
          description: 删除模型请求
          required: true
          schema:
            $ref: '#/definitions/DeleteModelRequest'
            originalRef: DeleteModelRequest
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/DeleteModelResponse'
            originalRef: DeleteModelResponse
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - Authorization:
            - global
  /v1/anti/ransomware/model/activate:
    put:
      x-impact-subsystem: 影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Model Management
      summary: 激活模型
      operationId: activateModelUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
        - in: body
          name: activateModelRequest
          description: 激活模型请求
          required: true
          schema:
            $ref: '#/definitions/ActivateModelRequest'
            originalRef: ActivateModelRequest
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ActivateModelResponse'
            originalRef: ActivateModelResponse
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization:
            - global
  /v1/anti/ransomware/models:
    get:
      x-impact-subsystem: 影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      x-dp-admin-role: 'Y'
      x-auditor-role: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Model Management
      summary: 获取模型列表
      operationId: getModelListUsingGET
      produces:
        - '*/*'
      parameters:
        - in: query
          name: pageNum
          description: 页的编号
          required: true
          schema:
            type: integer
            format: int64
        - in: query
          name: pageSize
          description: 每页数量
          required: true
          schema:
            type: integer
            format: int64
        - name: status
          in: query
          description: 模型状态
          required: false
          type: boolean
          x-example: 'false'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Response«List«ModelInfo»»'
            originalRef: Response«List«ModelInfo»»
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization:
            - global
securityDefinitions:
  Authorization:
    type: apiKey
    name: TOKEN
    in: header
definitions:
  ActivateModelRequest:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        example: 1
        description: 模型编号
    title: ActivateModelRequest
  ActivateModelResponse:
    type: object
    properties:
      activated:
        type: boolean
        description: 模型激活是否成功
    title: ActivateModelResponse
  Config:
    properties:
      dynamicDetection:
        type: boolean
        description: 是否开启动态探测
    title: Config
    required:
      - dynamicDetection
  DeleteModelRequest:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        example: 1
        description: 模型编号
    title: DeleteModelRequest
  DeleteModelResponse:
    type: object
    properties:
      deleted:
        type: boolean
        description: 模型删除是否成功
    title: DeleteModelResponse
  ModelInfo:
    type: object
    properties:
      desc:
        type: string
        description: 模型描述
      id:
        type: string
        description: 模型编号
      name:
        type: string
        description: 模型名称
      signatureInfo:
        type: string
        description: 签名信息
      status:
        type: boolean
        description: 模型状态
      updateTime:
        type: string
        description: 更新时间
      version:
        type: string
        description: 模型版本
    title: ModelInfo
  Response«List«ModelInfo»»:
    type: object
    properties:
      detailParams:
        type: array
        description: 错误参数
        items:
          type: string
      errorCode:
        type: integer
        format: int64
        description: 错误编码
      errorMessage:
        type: string
        description: 错误描述
      records:
        type: array
        description: 数据
        items:
          $ref: '#/definitions/ModelInfo'
          originalRef: ModelInfo
      totalCount:
        type: integer
        format: int64
        description: 翻页
    title: Response«List«ModelInfo»»
