swagger: '2.0'
info:
  title: 副本保护对象接口
  version: v1
tags:
  - name: protected_copy_object_api
paths:
  /v1/protected-copy-objects:
    delete:
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - description: 访问令牌
          in: header
          name: X-Auth-Token
          required: true
        - in: body
          name: body
          required: true
          schema:
            allOf:
              - $ref: '#/definitions/ProtectedCopyBatchOperationReq'
            description: 批量移除副本保护对象请求
            title: Req
      responses:
        '200':
          description: Successful Response
        '422':
          description: Validation Error
          schema:
            $ref: '#/definitions/HTTPValidationError'
      tags:
        - protected_copy_object_api
      description: 批量移除副本保护对象，解绑SLA
      operationId: delete_v1_protected_copy_objects_delete
      summary: 批量移除副本保护对象
    post:
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - description: 访问令牌
          in: header
          name: X-Auth-Token
          required: true
        - in: body
          name: body
          required: true
          schema:
            allOf:
              - $ref: '#/definitions/ProtectedCopyObjectUpdate'
            description: 创建副本保护对象请求
            title: Create Req
      responses:
        '200':
          description: Successful Response
          schema:
            $ref: '#/definitions/ProtectedCopyObjectId'
        '422':
          description: Validation Error
          schema:
            $ref: '#/definitions/HTTPValidationError'
      tags:
        - protected_copy_object_api
      description: 创建副本保护对象，绑定SLA
      operationId: create_v1_protected_copy_objects_post
      summary: 创建副本保护对象
    put:
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - description: 访问令牌
          in: header
          name: X-Auth-Token
          required: true
        - in: body
          name: body
          required: true
          schema:
            allOf:
              - $ref: '#/definitions/ProtectedCopyObjectUpdate'
            description: 修改副本保护对象请求
            title: Update Req
      responses:
        '200':
          description: Successful Response
        '422':
          description: Validation Error
          schema:
            $ref: '#/definitions/HTTPValidationError'
      tags:
        - protected_copy_object_api
      description: 修改副本保护对象，变更SLA
      operationId: modify_v1_protected_copy_objects_put
      summary: 修改副本保护对象
  /v1/protected-copy-objects/status/action/activate:
    put:
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - description: 访问令牌
          in: header
          name: X-Auth-Token
          required: true
        - in: body
          name: body
          required: true
          schema:
            allOf:
              - $ref: '#/definitions/ProtectedCopyBatchOperationReq'
            description: 批量激活保护副本操作请求
            title: Req
      responses:
        '200':
          description: Successful Response
        '422':
          description: Validation Error
          schema:
            $ref: '#/definitions/HTTPValidationError'
      tags:
        - protected_copy_object_api
      operationId: active_v1_protected_copy_objects_status_action_activate_put
      summary: 批量激活保护副本
  /v1/protected-copy-objects/status/action/deactivate:
    put:
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - description: 访问令牌
          in: header
          name: X-Auth-Token
          required: true
        - in: body
          name: body
          required: true
          schema:
            allOf:
              - $ref: '#/definitions/ProtectedCopyBatchOperationReq'
            description: 批量取消激活保护副本操作请求
            title: Req
      responses:
        '200':
          description: Successful Response
        '422':
          description: Validation Error
          schema:
            $ref: '#/definitions/HTTPValidationError'
      tags:
        - protected_copy_object_api
      operationId: deactivate_v1_protected_copy_objects_status_action_deactivate_put
      summary: 批量取消激活保护副本
  /v1/protected-copy-objects/action/replicate:
    post:
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - description: 访问令牌
          in: header
          name: X-Auth-Token
          required: true
        - in: body
          name: manual_replicate_req
          required: true
          schema:
            description: 手动复制请求体
            title: Create Req
            $ref: '#/definitions/ManualReplicationReq'
          description: 手动复制请求体
      responses:
        '200':
          description: OK
          schema:
            type: string
        '400':
          description: Bad Request
          schema:
            type: string
        '404':
          description: Not Found
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
        '502':
          description: Bad Gateway
          schema:
            type: string
      tags:
        - protected_copy_object_api
      description: 对资源进行手动复制
      operationId: manualReplicateUsiungPOST
      summary: 执行手动复制
definitions:
  Body_sync_replica_sla_change_v1_internal_protected_copy_objects_action_sync_sla_put:
    properties:
      sla_id:
        description: SLA的ID
        title: Sla Id
        type: string
    required:
      - sla_id
    title: >-
      Body_sync_replica_sla_change_v1_internal_protected_copy_objects_action_sync_sla_put
    type: object
  HTTPValidationError:
    properties:
      detail:
        items:
          $ref: '#/definitions/ValidationError'
        title: Detail
        type: array
    title: HTTPValidationError
    type: object
  ProtectedCopyBatchOperationReq:
    properties:
      resource_ids:
        description: 批量操作资源ID列表
        items:
          type: string
        title: Resource Ids
        type: array
    required:
      - resource_ids
    title: ProtectedCopyBatchOperationReq
    type: object
  ProtectedCopyObjectId:
    properties:
      uuid:
        description: 保护副本对象的ID
        title: Uuid
        type: string
    title: ProtectedCopyObjectId
    type: object
  ProtectedCopyObjectUpdate:
    properties:
      resource_id:
        description: 保护对象对应资源的ID
        maxLength: 128
        minLength: 1
        title: Resource Id
        type: string
      sla_id:
        description: 新SLA的ID
        format: uuid
        title: Sla Id
        type: string
    required:
      - sla_id
      - resource_id
    title: ProtectedCopyObjectUpdate
    type: object
  ValidationError:
    properties:
      loc:
        items:
          type: string
        title: Location
        type: array
      msg:
        title: Message
        type: string
      type:
        title: Error Type
        type: string
    required:
      - loc
      - msg
      - type
    title: ValidationError
    type: object
  ManualReplicationReq:
    type: object
    required:
      - sla_id
      - resource_id
      - policy_id
    properties:
      sla_id:
        type: string
        description: sla的id
      resource_id:
        type: string
        description: 资源id
      policy_id:
        type: string
        description: 选择的sla策略id
x-components: {}
