swagger: '2.0'
info:
  version: v1
  title: Kerberos管理接口
  contact: {}
  license: {}
host: localhost
basePath: /
tags:
  - name: Kerberos API
    description: Kerberos Controller
paths:
  /v1/kerberos:
    get:
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Kerberos API
      summary: 查询所有Kerberos
      operationId: queryAllKerberosUsingGET
      produces:
        - '*/*'
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
        - name: pageSize
          in: query
          description: 分页数量
          required: false
          type: integer
          maximum: 200.0
          minimum: 0.0
          format: int32
          x-example: 10
        - name: startPage
          in: query
          description: 分页起始页面
          required: false
          type: integer
          minimum: 0.0
          format: int32
          x-example: 0
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/BasePage«KerberosInfo»'
            originalRef: BasePage«KerberosInfo»
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization:
            - global
    post:
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Kerberos API
      summary: 添加Kerberos
      operationId: createKerberosUsingPOST
      consumes:
        - multipart/form-data
      produces:
        - '*/*'
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
        - in: formData
          name: createModel
          description: 创建模式
          required: true
          schema:
            type: string
        - name: keytabFile
          in: formData
          description: keytab文件
          required: false
          type: file
        - name: krb5File
          in: formData
          description: krb5文件
          required: false
          type: file
        - in: formData
          name: name
          description: 名称
          required: true
          pattern: '^[a-zA-Z0-9]{1,64}$'
          schema:
            type: string
        - in: formData
          name: password
          description: 密码
          required: false
          schema:
            type: string
        - in: formData
          name: principalName
          description: 主体名
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/KerberosIDResp'
            originalRef: KerberosIDResp
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization:
            - global
  '/v1/kerberos/{kerberos_id}':
    post:
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Kerberos API
      summary: 更新Kerberos
      operationId: updateKerberosUsingPOST
      consumes:
        - multipart/form-data
      produces:
        - '*/*'
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
        - in: formData
          name: createModel
          description: 创建模式
          required: false
          schema:
            type: string
        - name: kerberos_id
          in: path
          description: Kerberos ID
          required: true
          type: string
        - name: keytabFile
          in: formData
          description: keytab文件
          required: false
          type: file
        - name: krb5File
          in: formData
          description: krb5文件
          required: false
          type: file
        - in: formData
          name: name
          description: 名称
          required: true
          pattern: '^[a-zA-Z0-9]{1,64}$'
          schema:
            type: string
        - in: formData
          name: password
          description: 密码
          required: false
          schema:
            type: string
        - in: formData
          name: principalName
          description: 主体名
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization:
            - global
    delete:
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Kerberos API
      summary: 删除Kerberos
      operationId: deleteKerberosUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
        - name: kerberos_id
          in: path
          description: Kerberos ID
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/KerberosIDResp'
            originalRef: KerberosIDResp
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      security:
        - Authorization:
            - global
securityDefinitions:
  Authorization:
    type: apiKey
    name: TOKEN
    in: header
definitions:
  BasePage«KerberosInfo»:
    type: object
    properties:
      items:
        type: array
        description: 详情
        items:
          $ref: '#/definitions/KerberosInfo'
          originalRef: KerberosInfo
      page_no:
        type: integer
        format: int64
        description: 页码
      page_size:
        type: integer
        format: int64
        description: 每页总数
      pages:
        type: integer
        format: int64
        description: 总页数
      total:
        type: integer
        format: int64
        description: 总数
    title: BasePage«KerberosInfo»
  KerberosBo:
    type: object
    properties:
      createModel:
        type: string
      createTime:
        type: string
        format: date-time
      kerberosId:
        type: string
      keytabPath:
        type: string
      krb5Path:
        type: string
      name:
        type: string
      password:
        type: string
      principalName:
        type: string
      updateTime:
        type: string
        format: date-time
      userId:
        type: string
    title: KerberosBo
  KerberosIDResp:
    type: object
    properties:
      kerberos_id:
        type: string
        description: Kerberos ID
    title: KerberosIDResp
  KerberosInfo:
    type: object
    properties:
      createModel:
        type: string
        description: 创建模式
      createTime:
        type: string
        format: date-time
        description: 创建时间
      kerberosId:
        type: string
        description: Kerberos ID
      keytabPath:
        type: string
        description: keytab文件路径
      krb5Path:
        type: string
        description: krb5文件路径
      name:
        type: string
        description: 名称
      principalName:
        type: string
        description: 主体名
      updateTime:
        type: string
        format: date-time
        description: 更新时间
      userId:
        type: string
        description: 用户ID
    title: KerberosInfo
