swagger: '2.0'
info:
  version: v1
  title: 系统管理接口
  description: GroupDesc
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: ${system-api}
paths:
  /v1/system/service-status-info:
    get:
      x-product: OceanProtect X
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      x-rd-admin-role: 'Y'
      tags:
        - ${system-api}
      summary: 查询服务进度
      description: |-
        查询服务进度:
        查询标准备份服务或者SFTP服务的安装进度
      operationId: ListServiceStatusInfo
      parameters:
        - name: X-Auth-Token
          in: header
          required: true
          description: Access token
          type: string
        - name: serviceType
          in: query
          required: true
          description: 查询服务请求枚举
          type: string
          enum:
            - SFTP
            - STANDARD
          x-impact-subsystem: 不影响
          x-access-port: 25081
          x-auth-required: 'Y'
          x-public-api: 'Y'
      responses:
        '200':
          description: 需要返回的Ip个数
          schema:
            $ref: '#/definitions/ConfigStatus'
definitions:
  IpCountResponse:
    description: 当前需要配置的IP段的个数
    properties:
      ipCount:
        type: integer
        format: int32
        description: 返回的IP段个数
        minimum: 1
        maximum: 2
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
    required:
      - ipCount
  StandardServiceStatusResponse:
    description: 标准备份服务状态响应
    properties:
      status:
        type: string
        description: 判断标准备份服务状态结果
        x-impact-subsystem: 影响
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
    required:
      - status
  ConfigStatus:
    description: 开启标准备份服务状态
    required:
      - status
    properties:
      status:
        type: integer
        format: int32
        description: 执行状态
      code:
        type: string
        description: 错误码
      desc:
        type: string
        description: 错误描述
      rate:
        type: integer
        format: int32
        description: 进入比率
      params:
        type: array
        items:
          type: string
        description: 错误参数
  StandardBackupServiceConfig:
    description: 初始化标准备份服务
    properties:
      serviceIp:
        type: string
        description: 浮动IP
      serviceType:
        type: string
        description: 服务类型
        enum:
          - SFTP
          - STANDARD
        x-impact-subsystem: 不影响
        x-access-port: 25081
        x-auth-required: 'Y'
        x-public-api: 'Y'
