---
swagger: "2.0"
info:
  version: "v1"
  title: "DEE Anti Ransomware API Document"
  contact: {}
  license: {}
host: "localhost"
basePath: "/"
tags:
- name: "Config Management"
  description: "Config Controller"
- name: "Detect Result Management"
  description: "Detect Result Controller"
- name: "Task Management"
  description: "Detect Task Controller"
- name: "Model Management"
  description: "Model Controller"
paths:
  /v1/anti/ransomware/config/action/get:
    post:
      tags:
      - "Config Management"
      summary: "获取配置"
      operationId: "getConfigUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      responses:
        "200":
          description: "OK"
          schema:
            originalRef: "Config"
            $ref: "#/definitions/Config"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/anti/ransomware/config/action/set:
    post:
      tags:
      - "Config Management"
      summary: "设置配置"
      operationId: "setConfigUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "config"
        description: "配置参数"
        required: true
        schema:
          originalRef: "Config"
          $ref: "#/definitions/Config"
      responses:
        "200":
          description: "OK"
          schema:
            originalRef: "Config"
            $ref: "#/definitions/Config"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/anti/ransomware/detect/copy/false/action/alarm:
    post:
      tags:
      - "Detect Result Management"
      summary: "误报处理"
      operationId: "handleFalseAlarmUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "falseAlarmRequest"
        description: "误报处理请求"
        required: true
        schema:
          originalRef: "DetectFalseAlarmRequest"
          $ref: "#/definitions/DetectFalseAlarmRequest"
      responses:
        "200":
          description: "OK"
          schema:
            originalRef: "DetectFalseAlarmResponse"
            $ref: "#/definitions/DetectFalseAlarmResponse"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/anti/ransomware/detect/copy/feature/action/delete:
    post:
      tags:
      - "Detect Result Management"
      summary: "根据副本id删除特征文件"
      operationId: "deleteByCopyIdUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "request"
        description: "根据副本id删除特征文件"
        required: true
        schema:
          originalRef: "DeleteByCopyIdRequest"
          $ref: "#/definitions/DeleteByCopyIdRequest"
      responses:
        "200":
          description: "OK"
          schema:
            originalRef: "DeleteByCopyIdResponse"
            $ref: "#/definitions/DeleteByCopyIdResponse"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/anti/ransomware/detect/task/action/add:
    post:
      tags:
      - "Task Management"
      summary: "增加探测任务"
      operationId: "addTaskUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "addTaskRequest"
        description: "探测任务"
        required: true
        schema:
          originalRef: "AddTaskRequest"
          $ref: "#/definitions/AddTaskRequest"
      responses:
        "200":
          description: "OK"
          schema:
            originalRef: "AddTaskResponse"
            $ref: "#/definitions/AddTaskResponse"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/anti/ransomware/detect/task/action/delete:
    post:
      tags:
      - "Task Management"
      summary: "删除资源的探测任务"
      operationId: "deleteTasksUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "deleteTaskRequest"
        description: "删除任务请求"
        required: true
        schema:
          originalRef: "DeleteTaskRequest"
          $ref: "#/definitions/DeleteTaskRequest"
      responses:
        "200":
          description: "OK"
          schema:
            originalRef: "DeleteTaskResponse"
            $ref: "#/definitions/DeleteTaskResponse"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/anti/ransomware/detect/task/action/get:
    post:
      tags:
      - "Task Management"
      summary: "查询探测任务"
      operationId: "getTaskUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "getTaskRequest"
        description: "获取任务"
        required: true
        schema:
          originalRef: "GetTaskRequest"
          $ref: "#/definitions/GetTaskRequest"
      responses:
        "200":
          description: "OK"
          schema:
            originalRef: "GetTaskResponse"
            $ref: "#/definitions/GetTaskResponse"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/anti/ransomware/model/action/activate:
    post:
      tags:
      - "Model Management"
      summary: "激活模型"
      operationId: "activateModelUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "activateModelRequest"
        description: "激活模型请求"
        required: true
        schema:
          originalRef: "ActivateModelRequest"
          $ref: "#/definitions/ActivateModelRequest"
      responses:
        "200":
          description: "OK"
          schema:
            originalRef: "ActivateModelResponse"
            $ref: "#/definitions/ActivateModelResponse"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/anti/ransomware/model/action/delete:
    post:
      tags:
      - "Model Management"
      summary: "删除模型"
      operationId: "deleteModelUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "deleteModelRequest"
        description: "删除模型请求"
        required: true
        schema:
          originalRef: "DeleteModelRequest"
          $ref: "#/definitions/DeleteModelRequest"
      responses:
        "200":
          description: "OK"
          schema:
            originalRef: "DeleteModelResponse"
            $ref: "#/definitions/DeleteModelResponse"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/anti/ransomware/model/action/upload:
    post:
      tags:
      - "Model Management"
      summary: "增加模型"
      operationId: "addModelInfoUsingPOST"
      consumes:
      - "multipart/form-data"
      produces:
      - "*/*"
      parameters:
      - name: "modelFile"
        in: "formData"
        description: "模型文件"
        required: true
        type: "file"
      responses:
        "200":
          description: "OK"
          schema:
            originalRef: "ModelInfo"
            $ref: "#/definitions/ModelInfo"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/anti/ransomware/models/action/get:
    post:
      tags:
      - "Model Management"
      summary: "获取模型列表"
      operationId: "getModelListUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "getModelListRequest"
        description: "获取模型列表请求"
        required: true
        schema:
          originalRef: "GetModelListRequest"
          $ref: "#/definitions/GetModelListRequest"
      responses:
        "200":
          description: "OK"
          schema:
            originalRef: "Response«List«ModelInfo»»"
            $ref: "#/definitions/Response«List«ModelInfo»»"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
securityDefinitions:
  Authorization:
    type: "apiKey"
    name: "TOKEN"
    in: "header"
definitions:
  ActivateModelRequest:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "string"
        example: 1
        description: "模型编号"
    title: "ActivateModelRequest"
  ActivateModelResponse:
    type: "object"
    properties:
      activated:
        type: "boolean"
    title: "ActivateModelResponse"
  AddTaskRequest:
    type: "object"
    required:
    - "copyGn"
    - "copyId"
    - "resourceId"
    - "resourceType"
    - "snapId"
    - "snapMetadata"
    - "storageAddress"
    - "storagePassword"
    - "storagePort"
    - "storageUsername"
    properties:
      copyGn:
        type: "integer"
      copyId:
        type: "string"
      copyType:
        type: "string"
      requestId:
        type: "string"
      resourceId:
        type: "string"
      resourceType:
        type: "string"
      snapId:
        type: "string"
      snapMetadata:
        type: "string"
      storageAddress:
        type: "string"
      storagePassword:
        type: "string"
      storagePort:
        type: "string"
      storageProtocol:
        type: "string"
      storageType:
        type: "string"
      storageUsername:
        type: "string"
    title: "AddTaskRequest"
  AddTaskResponse:
    type: "object"
    properties:
      taskCode:
        type: "string"
    title: "AddTaskResponse"
  Config:
    type: "object"
    required:
    - "taskConcurrencyLimit"
    properties:
      dynamicDetection:
        type: "boolean"
      taskConcurrencyLimit:
        type: "integer"
        format: "int32"
        example: 10
        description: "配置任务并发上限"
        minimum: 1.0
        maximum: 1000.0
        exclusiveMinimum: false
        exclusiveMaximum: false
    title: "Config"
  DeleteByCopyIdRequest:
    type: "object"
    properties:
      copyIdList:
        type: "array"
        items:
          type: "string"
    title: "DeleteByCopyIdRequest"
  DeleteByCopyIdResponse:
    type: "object"
    properties:
      deleted:
        type: "boolean"
    title: "DeleteByCopyIdResponse"
  DeleteModelRequest:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "string"
        example: 1
        description: "模型编号"
    title: "DeleteModelRequest"
  DeleteModelResponse:
    type: "object"
    properties:
      deleted:
        type: "boolean"
    title: "DeleteModelResponse"
  DeleteTaskRequest:
    type: "object"
    required:
    - "resourceIds"
    properties:
      resourceIds:
        type: "array"
        items:
          type: "string"
    title: "DeleteTaskRequest"
  DeleteTaskResponse:
    type: "object"
    properties:
      stopTaskCodes:
        type: "array"
        items:
          type: "string"
    title: "DeleteTaskResponse"
  DetectFalseAlarmRequest:
    type: "object"
    required:
    - "copyIds"
    properties:
      copyIds:
        type: "array"
        items:
          type: "string"
    title: "DetectFalseAlarmRequest"
  DetectFalseAlarmResponse:
    type: "object"
    properties:
      falseAlarmResponseDetails:
        type: "array"
        items:
          originalRef: "FalseAlarmResponseDetail"
          $ref: "#/definitions/FalseAlarmResponseDetail"
    title: "DetectFalseAlarmResponse"
  FalseAlarmResponseDetail:
    type: "object"
    properties:
      copyId:
        type: "string"
      newStatus:
        type: "string"
      oldStatus:
        type: "string"
    title: "FalseAlarmResponseDetail"
  GetModelListRequest:
    type: "object"
    required:
    - "pageNum"
    - "pageSize"
    properties:
      pageNum:
        type: "integer"
        format: "int64"
        example: 1
        description: "页的编号"
        minimum: 1.0
        maximum: 500.0
        exclusiveMinimum: false
        exclusiveMaximum: false
      pageSize:
        type: "integer"
        format: "int64"
        example: 10
        description: "每页数量"
        minimum: 1.0
        maximum: 100.0
        exclusiveMinimum: false
        exclusiveMaximum: false
      status:
        type: "boolean"
        example: false
        description: "模型状态"
    title: "GetModelListRequest"
  GetTaskReport:
    type: "object"
    properties:
      taskCode:
        type: "string"
        description: "报告关联的任务编号"
    title: "GetTaskReport"
  GetTaskRequest:
    type: "object"
    required:
    - "taskCode"
    properties:
      taskCode:
        type: "string"
        example: 10
        description: "任务编号"
    title: "GetTaskRequest"
  GetTaskResponse:
    type: "object"
    properties:
      report:
        description: "任务报告"
        originalRef: "GetTaskReport"
        $ref: "#/definitions/GetTaskReport"
      status:
        type: "string"
        example: "COMPLETED"
        description: "任务状态"
        enum:
        - "IRRELEVANT"
        - "WAITING"
        - "DETECTING"
        - "COMPLETED"
      taskCode:
        type: "string"
        example: 10
        description: "任务编号"
    title: "GetTaskResponse"
  ModelInfo:
    type: "object"
    properties:
      desc:
        type: "string"
        description: "模型描述"
      id:
        type: "string"
        description: "模型编号"
      name:
        type: "string"
        description: "模型名称"
      signatureInfo:
        type: "string"
        description: "签名信息"
      status:
        type: "boolean"
        description: "模型状态"
      updateTime:
        type: "string"
        description: "更新时间"
      version:
        type: "string"
        description: "模型版本"
    title: "ModelInfo"
  Response«List«ModelInfo»»:
    type: "object"
    properties:
      detailParams:
        type: "array"
        description: "错误参数"
        items:
          type: "string"
      errorCode:
        type: "integer"
        format: "int64"
        description: "错误编码"
      errorMessage:
        type: "string"
        description: "错误描述"
      records:
        type: "array"
        description: "数据"
        items:
          originalRef: "ModelInfo"
          $ref: "#/definitions/ModelInfo"
      totalCount:
        type: "integer"
        format: "int64"
        description: "翻页"
    title: "Response«List«ModelInfo»»"
