# ---------------------------------------------------------------------
#
# $file: Dockerfile.integration
# $author: Protect Manager
#
# build docker for integration tests
# ---------------------------------------------------------------------

ARG jdk_tag=11.0.5-slim
ARG mvn_tag=v1.3


# ---------------------------------------------------------------------
# Build image
# ---------------------------------------------------------------------
FROM emei-il.huawei.com/mvn:${mvn_tag} as build

WORKDIR   /app

COPY    src/integration/src       ./src
COPY    src/integration/pom.xml   .

RUN mvn clean install


# ---------------------------------------------------------------------
# Build Integration Test Slim
# ---------------------------------------------------------------------
FROM openjdk:${jdk_tag}

ARG JAR_PATH=/app/target


WORKDIR /app
COPY --from=build ${JAR_PATH}/IntegrationTests.jar ./

CMD ["java", "-Djava.security.egd=file:/dev/urandom", "-jar",  "IntegrationTests.jar"]
