---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: emeistor-gui
  name: emeistor-gui
  namespace: default
spec:
  replicas: 1
  selector:
      matchLabels:
          k8s-app: emeistor-gui
  template:
    metadata:
      labels:
        k8s-app: emeistor-gui
    spec:
      containers:
      - name: emeistor-gui
        image: emei-il.huawei.com/dev/skaffold/sample-user/emeistor-gui
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /index.html
            port: 8080
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8080
          failureThreshold: 10
        ports:
          - containerPort: 8080
        env:
            - name: SERVICE_MODE
              value: real
            - name: LOGLEVEL
              valueFrom:
                  configMapKeyRef:
                      name: service-env-config
                      key: LOGLEVEL
      securityContext:
        runAsGroup: 1001
        runAsUser: 1001

---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: emeistor-gui
  name: emeistor-gui-server
spec:
  ports:
  - name: emeistor-gui-port
    port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    k8s-app: emeistor-gui
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: emeistor-gui
spec:
  gateways:
  - emeistor-gateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: emeistor-gui-server
        port:
          number: 80