---
version: 2.0

envs:
  - condition: ENV_VM == "VPC"
    label: OceanProtect_X8000_1.3.0_euler_arm_VPC
  - condition: ENV_VM != "VPC"
    label: X8000_1.3.0_euler_arm

#是否固定构建根目录
buildspace:
  fixed: true

params:
  - name: PRODUCT
    value: ${PRODUCT}
  - name: PM_BRANCH
    value: ${branch}

steps:
  CONFIG_ENV:
    - sh:
        command: |
          systemctl restart docker
          chmod -R 777 /var/run/docker*
          chmod 777 /run/docker*
          ls -l /run/docker*
          rm -rf /devcloud/maven/repository/org/apache/logging
          rm -rf /devcloud/maven/repository/com/huawei/oceanprotect/
        sudo: true
  PRE_BUILD:
    - manifest_checkout:
        manifest_file: ${dependency_path}
        groups: ${manifest_groups}
        strict: "false"
  BUILD:
    - build_execute:
        command: bash -c "
          cd ProtectManager/CI/script
          && sh Package.sh ${PRODUCT} ${PM_BRANCH} ${Service_Name}"
        accelerate:
          isAccelerate: false
          isCache: true
        check:
          auto: true
          mode: sync

