/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2021-2021. All rights reserved.
 */

package openbackup.data.protection.access.provider.sdk.copy;

import openbackup.data.protection.access.provider.sdk.base.DataProtectionProvider;
import openbackup.data.protection.access.provider.sdk.exception.NotImplementedException;

import java.util.Collections;
import java.util.List;

/**
 * 功能描述
 *
 * @author h30003246
 * @since 2020-08-24
 */
public interface CopyProvider extends DataProtectionProvider<CopyBo> {
    /**
     * This method is used for delete the copy according to retention policy.
     *
     * @param requestId requestId
     * @param copy copy info
     */
    void deleteCopy(String requestId, CopyInfoBo copy);

    /**
     * This method is used for build copy info
     *
     * @param requestId unique uuid throughout in one backup process
     * @param backupId  The copy ID generated by the backup task
     * @param instanceId  The copy ID generated by the backup task
     * @return 副本信息
     */
    default CopyInfoBo buildCopy(String requestId, String backupId, String instanceId) {
        throw new NotImplementedException("Not Implemented Exception");
    }

    /**
     * This method is used for build copy info
     *
     * @param requestId unique uuid throughout in one backup process
     * @param backupId The copy ID generated by the backup task
     * @param instanceId The copy ID generated by the backup task
     * @param subType 副本对应的资源子类型
     * @return 副本信息
     */
    default List<CopyInfoBo> buildCopy(String requestId, String backupId, String instanceId, String subType) {
        return Collections.singletonList(buildCopy(requestId, backupId, instanceId));
    }
}
