package openbackup.system.base.sdk.copy.model;

import openbackup.system.base.common.constants.CommonErrorCode;
import openbackup.system.base.common.exception.LegoCheckedException;

import com.google.common.collect.ImmutableList;

import java.util.Arrays;
import java.util.List;

/**
 * 功能描述
 *
 * @author j00364432
 * @version [OceanProtect A8000 1.0.0 2020.8]
 * @since 2020-12-11
 */
public enum CopyGeneratedByEnum {
    /**
     * The copy is generated by backup
     */
    BY_BACKUP("Backup"),

    /**
     * The copy is generated by cloud archive
     */
    BY_CLOUD_ARCHIVE("CloudArchive"),

    /**
     * The copy is generated by tape archive
     */
    BY_TAPE_ARCHIVE("TapeArchive"),

    /**
     * The copy is generated by live mount
     */
    BY_LIVE_MOUNTE("live_mount"),

    /**
     * The copy is generated by replicated
     */
    BY_REPLICATED("Replicated"),

    /**
     * The copy is generated by Imported
     */
    BY_IMPORTED("Imported"),

    /**
     * The copy is generated by common interface backup
     */
    BY_COMMON_INTERFACE_BACKUP("CommonInterfaceBackup"),

    /**
     * dws副本归档到磁带的需要先下载到A8000，再做恢复
     * 其他应用副本，包括dws归档到云的副本不用下载到A8000，直接恢复
     */
    BY_DOWNLOAD("Download"),

    /**
     * 由级联复制生成
     */
    BY_CASCADED_REPLICATION("CascadedReplication"),

    /**
     * 由反向复制生成
     */
    BY_REVERSE_REPLICATION("ReverseReplication");

    private static final List<CopyGeneratedByEnum> RESTORE_CAN_STOP = Arrays.asList(CopyGeneratedByEnum.BY_BACKUP,
        CopyGeneratedByEnum.BY_CLOUD_ARCHIVE, CopyGeneratedByEnum.BY_TAPE_ARCHIVE, CopyGeneratedByEnum.BY_REPLICATED,
        CopyGeneratedByEnum.BY_LIVE_MOUNTE, CopyGeneratedByEnum.BY_IMPORTED);

    /**
     * 副本复制生成方式列表
     */
    public static final List<String> COPY_GENERATED_BY_REPLICATION = ImmutableList.of(
        CopyGeneratedByEnum.BY_REPLICATED.value(), CopyGeneratedByEnum.BY_CASCADED_REPLICATION.value(),
        CopyGeneratedByEnum.BY_REVERSE_REPLICATION.value());

    private final String generatedBy;

    CopyGeneratedByEnum(String generatedBy) {
        this.generatedBy = generatedBy;
    }

    /**
     * return the value
     *
     * @return String
     */
    public String value() {
        return generatedBy;
    }

    /**
     * 根据副本生成类型获取副本生成类型的枚举类
     *
     * @param generatedType 副本生成类型
     * @return 副本生成类型的枚举类 {@code CopyGeneratedByEnum}
     */
    public static CopyGeneratedByEnum getByGenerateType(String generatedType) {
        return Arrays.stream(CopyGeneratedByEnum.values())
            .filter(generateType -> generateType.generatedBy.equals(generatedType))
            .findFirst()
            .orElseThrow(() -> new LegoCheckedException(CommonErrorCode.ILLEGAL_PARAM, "copy type illegal!"));
    }

    /**
     * 当前副本生成类型是否支持恢复任务停止
     *
     * @return 是否支持恢复任务停止
     */
    public boolean restoreCanStop() {
        return RESTORE_CAN_STOP.contains(this);
    }
}
