swagger: '2.0'
info:
  version: v1
  title: ApplicationTitle
  description: GroupDesc
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: anti-ransomware-network-api
    description: 安全一体机网络相关api
paths:
  /v1/anti-ransomware/oceancyber/network/iface:
    get:
      tags:
        - anti-ransomware-network-api
      x-dr-role: 'N'
      x-product: OceanCyber
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      operationId: QueryIFaceDetail
      summary: 查询设备网卡详情
      description: 查询设备网卡详情
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - name: iFace
          in: query
          required: true
          description: 网卡接口名
          type: string
          minLength: 1
          maxLength: 64
        - name: pageNo
          in: query
          required: false
          description: 页码
          type: string
          default: 0
          allowEmptyValue: true
        - name: pageSize
          in: query
          required: false
          description: 页大小
          type: string
          allowEmptyValue: true
          minLength: 1
          maxLength: 200
      responses:
        '200':
          description: 网卡关联租户信息查询信息对象
          schema:
            $ref: '#/definitions/PageListResponse'
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking. Format is request_uuid-timestamp-hostname.
        '400':
          description: Error response
          schema:
            $ref: '#/definitions/ErrorRsp'
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking. Format is request_uuid-timestamp-hostname.
  /v1/anti-ransomware/oceancyber/network:
    get:
      tags:
        - anti-ransomware-network-api
      x-dr-role: 'N'
      x-product: OceanCyber
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      operationId: QueryNetworkInfo
      summary: 查询安全一体机宿主机网络信息
      description: 查询安全一体机宿主机网络信息
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - in: body
          name: CreateDemoInfoRequestBody
          description: DemoInfo object that needs to be created
          required: true
          schema:
            $ref: '#/definitions/NetworkInfoResponse'
        - name: pageNo
          in: query
          required: false
          description: 页码
          type: integer
          format: int32
        - name: pageSize
          in: query
          required: false
          description: 页大小
          type: integer
          format: int32
      responses:
        '200':
          description: Demo Information
          schema:
            $ref: '#/definitions/NetworkInfoResponse'
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking. Format is request_uuid-timestamp-hostname.
        '400':
          description: Error response
          schema:
            $ref: '#/definitions/ErrorRsp'
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking. Format is request_uuid-timestamp-hostname.
    post:
      tags:
        - anti-ransomware-network-api
      x-dr-role: 'N'
      x-product: OceanCyber
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      operationId: CreateNetworkRelation
      summary: 绑定网卡与租户关系
      description: 绑定网卡与租户关系
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - in: body
          name: CreateIFaceRelationReq
          description: DemoInfo object that needs to be modified
          required: true
          schema:
            $ref: '#/definitions/CreateIFaceRelationReq'
      responses:
        '200':
          description: OK
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking. Format is request_uuid-timestamp-hostname.
        '400':
          description: Error response
          schema:
            $ref: '#/definitions/ErrorRsp'
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking. Format is request_uuid-timestamp-hostname.
    delete:
      tags:
        - anti-ransomware-network-api
      x-dr-role: 'N'
      x-product: OceanCyber
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      operationId: BatchDeleteNetWorkRelation
      summary: 批量删除绑定网卡与租户关系
      description: 批量删除绑定网卡与租户关系
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - name: relationIds
          in: query
          required: true
          description: 网卡与租户关系ID集合
          type: array
          items:
            type: integer
            format: int64
            minimum: 1
            maximum: 20000
      responses:
        '200':
          description: OK
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking. Format is request_uuid-timestamp-hostname.
        '400':
          description: Error response
          schema:
            $ref: '#/definitions/ErrorRsp'
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking. Format is request_uuid-timestamp-hostname.
definitions:
  NetworkInfoResponse:
    description: 安全一体机宿主机网络信息列表
    properties:
      totalCount:
        type: integer
        format: int32
        description: 总条数
        readOnly: true
        example: 28f61af50fc9452aa0ed5ea25c3cc3d3
      records:
        type: array
        items:
          $ref: '#/definitions/OceanCyberNetworkInfo'
        description: 安全一体机宿主机网络信息列表
    type: object
  ErrorRsp:
    description: 失败时返回的错误对象
    required:
      - error_code
      - error_msg
    properties:
      error_code:
        description: 错误码
        type: string
        minLength: 8
        maxLength: 36
      error_msg:
        description: 错误描述
        type: string
        minLength: 2
        maxLength: 512
  IFaceRelation:
    type: object
    description: 网卡关联租户信息信息
    properties:
      id:
        type: integer
        format: int64
        description: id
      iFace:
        type: string
        description: 网卡接口名
      esn:
        type: string
        description: 设备ESN
      vStoreId:
        type: string
        format: int32
        description: 存储设备租户id
      netmask:
        type: string
        description: 子网掩码
      gateway:
        type: string
        description: 网关
  PageListResponse:
    type: object
    properties:
      totalCount:
        type: string
        description: 总条数
      records:
        type: array
        items:
          $ref: '#/definitions/IFaceRelation'
        description: 网卡关联租户信息对象列表
  OceanCyberNetworkInfo:
    type: object
    description: 安全一体机网络配置信息
    properties:
      iFace:
        type: string
        description: 网卡接口名
      ip:
        type: string
        description: 网卡ip
      macAddress:
        type: string
        description: MacAddress
      broadcast:
        type: string
        description: broadcast
      netmask:
        type: string
        description: 子网掩码
      parentName:
        type: string
        description: vlan父网卡接口名称
      inet6:
        type: string
        description: ip v6地址
  CreateIFaceRelationReq:
    type: object
    description: 创建绑定网卡与租户关系请求
    required:
      - iFace
      - esn
      - vStoreId
      - netmask
    properties:
      iFace:
        type: string
        description: 网卡接口名
        minLength: 1
        maxLength: 64
      esn:
        type: string
        description: 设备ESN
        minLength: 1
        maxLength: 64
      vStoreId:
        type: string
        description: 存储设备租户id
        minLength: 1
        maxLength: 64
      netmask:
        type: string
        description: 子网掩码(默认255.255.255.255)
        pattern: ([1-9]|[1-9]\d|1\d{2}|2[0-4]\d|25[0-5])(\.(\d|[1-9]\d|1\d{2}|2[0-4]\d|25[0-5])){3}
      gateway:
        type: string
        description: 网关
        pattern: ([1-9]|[1-9]\d|1\d{2}|2[0-4]\d|25[0-5])(\.(\d|[1-9]\d|1\d{2}|2[0-4]\d|25[0-5])){3}
