swagger: '2.0'
info:
  version: v1
  title: ApplicationTitle
  description: GroupDesc
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: HcsResourceService
paths:
  /v1.0/servers:
    get:
      tags:
        - HcsResourceService
      operationId: GetEcmServer
      parameters:
        - name: offset
          in: query
          required: false
          type: integer
          format: int32
        - name: not-tags
          in: query
          required: false
          type: string
        - name: limit
          in: query
          required: false
          type: integer
          format: int32
        - name: expect_fields
          in: query
          required: false
          type: string
        - name: expect_capabilities
          in: query
          required: false
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/servers'
  /v1/resource-tags/availability_zone:
    get:
      tags:
        - HcsResourceService
      operationId: GetHcsAz
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/azResponse'
definitions:
  servers:
    type: object
    properties:
      count:
        type: integer
        format: int32
        example: 0
      servers:
        type: array
        items:
          type: string
  azResponse:
    type: object
    properties:
      resources:
        items:
          properties:
            resource_id:
              type: string
              example: az2.dc2
            resource_type:
              type: string
              example: availability_zone
            tags:
              properties:
                cloud_location:
                  type: array
                  items:
                    type: string
                  example:
                    - '1'
                virtual_capability:
                  type: array
                  items:
                    type: string
                  example:
                    - Ironic
                cloud_location_label:
                  type: array
                  items:
                    type: string
                  example:
                    - private_cloud_az0.dc0(localcloud)
                arch_type:
                  type: array
                  items:
                    type: string
                  example:
                    - x86_64
                storage_capability:
                  type: array
                  items:
                    type: string
                  example:
                    - Other
                display_name:
                  type: array
                  items:
                    type: string
                  example:
                    - AZ2_BMS
                network_capability:
                  type: array
                  items:
                    type: string
                  example:
                    - neutron+
        type: array
