swagger: '2.0'
info:
  version: v1
  title: DEE Base Parser API Document
  contact: {}
  license: {}
host: localhost
basePath: /
tags:
  - name: RestoreFilesController
    description: RestoreFilesController
paths:
  /v1/flr/network/check:
    post:
      tags:
        - RestoreFilesController
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      operationId: checkDestConnection
      parameters:
        - name: X-Auth-Token
          in: header
          required: true
          description: token
          type: string
        - name: checkDestConnectionRequest
          in: body
          required: true
          description: 请求参数
          schema:
            $ref: '#/definitions/CheckDestConnectionRequest'
      responses:
        '200':
          description: ''
          schema:
            type: string
securityDefinitions:
  Authorization:
    type: apiKey
    name: TOKEN
    in: header
definitions:
  StatusResponse:
    type: object
    properties:
      errorCode:
        type: string
      errorMessage:
        type: string
      file_name:
        type: string
      file_status:
        type: string
      request_id:
        type: string
    title: StatusResponse
  CheckDestConnectionRequest:
    type: object
    required:
      - username
      - password
      - osType
      - vmIp
    properties:
      username:
        type: string
        description: 用户名
      password:
        type: string
        description: 密码
      osType:
        type: string
        description: 操作系统类型 Linux或Windows
      vmIp:
        type: string
        description: 目标位置ip
