swagger: '2.0'
info:
  version: v1
  title: 勒索软件AirGap策略接口
host: localhost
basePath: /
tags:
  - name: anti-ransomware-airgap-api
    description: 防勒索AirGap策略
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /v1/anti-ransomware/airgaps:
    post:
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - anti-ransomware-airgap-api
      summary: 创建airGap策略
      description: 创建airGap策略
      operationId: CreateAirGap
      consumes:
        - application/json
      parameters:
        - name: X-Auth-Token
          in: header
          required: true
          description: Access token
          type: string
        - name: CreateAirGapRequestBody
          in: body
          required: true
          description: 防勒索AirGap创建，更新请求对象
          schema:
            $ref: '#/definitions/AirGapCreateRequest'
      responses:
        '200':
          description: OK
      x-order: 0
    get:
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - anti-ransomware-airgap-api
      summary: 查询AirGap策略列表
      description: 查询AirGap策略列表
      operationId: ListAirGaps
      parameters:
        - name: name
          in: query
          required: false
          description: 名称
          type: string
          minLength: 1
          maxLength: 64
        - name: statuses
          in: query
          required: false
          description: 状态
          type: array
          maxItems: 2
          items:
            type: string
          enum:
            - enable
            - disable
        - name: pageNo
          in: query
          required: false
          description: 起始页
          type: integer
          format: int32
          minimum: 0
          default: 0
        - name: pageSize
          in: query
          required: false
          description: 终止页
          type: integer
          format: int32
          minimum: 1
          maximum: 200
          default: 10
        - name: X-Auth-Token
          in: header
          required: true
          description: 访问令牌
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/PageListResponse'
      x-order: 2
  /v1/anti-ransomware/airgaps/{airGapId}:
    get:
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - anti-ransomware-airgap-api
      summary: 查询单个AirGap策略
      description: 查询单个AirGap策略
      operationId: ShowAirGap
      parameters:
        - name: airGapId
          in: path
          required: true
          type: string
          description: AirGap策略id
        - name: X-Auth-Token
          in: header
          required: true
          description: Access token
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/AirGapDetailVo'
      x-order: 1
    delete:
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - anti-ransomware-airgap-api
      summary: 删除单个AirGap策略
      description: 删除单个AirGap策略
      operationId: DeleteAirGap
      parameters:
        - name: airGapId
          in: path
          required: true
          type: string
          description: AirGap策略id
        - name: X-Auth-Token
          in: header
          required: true
          description: Access token
          type: string
      responses:
        '200':
          description: OK
      x-order: 4
    put:
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - anti-ransomware-airgap-api
      summary: 修改AirGap策略
      description: 修改AirGap策略
      operationId: UpdateAirGap
      parameters:
        - name: airGapId
          in: path
          required: true
          type: string
          description: 策略id
        - name: X-Auth-Token
          in: header
          required: true
          description: 访问令牌
          type: string
        - name: UpdateAirGapRequestBody
          in: body
          required: true
          description: 防勒索AirGap创建,更新请求对象
          schema:
            $ref: '#/definitions/AirGapCreateRequest'
      responses:
        '200':
          description: OK
      x-order: 3
  /v1/anti-ransomware/airgaps/{airGapId}/action/activate:
    put:
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - anti-ransomware-airgap-api
      summary: 激活AirGap策略
      description: 激活AirGap策略
      operationId: StartActivateAirGap
      parameters:
        - name: airGapId
          in: path
          required: true
          type: string
          description: 策略id
        - name: X-Auth-Token
          in: header
          required: true
          description: 访问令牌
          type: string
      responses:
        '200':
          description: OK
      x-order: 5
  /v1/anti-ransomware/airgaps/{airGapId}/action/deactivate:
    put:
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - anti-ransomware-airgap-api
      summary: 禁用AirGap策略
      description: 禁用AirGap策略
      operationId: StartDeactivateAirGap
      parameters:
        - name: airGapId
          in: path
          required: true
          type: string
          description: 策略id
        - name: X-Auth-Token
          in: header
          required: true
          description: 访问令牌
          type: string
      responses:
        '200':
          description: OK
  /v1/anti-ransomware/airgaps/port-details:
    get:
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - anti-ransomware-airgap-api
      summary: 查询AirGap端口信息
      description: 查询AirGap端口信息
      operationId: ListAirGapPorts
      parameters:
        - name: X-Auth-Token
          in: header
          required: true
          description: 访问令牌
          type: string
      responses:
        '200':
          description: AirGap端口信息列表
          schema:
            $ref: '#/definitions/AirGapPortVoList'
definitions:
  AirGapCreateRequest:
    type: object
    description: 防勒索AirGap创建，更新请求对象
    properties:
      name:
        type: string
        description: 名称
        pattern: ^[a-zA-Z0-9_\u4e00-\u9fa5]{1}[\u4e00-\u9fa5\w-]*$
        example: test_airgap
      description:
        type: string
        description: 描述
        minLength: 0
        maxLength: 255
        example: 测试airgap生成策略描述
      isForceStop:
        type: boolean
        description: 是否强制中止复制
        example: ''
        enum:
          - 'true'
          - 'false'
      triggerCycle:
        type: string
        description: 触发周期。按天day，按周week
        enum:
          - day
          - week
        example: day
      triggerWeekFreq:
        type: string
        description: 周触发频率,逗号拼接。
        example: ”mon,tue,wed,thu,fri,sat,sun”
      startTime:
        type: string
        description: 开始时间HH:mm
        example: '09:30'
      endTime:
        type: string
        description: 结束时间HH:mm
        example: '18:00'
      airGapPortIds:
        type: array
        items:
          type: string
          maxLength: 64
        description: 关联逻辑端口Id列表
        minItems: 1
        example: null
    required:
      - name
      - triggerCycle
      - triggerWeekFreq
      - startTime
      - endTime
      - airGapPortIds
  AirGapPortVo:
    type: object
    description: AirGapPortVo返回实体
    properties:
      id:
        type: string
        description: 逻辑端口ID
      name:
        type: string
        description: 逻辑端口名称
      ip:
        type: string
        description: 逻辑端口IP
      isActive:
        type: boolean
        description: 是否是激活状态
        enum:
          - 'true'
          - 'false'
      airGapId:
        type: string
        description: 关联的AIRGAP
  AirGapDetailVo:
    type: object
    description: AirGapDetailVo返回实体
    properties:
      id:
        type: string
        description: ID
      name:
        type: string
        description: 名称
      description:
        type: string
        description: 描述
      status:
        type: string
        description: 状态
        enum:
          - enable
          - disable
      isForceStop:
        type: boolean
        description: 是否强制中止复制
        enum:
          - 'true'
          - 'false'
      triggerCycle:
        type: string
        description: 触发周期
        enum:
          - day
          - week
      triggerWeekFreq:
        type: string
        description: 周触发频率
        example: '"mon,tue,wed,thu,fri,sat,sun"'
      startTime:
        type: string
        description: 开始时间HH:mm
        example: '09:00'
      endTime:
        type: string
        description: 结束时间HH:mm
        example: '18:00'
      airGapPorts:
        type: array
        items:
          $ref: '#/definitions/AirGapPortVo'
        description: 关联AirGapPort
  PageListResponse:
    type: object
    description: 分页返回对象
    properties:
      totalCount:
        type: integer
        format: int32
        description: 总条数
      records:
        items:
          $ref: '#/definitions/AirGapVo'
        description: AirGapVo返回实体列表
        type: array
  AirGapVo:
    type: object
    description: AirGapVo返回实体
    properties:
      id:
        type: string
        description: ID
      name:
        type: string
        description: 名称
      description:
        type: string
        description: 描述
      status:
        type: string
        description: 状态
        enum:
          - enable
          - disable
      isForceStop:
        type: boolean
        description: 是否强制中止复制
        enum:
          - 'true'
          - 'false'
      triggerCycle:
        type: string
        description: 触发周期
        enum:
          - day
          - week
      triggerWeekFreq:
        type: string
        description: 周触发频率
        example: ”mon,tue,wed,thu,fri,sat,sun”
      startTime:
        type: string
        description: 开始时间HH:mm
        example: '09:00'
      endTime:
        type: string
        description: 结束时间HH:mm
        example: '18:00'
  AirGapPortVoList:
    type: array
    items:
      $ref: '#/definitions/AirGapPortVo'
