swagger: '2.0'
info:
  version: v1
  title: ibmc接口
  contact: {}
  license: {}
host: localhost
basePath: /
tags:
  - name: alarm-and-event-api
    description: IBMC Controller
paths:
  /v1/ibmc/bmcusers:
    post:
      x-dr-role: 'N'
      x-product: OceanCyber
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - ibmc-alarm
      summary: 本地配置iBMC用户
      operationId: configureIBMCUserLocalUsingPost
      produces:
        - '*/*'
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
        - in: body
          name: iBMCUserRequest
          description: 配置iBMC用户请求体
          required: true
          schema:
            $ref: '#/definitions/IBMCUserRequest'
            originalRef: IBMCUserRequest
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization:
            - global
      deprecated: false
    get:
      x-dr-role: 'N'
      x-product: OceanCyber
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - ibmc-alarm
      summary: 获取已配置iBMC用户名
      operationId: iBMCUserNameUsingGet
      produces:
        - '*/*'
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization:
            - global
      deprecated: false  
  /v1/ibmc/bmcnewpasswd:
    post:
      x-dr-role: 'N'
      x-product: OceanCyber
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - ibmc-alarm
      summary: 同步修改iBMC用户
      operationId: configureIBMCUserSyncUsingPost
      produces:
        - '*/*'
      parameters:
        - name: X-Auth-Token
          in: header
          description: Access token
          required: true
          type: string
        - in: body
          name: iBMCUserRequest
          description: 配置iBMC用户请求体
          required: true
          schema:
            $ref: '#/definitions/IBMCUserRequest'
            originalRef: IBMCUserRequest
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization:
            - global
      deprecated: false


securityDefinitions:
  Authorization:
    type: apiKey
    name: TOKEN
    in: header
definitions:
  IBMCUserRequest:
    type: object
    required:
      - confirmPassword
      - newPassword
      - userName
      - userPassword
    properties:
      userName:
        type: string
        description: 用户名称。1、只能以字母、下划线、中文开头，由中文、数字、字母或者下划线组成的字符串。2、用户名长度：5-64
        pattern: ^[a-zA-Z_\u4e00-\u9fa5]{1}[\u4e00-\u9fa5\w-]*$
      userPassword:
        type: string
        description: >-
          密码。1、密码长度和复杂度，分别是由“查询安全策略”接口的passLenVal字段和passComplexVal字段决定。2、密码长度：8-64
      newPassword:
        type: string
        description: >-
          密码。1、密码长度和复杂度，分别是由“查询安全策略”接口的passLenVal字段和passComplexVal字段决定。2、密码长度：8-64
      confirmPassword:
        type: string
        description: >-
          密码。1、密码长度和复杂度，分别是由“查询安全策略”接口的passLenVal字段和passComplexVal字段决定。2、密码长度：8-64
    title: IBMCUserRequest
    description: iBMC配置用户请求体
responses:
  ErrorResponse:
    description: 统一错误响应
    examples:
      application/json:
        errorCode: '1677931527'
        errorMessage: xxx
        parameters: []
    schema:
      type: object