swagger: '2.0'
info:
  version: v1
  title: ApplicationTitle
  description: GroupDesc
schemes:
  - https
host: 'localhost.com'
basePath: /
tags:
  - name: report-data
paths:
  /v1/report-data/jobs:
    post:
      tags:
        - report-data
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000,OceanProtect E6000,OceanProtect DataBackup,OceanProtect for HCS
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      operationId: QueryProtectTask
      summary: 查询保护任务统计数据
      description: 查询保护任务统计数据
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - in: body
          name: QueryProtectTaskRequestBody
          description: 保护任务查询参数
          required: true
          schema:
            "$ref": "#/definitions/QueryProtectTaskRequestBody"
      responses:
        200:
          description: Demo Information
          schema:
            "$ref": "#/definitions/DataResponse"
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking.
                Format is request_uuid-timestamp-hostname.
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found

definitions:
  QueryProtectTaskRequestBody:
    type: object
    description: This is a demo
    properties:
      timeRange:
        type: string
        description: 统计时间范围，LAST_WEEK：最近一周，LAST_MONTH：最近一月，LAST_THREE_MONTH：最近三月。
        enum:
          - LAST_WEEK
          - LAST_MONTH
          - LAST_THREE_MONTH
      dataQueryTypeEnum:
        type: string
        description: 查询数据类型，CAPACITY：任务使用容量统计，RESOURCE：资源任务统计，SLA：sla关联任务统计
        enum:
          - CAPACITY
          - RESOURCE
          - SLA
     
  DataResponse:
    description: This is a demo
    required:
      - name
    properties:
      resourceTaskSummary:
        type: array
        description: 唯一标识ID
        items:
           $ref: '#/definitions/ResourceTaskSummary'
      slaTaskSummary:
        type: array
        description: 名称
        items:
           $ref: '#/definitions/SlaTaskSummary'
      taskCapacitySummary:
        type: object
        description: 描述
        $ref: '#/definitions/TaskCapacitySummary'
        
  ResourceTaskSummary:
    type: object
    description: This is a demo
    properties:
      count:
        type: integer
        format: int32
        description: 统计任务数
      status:
        type: string
        minLength: 1
        maxLength: 64
        description: 统计的任务状态类型
      resourceId:
        type: string
        minLength: 1
        maxLength: 64
        description: 资源id
      resourceName:
        type: string
        minLength: 1
        maxLength: 64
        description: 资源名称
      resourceType:
        type: string
        minLength: 1
        maxLength: 64
        description: 资源类型
          
  SlaTaskSummary:
    type: object
    description: This is a demo
    properties:
      count:
        type: integer
        format: int32
        minimum: 0
        description: 统计任务数
      status:
        type: string
        minLength: 1
        maxLength: 64
        description: 统计的任务状态类型
      slaId:
        type: string
        minLength: 1
        maxLength: 64
        description: sla ID
      slaName:
        type: string
        minLength: 1
        maxLength: 64
        description: sla名称
      protectedResourceCount:
        type: integer
        format: int32
        minimum: 0
        description: sla保护资源数。
        
  TaskCapacitySummary:
    type: object
    description: This is a demo
    properties:
      totalCapacity:
        type: integer
        format: int64
        minimum: 0
        description: 保护任务总使用容量。
      backupCapacity:
        type: integer
        format: int64
        minimum: 0
        description: 备份任务使用容量。
      archiveCapacity:
        type: integer
        format: int64
        minimum: 0
        description: 归档任务使用容量。
      duplicateCapacity:
        type: integer
        format: int64
        minimum: 0
        description: 复制任务使用容量。
