swagger: '2.0'
info:
  version: v1
  title: BackupCopyDetectAPI
  description: GroupDesc
schemes:
  - https
host: localhost
basePath: /
tags:
  - name: BackupCopyDetect
  - name: AbnormalFile
paths:
  /v1/anti/ransomware/detect/copy/backup/abnormal-file:
    get:
      x-dr-role: 'N'
      x-product: OceanCyber
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 8083
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - BackupCopyDetect
      operationId: GetAbnormalFileById
      summary: 根据备份副本id获取备份副本侦测异常文件信息
      description: Get abnormal fFile by id
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - name: pageNum
          in: query
          description: 页的编号，>=1
          required: true
          type: integer
          format: int64
          x-example: 0
        - name: pageSize
          in: query
          description: 每页数量，1~500
          required: true
          type: integer
          format: int64
        - name: backupCopyId
          in: query
          description: 根据备份副本id查询该副本异常文件
          required: true
          type: string
        - name: fileName
          in: query
          description: 支持按照备份副本名文件模糊查询
          required: false
          type: string
        - name: orderBy
          in: query
          description: 排序名称,支持按照文件大小进行排序,当前仅支持fileSize
          required: false
          type: string
        - name: orderType
          in: query
          description: 排序方式：asc|desc
          required: false
          type: string
        - name: snapshotId
          in: query
          required: false
          description: 快照id，用于分权分域
          type: string
      responses:
        '200':
          description: 备份副本异常文件列表
          schema:
            $ref: '#/definitions/Response'
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking. Format is request_uuid-timestamp-hostname.
        '400':
          description: Error response
          schema:
            $ref: '#/definitions/ErrorRsp'
          headers:
            X-request-id:
              type: string
              description: This field is the request ID number for task tracking. Format is request_uuid-timestamp-hostname.
  /v1/anti/ransomware/detect/copy/backup/protected-objs:
    get:
      tags:
        - BackupCopyDetect
      x-dr-role: 'N'
      x-product: OceanCyber
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      description: 根据快照ID获取保护对象列表
      operationId: QueryObjectsBySnapshotId
      parameters:
        - name: snapshotId
          in: query
          required: true
          description: 快照ID
          type: string
          minLength: 1
          maxLength: 1024
        - name: pageNum
          in: query
          required: false
          description: 页码
          type: integer
          format: int64
          default: 1
          minimum: 1
          maximum: 201
        - name: pageSize
          in: query
          required: false
          description: 每页数量
          type: integer
          format: int64
          default: 1
          minimum: 1
          maximum: 500
        - name: name
          in: query
          required: false
          description: 用于模糊查询的保护对象名
          type: string
          allowEmptyValue: true
          minLength: 1
          maxLength: 1024
        - name: orderBy
          in: query
          required: false
          description: 排序字段
          type: string
          enum:
            - backupCount
          allowEmptyValue: true
        - name: orderType
          in: query
          required: false
          description: 排序方式，asc增续，desc降序
          type: string
          enum:
            - asc
            - desc
          allowEmptyValue: true
        - name: statusList
          in: query
          required: false
          description: 待筛选的侦测状态集合
          type: array
          minItems: 1
          maxItems: 6
          items:
            enum:
              - -1
              - 0
              - 1
              - 2
              - 3
              - 4
            type: integer
            format: int32
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/QueryObjectsBySnapshotIdResponse'
  /v1/anti/ransomware/detect/copy/backup/obj-backups:
    get:
      tags:
        - BackupCopyDetect
      x-dr-role: 'N'
      x-product: OceanCyber
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      description: 根据保护对象名称获取副本列表
      operationId: QueryBackupsByProtectedObjName
      parameters:
        - name: protectedObjName
          in: query
          required: true
          type: string
          description: 保护对象名称
          minLength: 1
          maxLength: 1024
        - name: snapshotId
          in: query
          required: true
          description: 快照ID
          type: string
          minLength: 1
          maxLength: 1024
        - name: fileSystemId
          in: query
          required: true
          type: string
          description: 文件系统ID
          minLength: 1
          maxLength: 1024
        - name: pageNum
          in: query
          required: false
          type: integer
          format: int64
          description: 页码
          default: 1
          minimum: 1
          maximum: 201
        - name: pageSize
          in: query
          required: false
          type: integer
          format: int64
          description: 页大小
          minimum: 1
          maximum: 500
        - name: copyName
          in: query
          required: false
          type: string
          description: 副本名（副本ID），用于模糊匹配
          allowEmptyValue: true
          minLength: 1
          maxLength: 1024
        - name: orderBy
          in: query
          required: false
          description: 排序字段
          type: string
          enum:
            - copySize
            - backupTime
        - name: orderType
          in: query
          required: false
          description: 排序方式
          type: string
          enum:
            - asc
            - desc
        - name: copyTypeList
          in: query
          required: false
          description: 备份类型筛选，1:全备，2:差分增备，3:累积增备
          type: array
          minItems: 1
          maxItems: 3
          items:
            enum:
              - 1
              - 2
              - 3
            type: integer
            format: int32
        - name: statusList
          in: query
          required: false
          description: 侦测状态筛选
          type: array
          minItems: 1
          maxItems: 6
          items:
            enum:
              - -1
              - 0
              - 1
              - 2
              - 3
              - 4
            type: integer
            format: int32
        - name: backupJobId
          in: query
          required: false
          description: 备份任务ID，用于模糊匹配
          type: string
          minLength: 1
          maxLength: 1024
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/QueryBackupsByProtectedObjNameResponse'
  /v1/anti/ransomware/detect/copy/action/abnormal/download:
    get:
      tags:
        - AbnormalFile
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000,OceanProtect E6000,OceanProtect DataBackup
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      summary: 下载检测异常文件列表
      operationId: downloadAbnormalFile
      parameters:
        - name: copyId
          in: query
          required: true
          description: 副本ID
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
definitions:
  Response:
    description: 响应
    properties:
      records:
        type: array
        description: 备份副本异常文件信息
        items:
          $ref: '#/definitions/BackupCopyAbnormalFileInfo'
      totalCount:
        type: integer
        format: int64
        description: 总记录数
      errorCode:
        type: integer
        format: int64
        description: 错误编码
      errorMessage:
        description: 错误参数
        items:
          type: string
  BackupCopyAbnormalFileInfo:
    description: 备份副本异常文件信息
    properties:
      fileSystemId:
        type: string
        description: 备份副本所属文件系统id
      backupCopyId:
        type: string
        description: 备份副本id
      fileName:
        type: string
        description: 文件名
      fileSize:
        type: integer
        format: int64
        description: 文件大小
      filePath:
        type: string
        description: 文件路径
      latestModifyTime:
        type: string
        description: 最近修改时间，不带时区的"yyyy-MM-dd HH:mm:ss"字符串
    type: object
  ErrorRsp:
    description: 失败时返回的错误对象
    required:
      - error_code
      - error_msg
    properties:
      error_code:
        description: 错误码
        type: string
        minLength: 8
        maxLength: 36
      error_msg:
        description: 错误描述
        type: string
        minLength: 2
        maxLength: 512
  ProtectedObjInfo:
    type: object
    properties:
      protectedObjName:
        type: string
      clientName:
        type: string
      software:
        type: integer
        format: int32
      fileSystemId:
        type: string
      backupCount:
        type: integer
        format: int64
      abnormalBackupCount:
        type: integer
        format: int64
      status:
        type: integer
        format: int32
        description: 2未感染，3已感染
      latestInfectionStartTime:
        type: string
        description: 时间字符串（不带时区信息）yyyy-MM-dd HH:mm:ss
      latestInfectionEndTime:
        type: string
        description: 时间字符串（不带时区信息）yyyy-MM-dd HH:mm:ss
  QueryObjectsBySnapshotIdResponse:
    type: object
    properties:
      totalCount:
        type: integer
        format: int64
      records:
        type: array
        items:
          $ref: '#/definitions/ProtectedObjInfo'
  BackupCopyInfo:
    type: object
    properties:
      id:
        type: string
        description: 副本ID（名称）
      copyType:
        type: integer
        format: int32
        description: softwareType << 8 | objType
      backupType:
        type: integer
        format: int32
        description: '副本类型: 全备=1，增备=2'
      copyPath:
        type: string
      copySize:
        type: integer
        format: int64
      backupTime:
        type: string
        description: 时间字符串（不带时区信息）yyyy-MM-dd HH:mm:ss
      fileCount:
        type: integer
        format: int64
      abnormalFileCount:
        type: integer
        format: int64
      status:
        type: integer
        format: int32
        description: 2：未感染，3：已感染
      originalSize:
        type: integer
        format: int64
      abnormalSize:
        type: integer
        format: int64
      varyType:
        type: integer
        format: int32
        description: 副本变化标记，历史副本:1，变化副本:2，新增副本:3
        enum:
          - 1
          - 2
          - 3
  QueryBackupsByProtectedObjNameResponse:
    type: object
    properties:
      totalCount:
        type: integer
        format: int64
      records:
        type: array
        items:
          $ref: '#/definitions/BackupCopyInfo'
  ResourceInfo:
    type: object
    description: 文件系统资源信息
    properties:
      resourceId:
        type: string
        minLength: 1
        maxLength: 1024
      deviceId:
        type: string
        minLength: 1
        maxLength: 1024
      fileSystemId:
        type: string
        minLength: 1
        maxLength: 1024
    required:
      - resourceId
      - deviceId
      - fileSystemId
  QueryProtectObjsRequest:
    type: object
    required:
      - snapshotId
    properties:
      snapshotId:
        type: string
        description: 快照ID
        minLength: 1
        maxLength: 1024
      pageNum:
        type: integer
        format: int64
        description: 页码
        minimum: 1
        maximum: 201
      pageSize:
        type: integer
        format: int64
        description: 每页数量
        minimum: 1
        maximum: 500
      name:
        type: string
        description: 用于模糊查询的保护对象名
        minLength: 1
        maxLength: 1024
      orderBy:
        type: string
        description: 排序字段
        enum:
          - backupCount
      orderType:
        type: string
        description: 排序方式，asc增续，desc降序
        enum:
          - asc
          - desc
      statusList:
        type: array
        description: 待筛选的侦测状态集合
        minItems: 1
        maxItems: 6
        items:
          enum:
            - -1
            - 0
            - 1
            - 2
            - 3
            - 4
          type: integer
          format: int32
    description: 查询保护对象列表请求
  DownloadAbnormalRequest:
    type: object
    description: 下载异常文件列表请求
    required:
      - copyId
    properties:
      copyId:
        type: string
        description: 副本ID
