swagger: '2.0'
info:
  version: v1
  title: ApplicationTitle
  description: GroupDesc
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: Honeypot
paths:
  /v1/anti/ransomware/honeypot/enable:
    post:
      x-dr-role: 'N'
      x-product: hyper_detect
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Honeypot
      operationId: EnableHoneypot
      summary: 开启诱饵文件功能
      description: 开启诱饵文件功能
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - name: honeypotRequests
          in: body
          required: true
          description: 租户名文件系统名列表
          schema:
            type: array
            minItems: 1
            maxItems: 10
            items:
              $ref: '#/definitions/HoneypotRequestWithPeiod'
      responses:
        '200':
          description: 操作完成
          schema:
            $ref: '#/definitions/HoneypotOpResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-order: 0
  /v1/anti/ransomware/honeypot/disable:
    post:
      x-dr-role: 'N'
      x-product: hyper_detect
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Honeypot
      operationId: CloseHoneypot
      summary: 关闭诱饵文件功能
      description: 关闭诱饵文件功能
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - name: honeypotRequests
          in: body
          required: true
          description: 租户名文件系统名列表
          schema:
            type: array
            minItems: 1
            maxItems: 10
            items:
              $ref: '#/definitions/HoneypotRequest'
      responses:
        '200':
          description: 操作完成
          schema:
            $ref: '#/definitions/HoneypotOpResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-order: 1
  /v1/anti/ransomware/honeypot/modify:
    post:
      x-dr-role: 'N'
      x-product: hyper_detect
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Honeypot
      operationId: ModifyHoneypot
      summary: 修改诱饵文件更新周期
      description: 修改诱饵文件更新周期
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - name: honeypotRequests
          in: body
          required: true
          description: 租户名文件系统名列表
          schema:
            type: array
            minItems: 1
            maxItems: 10
            items:
              $ref: '#/definitions/HoneypotRequestWithPeiod'
      responses:
        '200':
          description: 操作完成
          schema:
            $ref: '#/definitions/HoneypotOpResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-order: 2
  /v1/anti/ransomware/honeypot/getinfo:
    get:
      x-dr-role: 'N'
      x-product: hyper_detect
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Honeypot
      operationId: ListHoneypotInfoById
      summary: 查询诱饵文件列表
      description: 获取诱饵文件信息，包括是否开启及诱饵文件列表
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - name: vstoreName
          in: query
          required: true
          description: 租户名
          type: string
          minLength: 1
          maxLength: 256
        - name: fsName
          in: query
          required: true
          description: 文件系统名
          type: string
          minLength: 1
          maxLength: 256
      responses:
        '200':
          description: 成功获取诱饵文件列表
          schema:
            $ref: '#/definitions/HoneypotInfoResponse'
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '410':
          description: Unauthorized
      x-order: 3
  /v1/anti/ransomware/honeypot/getnum:
    get:
      x-dr-role: 'N'
      x-product: hyper_detect
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Honeypot
      operationId: ListHoneypotNum
      summary: 查询已经开启诱饵文件功能的文件系统数量
      description: 查询已经开启诱饵文件功能的文件系统数量
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      responses:
        '200':
          description: 成功获取诱饵文件列表
          schema:
            $ref: '#/definitions/HoneypotNumResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      x-order: 4
  /v1/anti/ransomware/honeypot/getstatus:
    get:
      x-dr-role: 'N'
      x-product: hyper_detect
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Honeypot
      operationId: ListHoneypotStatusById
      summary: 查询诱饵文件列表
      description: 获取诱饵文件功能开启状态
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - name: fsIds
          in: query
          required: true
          description: 文件系统ID
          type: array
          items:
            type: string
      responses:
        '200':
          description: 成功获取诱饵文件列表
          schema:
            $ref: '#/definitions/HoneypotStatusResponse'
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '410':
          description: Unauthorized
      x-order: 5
  /v1/anti/ransomware/honeypot/detail:
    get:
      x-dr-role: 'N'
      x-product: HyperDetect
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 25081
      x-auth-required: 'Y'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'N'
      x-public-api: 'Y'
      x-sysadmin-role: 'Y'
      tags:
        - Honeypot
      summary: 查询诱饵文件详情
      description: 查询诱饵文件详情
      operationId: ListHoneypotDetail
      produces:
        - application/json
      parameters:
        - name: pageNum
          in: query
          required: true
          description: 页码
          type: integer
          format: int64
        - name: pageSize
          in: query
          required: true
          description: 每页大小
          type: integer
          format: int64
        - name: honeypotModes
          in: query
          required: false
          description: 诱饵文件状态
          type: array
          items:
            type: string
        - name: fsName
          in: query
          required: false
          description: 文件系统名模糊匹配
          type: string
        - name: vstoreName
          in: query
          required: false
          description: 租户名模糊匹配
          type: string
        - name: fsId
          in: query
          required: false
          description: 文件系统ID模糊匹配
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/HoneypotDetailResponse'
definitions:
  HoneypotRequestWithPeiod:
    type: object
    required:
      - vstoreName
      - fsName
    properties:
      vstoreName:
        type: string
        description: 租户名
        minLength: 1
        maxLength: 256
      fsName:
        type: string
        description: 文件系统名
        minLength: 1
        maxLength: 256
      period:
        type: integer
        format: int32
        description: 诱饵文件更新周期
        minimum: 0
        maximum: 30
  HoneypotRequest:
    type: object
    required:
      - vstoreName
      - fsName
    properties:
      vstoreName:
        type: string
        description: 租户名
        minLength: 1
        maxLength: 256
      fsName:
        type: string
        description: 文件系统名
        minLength: 1
        maxLength: 256
  HoneypotOpRet:
    type: object
    required:
      - honeyOpErrInfo
    properties:
      honeyOpErrInfo:
        type: string
        description: 诱饵文件操作失败信息
  HoneypotInfo:
    type: object
    required:
      - honeypotFileList
    properties:
      honeypotFileList:
        type: string
        description: 诱饵文件列表
  HoneypotStatus:
    type: object
    required:
      - honeypotMode
      - period
    properties:
      honeypotMode:
        type: integer
        format: int32
        description: 诱饵文件开启状态
      period:
        type: integer
        format: int32
        description: 诱饵文件更新周期
  HoneypotInfoResponse:
    type: object
    properties:
      errorCode:
        type: integer
        format: int64
        description: 错误编码
      errorMessage:
        type: string
        description: 错误描述
      detailParams:
        type: array
        items:
          type: string
        description: 错误参数
      records:
        description: 诱饵文件信息
        $ref: '#/definitions/HoneypotInfo'
      totalCount:
        type: integer
        format: int64
        description: 翻页
  HoneypotNumResponse:
    type: object
    properties:
      errorCode:
        type: integer
        format: int64
        description: 错误编码
      errorMessage:
        type: string
        description: 错误描述
      detailParams:
        type: array
        items:
          type: string
        description: 错误参数
      records:
        description: 数据
        $ref: '#/definitions/HoneypotNum'
      totalCount:
        type: integer
        format: int64
        description: 翻页
  HoneypotStatusResponse:
    type: object
    properties:
      errorCode:
        type: integer
        format: int64
        description: 错误编码
      errorMessage:
        type: string
        description: 错误描述
      detailParams:
        type: array
        items:
          type: string
        description: 错误参数
      records:
        items:
          $ref: '#/definitions/HoneypotStatus'
        description: 数据
        type: array
      totalCount:
        type: integer
        format: int64
        description: 翻页
  HoneypotOpResponse:
    type: object
    properties:
      errorCode:
        type: integer
        format: int64
        description: 错误编码
      errorMessage:
        type: string
        description: 错误描述
      detailParams:
        type: array
        items:
          type: string
        description: 错误参数
      records:
        items:
          $ref: '#/definitions/HoneypotOpRet'
        description: 数据
      totalCount:
        type: integer
        format: int64
        description: 翻页
  HoneypotNum:
    type: object
    properties:
      num:
        type: integer
        format: int64
        description: 已开启诱饵文件功能的文件系统数量
  HoneypotDetail:
    type: object
    required:
      - vstoreId
      - vstoreName
      - resourceId
      - resourceName
    properties:
      vstoreId:
        type: string
        description: 租户ID
      vstoreName:
        type: string
        description: 租户名
      resourceId:
        type: string
        description: 文件系统ID
      resourceName:
        type: string
        description: 资源名称
      mode:
        type: string
        description: 诱饵文件状态
      period:
        type: integer
        format: int32
        description: 周期
  HoneypotDetailResponse:
    type: object
    properties:
      errorCode:
        type: integer
        format: int64
        description: 错误码
      errorMessage:
        type: string
        description: 错误信息
      detailParams:
        type: array
        items:
          type: string
        description: 错误参数
      records:
        type: array
        items:
          $ref: '#/definitions/HoneypotDetail'
        description: 数据
      totalCount:
        type: integer
        format: int64
        description: 总数
