---
swagger: "2.0"
info:
  version: "v1"
  title: "License管理接口"
  contact: {}
  license: {}
host: "localhost"
basePath: "/"
tags:
- name: "${license-api}"
  description: "License Controller"
paths:
  /v1/internal/license/function:
    get:
      tags:
      - "${license-api}"
      summary: "校验License"
      operationId: "functionLicenseUsingGET"
      produces:
      - "*/*"
      parameters:
      - name: "function"
        in: "query"
        description: "需要校验的功能名称"
        required: true
        type: "string"
        allowEmptyValue: false
      - name: "resourceType"
        in: "query"
        description: "需要校验的资源类型"
        required: true
        type: "string"
        allowEmptyValue: false
      responses:
        "200":
          description: "OK"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/license:
    get:
      tags:
      - "${license-api}"
      summary: "查询License信息"
      operationId: "queryLicenseUsingGET"
      produces:
      - "*/*"
      parameters:
      - name: "X-Auth-Token"
        in: "header"
        description: "Access token"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/LicenseInfoVo"
              originalRef: "LicenseInfoVo"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/license/action/active:
    post:
      tags:
      - "${license-api}"
      summary: "激活License"
      operationId: "activeLicenseUsingPOST"
      consumes:
      - "multipart/form-data"
      produces:
      - "*/*"
      parameters:
      - name: "X-Auth-Token"
        in: "header"
        description: "Access token"
        required: true
        type: "string"
      - name: "file"
        in: "formData"
        description: "数据存储管理软件容量许可激活文件，dat格式，文件大小不超过2MB"
        required: true
        type: "file"
      responses:
        "200":
          description: "OK"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/license/action/export:
    get:
      tags:
      - "${license-api}"
      summary: "导出License"
      operationId: "exportLicenseUsingGET"
      produces:
      - "*/*"
      parameters:
      - name: "X-Auth-Token"
        in: "header"
        description: "Access token"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
  /v1/license/action/import:
    post:
      tags:
      - "${license-api}"
      summary: "导入License文件"
      operationId: "importLicenseUsingPOST"
      consumes:
      - "multipart/form-data"
      produces:
      - "*/*"
      parameters:
      - name: "X-Auth-Token"
        in: "header"
        description: "Access token"
        required: true
        type: "string"
      - name: "basic_license_file"
        in: "formData"
        description: "数据保护一体机存储软件许可文件，dat格式，文件大小不超过2MB"
        required: false
        type: "file"
      - name: "file"
        in: "formData"
        description: "数据存储管理软件容量许可文件，dat格式，文件大小不超过2MB"
        required: false
        type: "file"
      responses:
        "200":
          description: "OK"
        "201":
          description: "Created"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
      security:
      - Authorization:
        - "global"
      deprecated: false
securityDefinitions:
  Authorization:
    type: "apiKey"
    name: "TOKEN"
    in: "header"
definitions:
  LicenseInfoVo:
    type: "object"
    properties:
      expireTime:
        type: "string"
        description: "过期时间"
      importTime:
        type: "string"
        description: "导入时间"
      name:
        type: "string"
        description: "授权名称"
      status:
        type: "integer"
        format: "int32"
        description: "状态 0:未激活 1:已激活 2:已过期 3:部分激活"
      totalCapacity:
        type: "integer"
        format: "int64"
        description: "总容量(授权容量)，单位Byte"
      unactiveCapactiy:
        type: "integer"
        format: "int64"
        description: "未激活总容量，单位Byte"
      usedCapacity:
        type: "integer"
        format: "int64"
        description: "已使用容量，单位Byte"
    title: "LicenseInfoVo"
