---
version: 2.0

#构建环境
envs:
  - condition: ENV_VM == "VPC"
    label: OceanProtect_X8000_1.3.0_euler_arm_VPC
  - condition: ENV_VM != "VPC"
    label: X8000_1.3.0_euler_arm

#是否固定构建根目录
buildspace:
  fixed: true

#构建参数，构建命令可通过环境变量使用
params:
  - name: PRODUCT
    value: ${PRODUCT}
  - name: DME_BRANCH
    value: ${branch}
  - name: INF_BRANCH
    value: ${branch}

#构建步骤
steps:
  CONFIG_ENV:
    - sh:
        command: |
          systemctl restart docker
          chmod -R 777 /var/run/docker*
          chmod 777 /run/docker*
          ls -l /run/docker*
          chmod +w /etc/sudoers
          test `cat /etc/sudoers |grep cp |wc -l` -eq 0 && echo -e "Cmnd_Alias    CP = /usr/bin/cp\nALL    ALL=NOPASSWD: CP" >> /etc/sudoers
          test `cat /etc/sudoers |grep "/usr/bin/ln" |wc -l` -eq 0 && echo -e "Cmnd_Alias    LN = /usr/bin/ln\nALL    ALL=NOPASSWD: LN" >> /etc/sudoers
          chmod -w /etc/sudoers
          cat /etc/sudoers
        sudo: true
  PRE_BUILD: # 构建准备
    - manifest_checkout:
        manifest_file: ${dependency_path}
        groups: ${manifest_groups}
        strict: "false"

  BUILD:
    - when:
        condition: tag_image == "asan"
        steps:
          - build_execute:
              command: bash -c "
                cd ${WORKSPACE}/DataMoveEngine/CI/script/
                && sh Package.sh ${PRODUCT} ${DME_BRANCH} ${Service_Name}
                && cd ${WORKSPACE}/DataMoveEngine/CI/script
                && sh Build_ASAN.sh ${DME_BRANCH} ${INF_BRANCH}"
              accelerate:
                isAccelerate: false
                isCache: true
              check:
                auto: true
                mode: sync
    - when:
        condition: tag_image != "asan"
        steps:
          - build_execute:
              command: bash -c "
                cd ${WORKSPACE}/DataMoveEngine/CI/script/
                && sh Package.sh ${PRODUCT} ${DME_BRANCH} ${Service_Name}
                && cd ${WORKSPACE}/DataMoveEngine/CI/script
                && sh build_image.sh ${DME_BRANCH} ${INF_BRANCH} ${Service_Name}"
              accelerate:
                isAccelerate: false
                isCache: true
              check:
                auto: true
                mode: sync