---
version: 2.0
# 构建参数
params:
  - name: IS_SNAPSHOT
    value: ${IS_SNAPSHOT}
  - name: IS_ComponentVersion
    value: ${IS_ComponentVersion}
  - name: PBI_NAME
    value: '${PBI_NAME}'
  - name: PBI_NAME_CY
    value: '${PBI_NAME_CY}'
  - name: CY_VERSION
    value: ${CY_VERSION}
  - name: MS_IMAGE_TAG_CY
    value: ${MS_IMAGE_TAG_CY}
  - name: PRODUCT
    value: ${PRODUCT}
  - name: CODE_BRANCH
    value: ${branch}
  - name: PM_BRANCH
    value: ${branch}
  - name: DME_BRANCH
    value: ${branch}
  - name: DEE_BRANCH
    value: ${branch}
  - name: INF_BRANCH
    value: ${branch}
  - name: DMA_BRANCH
    value: ${branch}
  - name: AGENT_BRANCH
    value: ${branch}
  - name: NAS_Plugins_BRANCH
    value: ${branch}
  - name: tag_image
    value: debug
  - name: BUILD_TYPE
    value: debug
  - name: Compile_image
    value: Y
  - name: harbor_project
    value: a8000
  - name: MS_IMAGE_TAG
    value: ${MS_IMAGE_TAG}
  - name: INTERNAL_VERSION
    value: ${INTERNAL_VERSION}
  - name: dependency_path
    value: .cloudbuild/euler_arm/dependency.xml
#构建环境
envs:
  - condition: ENV_VM == "VPC"
    label: OceanProtect_X8000_1.3.0_euler_arm_VPC
  - condition: ENV_VM != "VPC"
    label: X8000_1.3.0_euler_arm
buildflow:
  strategy: lazy
  flow_metadata:
    from: 100P_Package_DATA
  attach_workspace:
    path: output
    resource: efs
  jobs:
    - job: 100P_Package_DATA
      depends_on:
          - PM_GUI
          - PM_System_Base_Common_Service
          - PM_Data_Protection_Service
          - PM_Database_Version_Migration
          - PM_API_Gateway
          - DME_VMware
          - DME_Archive
          - DME_JobManager
          - DME_Data_Move_Controller
          - DME_Replication
          - DME_UnifiedBackupController
          - DEE_Indexer
          - DEE_Base_Parser
          - DEE_DB_Anonymization
          - DEE_Global_Search
          - DEE_Anti_Ransomware
          - ProtectAgent
          - infrastructure
      params:
      - name: manifest_groups
        value: DPAProduct,ProtectManager,DataMoveEngine,Infrastructure_OM,DataEnableEngine,ProtectAgent,CPP
      - name: BUILD_PKG_TYPE
        value: DataProtect
      build_ref: .cloudbuild/euler_arm/package/build.yml
    - job: 100P_Package_CY
      depends_on:
          - PM_GUI
          - PM_System_Base_Common_Service
          - PM_Data_Protection_Service
          - PM_Database_Version_Migration
          - PM_API_Gateway
          - DME_VMware
          - DME_Archive
          - DME_JobManager
          - DME_Data_Move_Controller
          - DME_Replication
          - DME_UnifiedBackupController
          - DEE_Indexer
          - DEE_Base_Parser
          - DEE_DB_Anonymization
          - DEE_Global_Search
          - DEE_Anti_Ransomware
          - ProtectAgent
          - infrastructure
      params:
      - name: manifest_groups
        value: DPAProduct,ProtectManager,DataMoveEngine,Infrastructure_OM,DataEnableEngine,ProtectAgent,CPP
      - name: BUILD_PKG_TYPE
        value: OceanCyber
      build_ref: .cloudbuild/euler_arm/package/build.yml

# 构建PM服务
    - job: PM_API_Gateway
      params:
      - name: manifest_groups
        value: ProtectManager,PM_OpenSource
      - name: Service_Name
        value: PM_API_Gateway
      build_ref: .cloudbuild/euler_arm/PM_CI/package/build.yml

    - job: PM_GUI
      params:
      - name: manifest_groups
        value: ProtectManager,PM_OpenSource
      - name: Service_Name
        value: PM_GUI
      build_ref: .cloudbuild/euler_arm/PM_CI/package/build.yml

    - job: PM_System_Base_Common_Service
      params:
      - name: manifest_groups
        value: ProtectManager,PM_OpenSource
      - name: Service_Name
        value: PM_System_Base_Common_Service
      build_ref: .cloudbuild/euler_arm/PM_CI/package/build.yml

    - job: PM_Data_Protection_Service
      params:
      - name: manifest_groups
        value: ProtectManager,PM_OpenSource
      - name: Service_Name
        value: PM_Data_Protection_Service
      build_ref: .cloudbuild/euler_arm/PM_CI/package/build.yml

    - job: PM_Database_Version_Migration
      params:
      - name: manifest_groups
        value: ProtectManager,PM_OpenSource
      - name: Service_Name
        value: PM_Database_Version_Migration
      build_ref: .cloudbuild/euler_arm/PM_CI/package/build.yml

# 构建DME服务
    - job: DME_VMware
      depends_on:
          - DME_Framework
      params:
      - name: manifest_groups
        value: DataMoveEngine,CPP,DME_OpenSource,DME_OpenSource
      - name: Service_Name
        value: DME_VMware
      build_ref: .cloudbuild/euler_arm/DME_CI/package/build.yml
    - job: DME_Archive
      depends_on:
          - DME_Framework
      params:
      - name: manifest_groups
        value: DataMoveEngine,CPP,DME_OpenSource,DME_OpenSource
      - name: Service_Name
        value: DME_Archive
      build_ref: .cloudbuild/euler_arm/DME_CI/package/build.yml
    - job: DME_JobManager
      depends_on:
          - DME_Framework
      params:
      - name: manifest_groups
        value: DataMoveEngine,CPP,DME_OpenSource,DME_OpenSource
      - name: Service_Name
        value: DME_JobManager
      build_ref: .cloudbuild/euler_arm/DME_CI/package/build.yml
    - job: DME_Data_Move_Controller
      depends_on:
          - DME_Framework
      params:
      - name: manifest_groups
        value: DataMoveEngine,CPP,DME_OpenSource
      - name: Service_Name
        value: DME_Data_Move_Controller
      build_ref: .cloudbuild/euler_arm/DME_CI/package/build.yml
    - job: DME_Replication
      depends_on:
          - DME_Framework
      params:
      - name: manifest_groups
        value: DataMoveEngine,CPP,DME_OpenSource
      - name: Service_Name
        value: DME_Replication
      build_ref: .cloudbuild/euler_arm/DME_CI/package/build.yml
    - job: DME_UnifiedBackupController
      depends_on:
          - DME_Framework
      params:
      - name: manifest_groups
        value: DataMoveEngine,CPP,DME_OpenSource
      - name: Service_Name
        value: DME_UnifiedBackupController
      build_ref: .cloudbuild/euler_arm/DME_CI/package/build.yml
    - job: DME_Framework
      depends_on:
          - om
      params:
      - name: manifest_groups
        value: DataMoveEngine,CPP,DME_OpenSource
      - name: Service_Name
        value: DME_Framework
      build_ref: .cloudbuild/euler_arm/DME_CI/package/build.yml

# 构建DEE服务
    - job: DEE_Common
      depends_on:
          - om
      params:
      - name: manifest_groups
        value: DataEnableEngine,DEE_OpenSource
      - name: Service_Name
        value: DEE_Common
      build_ref: .cloudbuild/euler_arm/DEE_CI/package/build.yml
    - job: DEE_Indexer
      depends_on:
          - DEE_Common
      params:
      - name: manifest_groups
        value: DataEnableEngine,DEE_OpenSource
      - name: Service_Name
        value: DEE_Indexer
      build_ref: .cloudbuild/euler_arm/DEE_CI/package/build.yml
    - job: DEE_Base_Parser
      depends_on:
          - DEE_Common
      params:
      - name: manifest_groups
        value: DataEnableEngine,DEE_OpenSource
      - name: Service_Name
        value: DEE_Base_Parser
      build_ref: .cloudbuild/euler_arm/DEE_CI/package/build.yml
    - job: DEE_Global_Search
      depends_on:
          - DEE_Common
      params:
      - name: manifest_groups
        value: DataEnableEngine,DEE_OpenSource
      - name: Service_Name
        value: DEE_Global_Search
      build_ref: .cloudbuild/euler_arm/DEE_CI/package/build.yml
    - job: DEE_DB_Anonymization
      depends_on:
          - DEE_Common
      params:
      - name: manifest_groups
        value: DataEnableEngine,DEE_OpenSource
      - name: Service_Name
        value: DEE_DB_Anonymization
      build_ref: .cloudbuild/euler_arm/DEE_CI/package/build.yml
    - job: DEE_Anti_Ransomware
      depends_on:
        - DEE_Common
      params:
      - name: manifest_groups
        value: DataEnableEngine,DEE_OpenSource
      - name: Service_Name
        value: DEE_Anti_Ransomware
      build_ref: .cloudbuild/euler_arm/DEE_CI/package/build.yml

# 构建INF基础服务
    - job: infrastructure
      params:
      - name: manifest_groups
        value: Infrastructure_OM,DPAProduct,INF_OpenSource
      - name: Service_Name
        value: infrastructure
      build_ref: .cloudbuild/euler_arm/INF_CI/package/infrastructure/build.yml
    - job: om
      params:
      - name: manifest_groups
        value: Infrastructure_OM,DPAProduct,INF_OpenSource
      - name: Service_Name
        value: om
      build_ref: .cloudbuild/euler_arm/INF_CI/package/om/build.yml
# 构建Agent插件
    - job: ProtectAgent
      params:
      - name: manifest_groups
        value: ProtectAgent
      - name: Service_Name
        value: ProtectAgent
      build_ref: .cloudbuild/euler_arm/Plugins/package/build.yml