apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    emei_stor: 'True'
    k8s-app: emeistor-gui
  name: {{ include "gui.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: emeistor-gui
  template:
    metadata:
      annotations:
        co.elastic.logs/processors.decode_json_fields.fields.1: message
        co.elastic.logs/processors.decode_json_fields.overwrite_keys: 'true'
        co.elastic.logs/processors.decode_json_fields.target: ''
      labels:
        emei_stor: 'True'
        k8s-app: emeistor-gui
    spec:
      containers:
      - env:
        - name: SERVICE_MODE
          value: {{ .Values.serviceMode }}
        - name: LOGLEVEL
          valueFrom:
            configMapKeyRef:
              key: LOGLEVEL
              name: service-env-config
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: IS_TESTING
          value: {{ .Values.isTesting }}
        image: {{ template "gui.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: emeistor-gui
        ports:
        - containerPort: 80
        resources: {{- toYaml .Values.resources | nindent 12 }}
