apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: emeistor-gui
spec:
  gateways:
  - emeistor-gateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /console
    route:
    - destination:
        host: emeistor-gui-server
        port:
          number: 80