swagger: '2.0'
info:
  version: v1
  title: kerberos管理接口
  contact: {}
  license: {}
host: localhost
basePath: /
tags:
  - name: kerberos-internal-controller
    description: Kerberos Internal Controller
paths:
  /v1/internal/kerberos/{kerberos_id}:
    get:
      x-dr-role: 'N'
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 30081
      x-auth-required: 'N'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'N'
      x-sysadmin-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      tags:
        - kerberos-internal-controller
      summary: getKerberosById
      operationId: getKerberosByIdUsingGET
      produces:
        - '*/*'
      parameters:
        - name: kerberos_id
          in: path
          description: kerberos_id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/KerberosBo'
            originalRef: KerberosBo
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization:
            - global
      deprecated: false
securityDefinitions:
  Authorization:
    type: apiKey
    name: TOKEN
    in: header
definitions:
  BasePage«KerberosInfo»:
    type: object
    properties:
      items:
        type: array
        description: 详情
        items:
          $ref: '#/definitions/KerberosInfo'
          originalRef: KerberosInfo
      page_no:
        type: integer
        format: int64
        description: 页码
      page_size:
        type: integer
        format: int64
        description: 每页总数
      pages:
        type: integer
        format: int64
        description: 总页数
      total:
        type: integer
        format: int64
        description: 总数
    title: BasePage«KerberosInfo»
  KerberosBo:
    type: object
    properties:
      createModel:
        type: string
      createTime:
        type: string
        format: date-time
      kerberosId:
        type: string
      keytabPath:
        type: string
      krb5Path:
        type: string
      name:
        type: string
      password:
        type: string
      principalName:
        type: string
      updateTime:
        type: string
        format: date-time
      userId:
        type: string
    title: KerberosBo
  KerberosIDResp:
    type: object
    properties:
      kerberos_id:
        type: string
        description: Kerberos ID
    title: KerberosIDResp
  KerberosInfo:
    type: object
    properties:
      createModel:
        type: string
        description: 创建模式
      createTime:
        type: string
        format: date-time
        description: 创建时间
      kerberosId:
        type: string
        description: Kerberos ID
      keytabPath:
        type: string
        description: keytab文件路径
      krb5Path:
        type: string
        description: krb5文件路径
      name:
        type: string
        description: 名称
      principalName:
        type: string
        description: 主体名
      updateTime:
        type: string
        format: date-time
        description: 更新时间
      userId:
        type: string
        description: 用户ID
    title: KerberosInfo
