swagger: '2.0'
info:
  version: v1
  title: 证书组件管理接口
  contact: {}
  license: {}
host: localhost
basePath: /
tags:
  - name: component-internal-controller
    description: Component Internal Controller
paths:
  /v1/internal/certs/components/genCert:
    post:
      x-dr-role: 'N'
      x-product: OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      x-dm-role: 'N'
      x-impact-subsystem: 影响
      x-access-port: 30081
      x-auth-required: 'N'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-public-api: 'N'
      x-sysadmin-role: 'N'
      tags:
        - component-internal-controller
      summary: agent证书签发
      operationId: genCert4AgentUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: certSignBo
          description: agent证书签发请求体
          required: false
          schema:
            $ref: '#/definitions/CertSignBo'
            originalRef: CertSignBo
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/ClientCertGenResult'
            originalRef: ClientCertGenResult
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      security:
        - Authorization:
            - global
      deprecated: false
securityDefinitions:
  Authorization:
    type: apiKey
    name: TOKEN
    in: header
definitions:
  CertSignBo:
    type: object
    properties:
      password:
        type: string
        description: 私钥密码
    title: CertSignBo
  CertUpdateErrorCause:
    type: object
    properties:
      arguments:
        type: array
        description: 参数
        items:
          type: string
      lang:
        type: string
        description: 语言
      template:
        type: string
        description: 模板
    title: CertUpdateErrorCause
  CertificateDetail:
    type: object
    properties:
      certType:
        type: integer
        format: int32
        description: 证书类型。【取值范围】0:未知类型, 1:服务证书, 2:CA证书, 3:自签发证书
      effectiveTime:
        type: integer
        format: int64
        description: 证书生效时间
      expirationTime:
        type: integer
        format: int64
        description: 证书过期时间
      fingerprint:
        type: string
        description: 证书指纹
      issuer:
        type: string
        description: 证书颁发机构
      keyAlgorithm:
        type: string
        description: 私钥算法
      keyLength:
        type: integer
        format: int32
        description: 私钥长度
      serialNumber:
        type: integer
        description: 序列号
      signatureAlg:
        type: string
        description: 指纹加密算法
      sortNum:
        type: integer
        format: int32
        description: 证书链顺序
      subject:
        type: string
        description: 证书使用机构
    title: CertificateDetail
  CertificateEntity:
    type: object
    properties:
      certType:
        type: integer
        format: int32
        description: 证书类型。【取值范围】0:未知类型, 1:服务证书, 2:CA证书, 3:自签发证书
      certificateId:
        type: string
        description: 证书ID
      chainTail:
        type: boolean
        description: 是否链尾
      componentId:
        type: string
        description: 组件ID
      effectiveTime:
        type: integer
        format: int64
        description: 证书生效时间
      expirationTime:
        type: integer
        format: int64
        description: 证书过期时间
      fingerprint:
        type: string
        description: 证书指纹
      issuer:
        type: string
        description: 证书颁发机构
      keyAlgorithm:
        type: string
        description: 私钥算法
      keyLength:
        type: integer
        format: int32
        description: 私钥长度
      serialNumber:
        type: integer
        description: 序列号
      signatureAlg:
        type: string
        description: 指纹加密算法
      sortNum:
        type: integer
        format: int32
        description: 证书链顺序
      subject:
        type: string
        description: 证书使用机构
      validity:
        type: boolean
        description: 证书有效性
    title: CertificateEntity
  ClientCertGenResult:
    type: object
    properties:
      status:
        type: integer
        format: int32
      uuid:
        type: string
    title: ClientCertGenResult
