swagger: '2.0'
info:
  version: v1
  title: ApplicationTitle
  description: GroupDesc
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: sla-internal-api
paths:
  /v1/internal/slas/{slaId}:
    get:
      x-product: CyberEngine,OceanProtect X
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 30081
      x-auth-required: 'N'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'N'
      x-sysadmin-role: 'Y'
      tags:
        - sla-internal-api
      operationId: querySLAUsingGET
      consumes:
        - application/json
      summary: 查询SLA
      description: 查询SLA
      x-is-registered: 'N'
      x-support-sdk: 'N'
      produces:
        - application/json
      parameters:
        - name: slaId
          in: path
          required: true
          type: string
          description: SLA的id
      responses:
        '200':
          description: OK
          schema:
            $ref: 'api-sla.yaml#/definitions/SlaDto'
        '400':
          description: Bad Request
          schema:
            type: string
        '404':
          description: Not Found
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
        '502':
          description: Bad Gateway
          schema:
            type: string
  /v1/internal/slas/policies/{policyId}/detail:
    get:
      x-product: CyberEngine,OceanProtect X
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 30081
      x-auth-required: 'N'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'N'
      x-sysadmin-role: 'Y'
      tags:
        - sla-internal-api
      summary: 根据id查询policy
      description: 根据id查询policy
      operationId: queryPolicyUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: policyId
          in: path
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: 'api-sla.yaml#/definitions/PolicyDto'
        '400':
          description: Bad Request
          schema:
            type: string
        '404':
          description: Not Found
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
        '502':
          description: Bad Gateway
          schema:
            type: string
  /v1/internal/sla/action/verify:
    get:
      x-product: CyberEngine,OceanProtect X
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 30081
      x-auth-required: 'N'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'N'
      x-sysadmin-role: 'Y'
      tags:
        - sla-internal-api
      summary: 验证sla所有权
      description: 验证sla所有权
      operationId: verifySLAOwnerUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: user_id
          in: query
          required: true
          description: 用户id
          type: string
        - name: sla_uuid_list
          in: query
          required: true
          description: SLA的id列表
          type: array
          items:
            type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '400':
          description: Bad Request
          schema:
            type: string
        '404':
          description: Not Found
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
        '502':
          description: Bad Gateway
          schema:
            type: string
  /v1/internal/slas/policies/ext-parameters:
    get:
      x-product: CyberEngine,OceanProtect X
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 30081
      x-auth-required: 'N'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'N'
      x-sysadmin-role: 'Y'
      tags:
        - sla-internal-api
      summary: 根据policy扩展参数查询sla
      description: 根据policy扩展参数查询sla
      operationId: queryPolicyByExtParamsUsingGET
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: key
          in: query
          required: true
          description: SLA高级参数的key
          type: string
        - name: value
          in: query
          required: true
          description: SLA高级参数的value
          type: string
        - name: is_all_sla
          in: query
          required: false
          description: 是否返回所有SLA
          type: boolean
          default: false
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: 'api-sla.yaml#/definitions/SlaDto'
        '400':
          description: Bad Request
          schema:
            type: string
        '404':
          description: Not Found
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
        '502':
          description: Bad Gateway
          schema:
            type: string
  /v1/internal/sla/action/revoke/{userId}:
    put:
      x-product: CyberEngine,OceanProtect X
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-access-port: 30081
      x-auth-required: 'N'
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'N'
      x-sysadmin-role: 'Y'
      tags:
        - sla-internal-api
      summary: 撤销sla的用户id
      description: 撤销sla的用户id
      operationId: revokeSLAOwnerUsingPUT
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: userId
          in: path
          required: true
          type: string
          description: 用户id
      responses:
        '200':
          description: OK
          schema:
            type: string
        '400':
          description: Bad Request
          schema:
            type: string
        '404':
          description: Not Found
          schema:
            type: string
        '500':
          description: Internal Server Error
          schema:
            type: string
        '502':
          description: Bad Gateway
          schema:
            type: string
definitions:
  DemoInfo:
    description: This is a demo
    required:
      - name
    properties:
      id:
        type: string
        description: 唯一标识ID
        minLength: 32
        maxLength: 36
        readOnly: true
        example: 28f61af50fc9452aa0ed5ea25c3cc3d3
      name:
        type: string
        description: 名称
        minLength: 2
        maxLength: 64
        example: MyDemo
      description:
        type: string
        description: 描述
        minLength: 2
        maxLength: 512
        example: this is a demo
  ErrorRsp:
    description: 失败时返回的错误对象
    required:
      - error_code
      - error_msg
    properties:
      error_code:
        description: 错误码
        type: string
        minLength: 8
        maxLength: 36
      error_msg:
        description: 错误描述
        type: string
        minLength: 2
        maxLength: 512
