swagger: '2.0'
info:
  version: v1
  title: ResourceAccessFramework
basePath: /
tags:
  - name: JsonSchema Internal API
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /v2/internal/jsonschemas/{schemaName}/validation/result:
    get:
      x-product: OceanProtect X
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-sysadmin-role: 'Y'
      x-auth-required: 'N'
      x-public-api: 'N'
      x-request-examples-url-1: /v2/internal/jsonschemas/Oracle/validation
      x-request-examples-description-1: >-
        对Oracle资源进行校验，规定的文件名为Oracle_define.json，对应的schemaName为Oracle；被校验的数据以Json对象的格式给出，如示例内容中所示
      x-request-examples-text-1:
        uuid: string
        name: string
        type: string
        subtype: string
        path: string
        createdTime: string
        parentName: string
        parentUuid: string
        protectionStatus: string
        sourceType: string
        userId: string
        authorizedUser: string
        extendInfo:
          key1: string
          key2: string
          key3: string
      x-request-examples-1:
        uuid: string
        name: string
        type: string
        subtype: string
        path: string
        createdTime: string
        parentName: string
        parentUuid: string
        protectionStatus: string
        sourceType: string
        userId: string
        authorizedUser: string
        extendInfo:
          key1: string
          key2: string
          key3: string
      tags:
        - JsonSchema Internal API
      summary: 校验
      description: 通过jsonschema文件校验传入的数据
      x-access-port: 30081
      operationId: ValidateData
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: checkedData
          in: query
          description: 需要被校验的数据，以json字符串的格式给出
          type: string
          required: true
          x-access-port: 30081
          x-auth-required: 'N'
          x-public-api: 'N'
          minLength: 1
          maxLength: 10240
        - name: schemaName
          in: path
          description: JsonSchema文件名字，按照统一规定给出，如资源相关的文件名为resourceSubType_define.json，则schemaName为resourceSubType
          required: true
          x-access-port: 30081
          type: string
          x-auth-required: 'N'
          x-public-api: 'N'
          minLength: 1
          maxLength: 40
      responses:
        '200':
          description: ok
        '400':
          description: Bad Request
        '404':
          description: Not Found
  /v2/internal/jsonschemas/{schemaName}/fields/editable:
    get:
      x-product: OceanProtect X
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-sysadmin-role: 'Y'
      x-auth-required: 'N'
      x-public-api: 'N'
      x-request-examples-url-1: /v2/internal/jsonschemas/Oracle/editable_data
      x-request-examples-description-1: 查找schema文件中定义的可编辑的元素，文件名规定为Oracle_define.json，schemaName则为Oracle
      tags:
        - JsonSchema Internal API
      summary: 获取可编辑字段
      description: 获取传入数据中可编辑的字段
      operationId: ListEditableFields
      x-access-port: 30081
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - '*/*'
      parameters:
        - name: schemaName
          in: path
          description: JsonSchema文件名字，按照统一规定给出，如资源相关的文件名为resourceSubType_define.json，则schemaName为resourceSubType
          required: true
          x-access-port: 30081
          type: string
          x-auth-required: 'N'
          x-public-api: 'N'
          minLength: 1
          maxLength: 40
      responses:
        '200':
          description: ok
          schema:
            type: array
            items:
              type: string
          examples:
            application/json:
              - editableElement1
              - editableElement2
              - editableElement3
        '400':
          description: Bad Request
        '404':
          description: Not Found
  /v2/internal/jsonschemas/{schemaName}/fields/secret:
    get:
      x-product: OceanProtect X
      x-dm-role: 'N'
      x-impact-subsystem: 不影响
      x-rd-admin-role: 'N'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-sysadmin-role: 'Y'
      x-auth-required: 'N'
      x-public-api: 'N'
      x-request-examples-url-1: /v2/internal/jsonschemas/Oracle/secret_data
      x-request-examples-description-1: 获取schema文件中定义的敏感字段，schema文件名规定为Oracle_define.json，schemaName则为Oracle
      tags:
        - JsonSchema Internal API
      summary: 获取敏感字段
      description: 获取传入数据中的敏感字段
      operationId: ListSecretFields
      x-access-port: 30081
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - '*/*'
      parameters:
        - name: schemaName
          in: path
          description: JsonSchema文件名字，按照统一规定给出，如资源相关的文件名为resourceSubType_define.json，则schemaName为resourceSubType
          required: true
          x-access-port: 30081
          type: string
          x-auth-required: 'N'
          x-public-api: 'N'
          minLength: 1
          maxLength: 40
      responses:
        '200':
          description: ok
          schema:
            type: array
            items:
              type: string
          examples:
            application/json:
              - secretElement1
              - secretElement2
        '400':
          description: Bad Request
        '404':
          description: Not Found
