swagger: '2.0'
info:
  title: k8s规则管理接口
  version: v1
tags:
  - name: k8s-rule
paths:
  /v1/internal/rules/kubernetes/action/verify:
    get:
      produces:
        - application/json
      parameters:
        - description: 用户ID
          in: query
          name: user_id
          required: true
          type: string
        - collectionFormat: multi
          description: K8S规则uuid列表
          in: query
          items:
            type: string
          name: uuid_list
          required: true
          type: array
      responses:
        '200':
          description: Successful Response
          schema: {}
        '422':
          description: Validation Error
          schema:
            $ref: '#/definitions/HTTPValidationError'
      tags:
        - k8s-rule
      description: |-
        供内部参数校验，验证user_id对应用户是否有权限操作uuid_list对应的K8S规则

        :param user_id: 用户id
        :param uuid_list: 待检测的kubernetes规则对应的uuid列表
        :return:
        :raise:
      operationId: >-
        internal_verify_k8s_rule_ownership_v1_internal_rules_kubernetes_action_verify_get
      summary: Internal Verify K8S Rule Ownership
  '/v1/internal/rules/kubernetes/{uuid}':
    get:
      produces:
        - application/json
      parameters:
        - description: Kubernetes规则的uuid
          in: path
          name: uuid
          required: true
          type: string
      responses:
        '200':
          description: Kubernetes规则详细信息
          schema:
            $ref: '#/definitions/QueryK8SRuleResponse'
        '422':
          description: Validation Error
          schema:
            $ref: '#/definitions/HTTPValidationError'
      tags:
        - k8s-rule
      description: |-
        供内部调用，查找1条kubernetes规则

        接口: /v1/internal/rules/kubernetes/{uuid} 方法： Get

        :param uuid: kubernetes规则id
        :return: 返回kubernetes规则响应
        :raise: NA
      operationId: get_internal_k8s_rule_by_id_v1_internal_rules_kubernetes__uuid__get
      summary: 按uuid查询单个Kubernetes规则
definitions:
  CreateK8SRuleRequest:
    properties:
      name:
        description: Kubernetes规则名称
        maxLength: 64
        minLength: 1
        pattern: '^[a-zA-Z_\u4e00-\u9fa5]{1}[\u4e00-\u9fa5\w-]*$'
        title: Name
        type: string
      sub_rules:
        description: Kubernetes子规则列表
        items:
          $ref: '#/definitions/CreateK8SSubRuleRequest'
        maxItems: 16
        minItems: 1
        title: Sub Rules
        type: array
    required:
      - name
      - sub_rules
    title: CreateK8SRuleRequest
    type: object
  CreateK8SSubRuleRequest:
    properties:
      actions:
        description: Kubernetes子规则下对应的命令列表
        items:
          maxLength: 1024
          minLength: 1
          type: string
        maxItems: 16
        minItems: 1
        title: Actions
        type: array
      container:
        description: 应用Kubernetes子规则的容器名称
        maxLength: 64
        minLength: 1
        title: Container
        type: string
      pod_selectors:
        description: 应用Kubernetes子规则的pod筛选器列表
        items:
          maxLength: 128
          minLength: 3
          type: string
        maxItems: 32
        minItems: 1
        title: Pod Selectors
        type: array
        uniqueItems: true
    required:
      - pod_selectors
      - actions
    title: CreateK8SSubRuleRequest
    type: object
  HTTPValidationError:
    properties:
      detail:
        items:
          $ref: '#/definitions/ValidationError'
        title: Detail
        type: array
    title: HTTPValidationError
    type: object
  IdResponse:
    description: 修改、创建K8S Rule成功响应
    properties:
      uuid:
        description: Kubernetes规则的唯一uuid
        maxLength: 64
        minLength: 1
        title: Uuid
        type: string
    required:
      - uuid
    title: IdResponse
    type: object
  PagedQueryK8SRuleItem:
    description: |-
      分页查询K8S Rule的响应
      包含：1.QueryK8SRuleResponse
      2. number_of_sub_rules: 界面会显示当前K8S rule下子规则数目
    properties:
      name:
        description: Kubernetes规则名称
        title: Name
        type: string
      number_of_sub_rules:
        title: Number Of Sub Rules
        type: integer
      sub_rules:
        description: Kubernetes子规则列表
        items:
          $ref: '#/definitions/QueryK8SSubRuleResponse'
        title: Sub Rules
        type: array
      uuid:
        description: Kubernetes规则的唯一uuid
        title: Uuid
        type: string
    title: PagedQueryK8SRuleItem
    type: object
  PagedQueryK8SRulesResponse:
    description: |-
      分页查询K8S Rules的响应
      total: int = Field(description="总的数据条数")
      pages: int = Field(description="总页数")
      page_size: int = Field(description="每页数据量")
      page_no: int = Field(description="页面编号")
      items： list[QueryK8SRuleResponse]
    properties:
      items:
        description: 数据列表
        items:
          $ref: '#/definitions/PagedQueryK8SRuleItem'
        title: Items
        type: array
      page_no:
        description: 页面编号
        title: Page No
        type: integer
      page_size:
        description: 每页数据量
        title: Page Size
        type: integer
      pages:
        description: 总页数
        title: Pages
        type: integer
      total:
        description: 总的数据条数
        title: Total
        type: integer
    required:
      - total
      - pages
      - page_size
      - page_no
      - items
    title: PagedQueryK8SRulesResponse
    type: object
  QueryK8SRuleResponse:
    description: |-
      查询K8S Rule的响应
      取出数据不做校验
    properties:
      name:
        description: Kubernetes规则名称
        title: Name
        type: string
      sub_rules:
        description: Kubernetes子规则列表
        items:
          $ref: '#/definitions/QueryK8SSubRuleResponse'
        title: Sub Rules
        type: array
      uuid:
        description: Kubernetes规则的唯一uuid
        title: Uuid
        type: string
    title: QueryK8SRuleResponse
    type: object
  QueryK8SSubRuleResponse:
    description: |-
      查询K8S子规则的响应
      取出数据不做校验
    properties:
      actions:
        description: Kubernetes子规则下对应的命令列表
        items:
          type: string
        title: Actions
        type: array
      container:
        description: 应用Kubernetes子规则的容器名称
        title: Container
        type: string
      pod_selectors:
        description: 应用Kubernetes子规则的pod筛选器列表
        items:
          type: string
        title: Pod Selectors
        type: array
        uniqueItems: true
      uuid:
        description: Kubernetes子规则的唯一uuid
        title: Uuid
        type: string
    title: QueryK8SSubRuleResponse
    type: object
  UpdateK8SRuleRequest:
    description: 修改K8S Rule的请求
    properties:
      name:
        description: Kubernetes规则名称
        maxLength: 64
        minLength: 1
        pattern: '^[a-zA-Z_\u4e00-\u9fa5]{1}[\u4e00-\u9fa5\w-]*$'
        title: Name
        type: string
      sub_rules:
        description: Kubernetes子规则列表
        items:
          $ref: '#/definitions/UpdateK8SSubRuleRequest'
        maxItems: 16
        minItems: 1
        title: Sub Rules
        type: array
      uuid:
        description: Kubernetes规则的唯一uuid
        maxLength: 64
        minLength: 1
        title: Uuid
        type: string
    required:
      - name
      - sub_rules
      - uuid
    title: UpdateK8SRuleRequest
    type: object
  UpdateK8SSubRuleRequest:
    description: 修改K8S子规则的请求
    properties:
      actions:
        description: Kubernetes子规则下对应的命令列表
        items:
          maxLength: 1024
          minLength: 1
          type: string
        maxItems: 16
        minItems: 1
        title: Actions
        type: array
      container:
        description: 应用Kubernetes子规则的容器名称
        maxLength: 64
        minLength: 1
        title: Container
        type: string
      pod_selectors:
        description: 应用Kubernetes子规则的pod筛选器列表
        items:
          maxLength: 128
          minLength: 3
          type: string
        maxItems: 32
        minItems: 1
        title: Pod Selectors
        type: array
        uniqueItems: true
      uuid:
        description: Kubernetes子规则的唯一uuid
        maxLength: 64
        title: Uuid
        type: string
    required:
      - pod_selectors
      - actions
    title: UpdateK8SSubRuleRequest
    type: object
  ValidationError:
    properties:
      loc:
        items:
          type: string
        title: Location
        type: array
      msg:
        title: Message
        type: string
      type:
        title: Error Type
        type: string
    required:
      - loc
      - msg
      - type
    title: ValidationError
    type: object
x-components: {}
