swagger: '2.0'
info:
  version: v1
  title: 导出/下载文件管理内部接口
  description: GroupDesc
schemes:
  - https
host: localhost.com
basePath: /
tags:
  - name: api-export-files-internal-api
    description: 内部接口
paths:
  /v1/internal/export-files/{id}:
    put:
      x-product: CyberEngine,OceanProtect X
      x-dm-role: 'N'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-sysadmin-role: 'N'
      x-impact-subsystem: 影响
      x-access-port: 30081
      x-auth-required: 'N'
      x-public-api: 'N'
      tags:
        - api-export-files-internal-api
      summary: 修改导出文件记录
      description: 修改导出文件记录
      operationId: UpdateExportFile
      parameters:
        - name: id
          in: path
          required: true
          type: string
          description: 导出记录ID
          maxLength: 64
          x-impact-subsystem: 影响
          x-access-port: 25081
          x-auth-required: 'N'
          x-rd-admin-role: 'N'
          x-auditor-role: 'N'
          x-dp-admin-role: 'N'
          x-public-api: 'N'
          x-sysadmin-role: 'N'
        - name: request
          in: body
          required: true
          description: 修改导出文件请求参数
          schema:
            $ref: '#/definitions/ExportFileModifyRequest'
      responses:
        '200':
          description: 无返回值
definitions:
  ERROR:
    description: 错误信息
    required:
      - code
    properties:
      code:
        type: integer
        format: int64
        description: 错误码
      params:
        type: array
        items:
          type: string
        description: 错误码参数
  Data:
    description: 数据
    required:
      - size
      - md5
      - downloadPath
    properties:
      size:
        type: integer
        format: int64
        description: 文件大小
      md5:
        type: string
        description: MD5
      downloadPath:
        type: string
        description: 下载路径
  ExportFileModifyRequest:
    description: 修改导出文件请求参数
    properties:
      error:
        description: 错误信息
        $ref: '#/definitions/ERROR'
      data:
        description: 数据
        $ref: '#/definitions/Data'
