swagger: '2.0'
info:
  version: v1
  title: ApplicationTitle
  description: GroupDesc
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
host: localhost.com
basePath: /
tags:
  - name: resource
  - name: lock
paths:
  /v1/internal/locks:
    post:
      x-product: CyberEngine,OceanProtect X
      tags:
        - lock
      summary: 锁定资源
      x-impact-subsystem: 不影响
      x-access-port: 30092
      x-auth-required: 'N'
      x-public-api: 'N'
      description: 创建资源锁
      operationId: CreateResourceLock
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: CreateResourcelockRequestBody
          in: body
          required: true
          description: 锁定资源请求
          schema:
            $ref: '#/definitions/LockRequest'
      responses:
        '200':
          description: 正确响应
        '500':
          $ref: '#/responses/CommonErrorResponse'
    delete:
      x-product: CyberEngine,OceanProtect X
      tags:
        - lock
      x-dm-role: 'Y'
      x-impact-subsystem: 不影响
      x-access-port: 30092
      x-auth-required: 'N'
      x-rd-admin-role: 'Y'
      x-auditor-role: 'Y'
      x-dp-admin-role: 'Y'
      x-public-api: 'N'
      x-sysadmin-role: 'Y'
      summary: 清空资源锁
      description: 清空资源锁信息(当前用于管理数据恢复后使用)
      operationId: DeleteAllResourceLock
      responses:
        '200':
          description: OK
          schema:
            type: string
        '500':
          description: 公共的错响应码
          schema:
            $ref: '#/definitions/ErrorResponse'
          examples:
            application/json:
              errorCode: '1677929221'
              errorMessage: System error.
              parameters: []
              retryable: true
  /v1/internal/locks/{lock_id}:
    delete:
      x-dr-role: 'N'
      x-dm-role: 'N'
      x-rd-admin-role: 'N'
      x-auditor-role: 'N'
      x-dp-admin-role: 'N'
      x-sysadmin-role: 'N'
      x-product: CyberEngine,OceanProtect X8000,OceanProtect X6000,OceanProtect X3000
      tags:
        - lock
      x-impact-subsystem: 不影响
      x-access-port: 30092
      x-auth-required: 'N'
      x-public-api: 'N'
      summary: 释放资源锁
      description: 删除资源锁
      operationId: DeleteResourceLock
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: lock_id
          in: path
          required: true
          type: string
        - name: requestId
          in: query
          required: true
          description: 请求id
          type: string
          minLength: 1
          maxLength: 64
          x-impact-subsystem: 不影响
          x-access-port: 30092
          x-auth-required: 'N'
          x-public-api: 'N'
      responses:
        '200':
          description: 正确响应
          schema:
            type: string
        '500':
          $ref: '#/responses/CommonErrorResponse'
definitions:
  LockRequest:
    description: 资源加锁请求
    x-impact-subsystem: 不影响
    x-access-port: 30092
    x-auth-required: 'N'
    x-public-api: 'N'
    properties:
      requestId:
        type: string
        description: 请求id
        minLength: 1
        maxLength: 64
        x-impact-subsystem: 不影响
        x-access-port: 30092
        x-auth-required: 'N'
        x-public-api: 'N'
      lockId:
        type: string
        description: 资源锁id
        minLength: 1
        maxLength: 64
        x-impact-subsystem: 不影响
        x-access-port: 30092
        x-auth-required: 'N'
        x-public-api: 'N'
      resources:
        type: array
        description: 锁定资源列表
        items:
          $ref: '#/definitions/LockResource'
        x-impact-subsystem: 不影响
        x-access-port: 30092
        x-auth-required: 'N'
        x-public-api: 'N'
        minItems: 1
        maxItems: 128
      priority:
        type: string
        description: 加锁优先级
        default: '3'
        x-impact-subsystem: 不影响
        x-access-port: 30092
        x-auth-required: 'N'
        x-public-api: 'N'
        minLength: 1
        maxLength: 128
    required:
      - requestId
      - lockId
      - resources
      - priority
  LockResource:
    description: 锁定的资源对象
    properties:
      id:
        type: string
        description: 资源id
        minLength: 1
        maxLength: 64
        x-impact-subsystem: 不影响
        x-access-port: 30092
        x-auth-required: 'N'
        x-public-api: 'N'
      lockType:
        type: string
        description: 资源锁类型:r-读锁  w-写锁
        enum:
          - r
          - w
        x-impact-subsystem: 不影响
        x-access-port: 30092
        x-auth-required: 'N'
        x-public-api: 'N'
    required:
      - id
      - lockType
  ErrorResponse:
    description: 统一错误响应
    properties:
      errorCode:
        type: string
        description: 统一错误码
        minLength: 1
        maxLength: 64
        x-impact-subsystem: 不影响
        x-access-port: 30092
        x-auth-required: 'N'
        x-public-api: 'N'
      errorMessage:
        type: string
        description: 统一错误信息
        minLength: 1
        maxLength: 1024
        x-impact-subsystem: 不影响
        x-access-port: 30092
        x-auth-required: 'N'
        x-public-api: 'N'
      parameters:
        type: array
        items:
          type: string
          minLength: 1
          maxLength: 64
        description: 错误信息中的参数列表
        minItems: 1
        maxItems: 64
        x-impact-subsystem: 不影响
        x-access-port: 30092
        x-auth-required: 'N'
        x-public-api: 'N'
    required:
      - errorCode
      - errorMessage
responses:
  CommonErrorResponse:
    description: 公共的错响应码
    schema:
      $ref: '#/definitions/ErrorResponse'
    examples:
      application/json:
        errorCode: '112344'
        errorMessage: param {0} can not be null
        parameters:
          - xxx
