/*
* This file is a part of the open-eBackup project.
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*
* Copyright (c) [2024] Huawei Technologies Co.,Ltd.
*
* THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
* EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
* MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
*/
#include "gtest/gtest.h"
#include "gmock/gmock.h"
#include "stub.h"
#include <protect_engines/kubernetes/util/Transformer.h>
#include <protect_engines/kubernetes/common/KubeErrorCodes.h>

namespace HDT_TEST {
using ::testing::_;
using ::testing::Return;
using ::testing::ReturnRef;
using namespace KubernetesPlugin;
std::pair<int32_t, std::shared_ptr<StorageClient>> Stub_StorageClientCreate(const std::string &ip, int port,
    const AccessAuthParam &accessAuthParam, const std::vector<std::string> &ipList)
{
    StorageDeviceAuthData authData = {"", "", {""}};
    std::shared_ptr <StorageClient> dummy = std::make_shared<StorageClient>(ip, port, accessAuthParam, authData, ipList);
    if (ip == "127.0.0.1" && port == 8088 &&
        accessAuthParam.m_userName == "abc" && accessAuthParam.m_userkey == "123") {
        return std::make_pair(0, dummy);
    } else {
        return std::make_pair(Module::FAILED, dummy);
    }
}

class TransformerTest : public testing::Test {
public:
    void SetUp();
    void TearDown();
    static void SetUpTestCase();
    static void TearDownTestCase();

};

void TransformerTest::SetUp() {}
void TransformerTest::TearDown() {}
void TransformerTest::SetUpTestCase() {}
void TransformerTest::TearDownTestCase() {}

/**
 * 测试用例：测试FulfillVolInfo函数成功
 * 前置条件：预置正常的数据
 * Check点：VolInfo被正确填充。
 */
TEST_F(TransformerTest, FulfillVolInfoShouldSuccess) {
    VolInfo targetVolInfo;

    StorageDeviceInfo storageDeviceInfo;
    LunInfoData lunInfoData;
    lunInfoData.m_sectorSize = "512";
    lunInfoData.m_capacity = "128";
    StorageParam storageParam;
    storageParam.ip = "127.0.0.1";
    KubeHelper::FulfillVolInfo(targetVolInfo,
                               storageDeviceInfo,
                               lunInfoData,
                               storageParam);
    EXPECT_EQ(targetVolInfo.m_datastore.m_ip, storageParam.ip);
}

/**
 * 测试用例：测试GetStorageParamVecFromAppEnv函数成功
 * 前置条件：预置正常的数据
 * Check点：返回正确的StorageParamList。
 */
TEST_F(TransformerTest, GetStorageParamVecFromAppEnv_ShouldSuccess) {
    std::string authExtendInfo = R"({"config":"123","storages":"[{\"username\": \"test\",\"password\": \"test\",\"ip\": \"8.40.111.70\",\"port\": 8088},{\"username\": \"test\",\"password\": \"test\",\"ip\": \"127.0.0.1\",\"port\": 8088}]"})";
    auto storageOptList = KubeHelper::GetStorageParamVecFromAppEnv(authExtendInfo);
    EXPECT_TRUE(storageOptList);
    EXPECT_EQ(storageOptList->size(), 2);
    EXPECT_EQ((*storageOptList)[1].ip, "127.0.0.1");
}

/**
 * 测试用例：测试GetKubernetesApiFromAppEnv函数成功
 * 前置条件：config参数正常
 * Check点：返回正确的KubernetesApi。
 */
TEST_F(TransformerTest, GetKubernetesApiFromAppEnv_ShouldSuccess) {
    std::string authExtendInfo = R"({"config":"a2luZDogQ29uZmlnCmFwaVZlcnNpb246IHYxCmNsdXN0ZXJzOgotIGNsdXN0ZXI6CiAgICBjZXJ0aWZpY2F0ZS1hdXRob3JpdHktZGF0YTogTFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVaE9la05EUWxJclowRjNTVUpCWjBsS1FVMXZhblpFUVZWYVJrWnJUVUV3UjBOVGNVZFRTV0l6UkZGRlFrTjNWVUZOU1Vjd1RWRnpkME5SV1VRS1ZsRlJSMFYzU2tSVWFrVlRUVUpCUjBFeFZVVkRRWGRLVWpOV2FHSnRaRVZpTWpWdVRWSkZkMFIzV1VSV1VWRklSRUZvVkdGSFZuVlhiV2hzWW1wRmJBcE5RMDFIUVRGVlJVTm5kMk5UU0Zab1pESldjRWxHVW14Wk1taDFZako0ZGxveWJHeGplVUpFWW5rMGMwbEZlREJhUkVWb1RVSTRSMEV4VlVWRGQzZFpDbFF4VGxSSlExbG5WVEpXZVdSdGJHcGFVMEpWWWpJNWMyTjVRa1ZhV0VJd1RWSkpkMFZCV1VSV1VWRkVSRUZzVUZVeFRYcE1ha0ZuVVRCRmVFbEVRV1VLUW1kcmNXaHJhVWM1ZHpCQ1ExRkZWMFZYT1hwamVrNXFXVlZDYjJSWFJqTmFWMnQxV1RJNWRFMUNORmhFVkVsNVRVUlpkMDFxUVhwT1JHY3hUbXh2V0FwRVZFMTVUVVJWZWsxRVFYcE9SR2N4VG14dmQyZGlVWGhEZWtGS1FtZE9Wa0pCV1ZSQmEwNVBUVkpKZDBWQldVUldVVkZKUkVGc1NHUlhSblZhTUZKMkNtSnRZM2hGVkVGUVFtZE9Wa0pCWTAxRFJrNXZXbGMxWVdGSFZuVk5VMVYzU1hkWlJGWlJVVXRFUW5oSlpGZEdNMXBYYTJkV1IxWnFZVWMxZG1KSE9XNEtZVmRXZWtsRlRuWk1hWGRuVkVoU2EwMVRSWGRJZDFsRVZsRlJURVJDYUZCVk1VMW5TbWxDVkZwWVNqSmhWMDVzU1VaU2RtSXllSHBKUlZKc1kwaFJlQXBGYWtGUlFtZE9Wa0pCVFUxRFZUbFVWWHBOZFUxRFFrUlJWRVZuVFVJMFIwTlRjVWRUU1dJelJGRkZTa0ZTV1ZKaU0wNTZUVEpPYUZGSGFERlpXR1JzQ21GVE5XcGlNakIzWjJkSmFVMUJNRWREVTNGSFUwbGlNMFJSUlVKQlVWVkJRVFJKUTBSM1FYZG5aMGxMUVc5SlEwRlJSRk5LUkhsd2QzbFlURWhDTHpVS2JYSkZhR2gwV1RWalQzbGxUbVF2VVVWNGJuWlJZV1JhUW5KSGQwRjVNVzQ1YjNvM2JGTTVWREpHUm01NmJVbFlVMDVLWlZkVVFYVk5PV1F5V0c1RGFBbzRXVE5oYVdoemIxSTBORmhWTDNWd015dE5ZWFJPVG1kMlpuTXpORGhYYm05M2RHdFRkREpHVW1FcmNuaEZWbWQxZDIwNFNubHVkV2xDWmpaMVZ6WjBDbFpuYUVSSVMzSXJSbVVyYVV0ek5uaGlOWGR4YXpGWlRuaE1VRVkxVEdVeWNWVkdlVEJVY1ZKSU9YTmFUazlwWkZOdk9XUk1aR0pNVEROa2RreHNjRzhLUTBoVFF6QmpPUzkzTmxaVU5YVlRkMVY2V1VkT2MwUnlaeXRxVWtGVFdtaE5SVnBWVGtoNVJXeGxkWGQwUzBwNVlsTjJSbmhwV0hKa2RHdDRWMVphYndwcFRrOW5WbkZOZGpCWU5HOVJha1J3YlRWdlNYQnZhR2hYV0VWUE5VVndhblpZZEdkYU5rSnRiVlZVTURFclpHMWFkMjFpVXpadmRGSTFWemhPTjBoTUNrcHhTVFpRYVRWRlIwNUlSakppTkROR1VGUnZNblo0UjBSclNFRjFORXhPU0RkS05rRm5lRVZ1TW1rMlJtOTNXRWd6ZWtwd1FqQmFaVzVaYW5WMlZUWUtOMFE1UVdjcmFFUnVjRzkxUW5CSlVXaENSR28zVVdKSk5YUXhjVzFNVDFNMU1FMTNTWEFyWmxwWGFsVmtNMmxsYml0TVNqaGlRWFpZWTNKa1NYbENWd28yTmxweVV6STVPR0paYlVkWFdUTnJhVWhuUVZsalptWnBMMkkwWXpaNk1uWnNWWG8yYmxWMmJ5OWpXbHBaYTFOR1dHOVNWWE5uUzNJNWMzcFZNblppQ2s1VmRIbFVkekZqVFRKTk1qaDRNVWQwTDNkWVpsTlZlVXNyVjJKMVYzZHpkMFJRYTBOcE9HVk1RVTloU0dZeVFUaEdNa1prYUVkVk1FaGlVV1p6TVVrS1ZrTlJLMkpWWkdWVGMxWm1PVUY1VURGU2RHSnNWMjF1YzNkTU1FYzRiemRtY3pjeWRrNXRTVVIyY2pGc1pXZHRLMHh0VVVKRVpEVkVUVTFYWlVOcE9RcFVVbGRVUXpseE1tWmpVbHAxTldWeU0wOVJSVmdyZFVKT05IZEVkRkZKUkVGUlFVSnZORWxDVTBSRFEwRlZVWGRJVVZsRVZsSXdUMEpDV1VWR1RucFZDbkp2Wm5kR1RHOTJaR0pIZFhnd1F6ZHViRTAyVjBZNFpFMUpTSEJDWjA1V1NGTk5SV2RsUlhkblpEWkJSazU2VlhKdlpuZEdURzkyWkdKSGRYZ3dRemNLYm14Tk5sZEdPR1J2V1VjMmNFbEhNMDFKUnpCTlVYTjNRMUZaUkZaUlVVZEZkMHBFVkdwRlUwMUNRVWRCTVZWRlEwRjNTbEl6Vm1oaWJXUkZZakkxYmdwTlVrVjNSSGRaUkZaUlVVaEVRV2hVWVVkV2RWZHRhR3hpYWtWc1RVTk5SMEV4VlVWRFozZGpVMGhXYUdReVZuQkpSbEpzV1RKb2RXSXllSFphTW14c0NtTjVRa1JpZVRSelNVVjRNRnBFUldoTlFqaEhRVEZWUlVOM2QxbFVNVTVVU1VOWloxVXlWbmxrYld4cVdsTkNWV0l5T1hOamVVSkZXbGhDTUUxU1NYY0tSVUZaUkZaUlVVUkVRV3hRVlRGTmVreHFRV2RSTUVWNFNVUkJaVUpuYTNGb2EybEhPWGN3UWtOUlJWZEZWemw2WTNwT2FsbFZRbTlrVjBZeldsZHJkUXBaTWpsMFoyZHJRWGxwVHpoTlFsSnJWVmRSZDBSQldVUldVakJVUWtGVmQwRjNSVUl2ZWtGTVFtZE9Wa2hST0VWQ1FVMURRVkZaZDBoQldVUldVakJTQ2tKQ1ZYZEZORVZTWWpOT2VrMHlUbWhSUjJneFdWaGtiR0ZUTldwaU1qQjNSRkZaU2t0dldrbG9kbU5PUVZGRlRFSlJRVVJuWjBsQ1FVTlVTWGxFVkdzS05YQlBRVVJrVldzemJVdGpUR1Z5V2pGR1NVMTVhMlkxUzNScFFVNTBZMHhyUjJZNVdGTjVURmw2WW5OQ2FUWklhbTVUTjJ0MFoxZFFhRWQ2WlN0b2RRcENhMGwzYkhkNlJEVmlkbU0wSzJWV1Uyd3ZUa0Y1YzBsSmFuQlNialI1Y0cxRmVYQkNRM3B6TVdwV1FuVndiak5SVERWYVoyTkZNSFJWZEZvemJVbHNDblJxTVdwSVJqQmtVSFoxY3padk0yc3pNaXN5TjIwMlRVeHFOeXRFYW1GTGRUSkJlalY1YkROdWVTdFBVVGs1VkZKemRWQk9XblYxUjNWSGJuUndORUVLUml0MGREWjBlbTB5VkRnd1ptZG1WVmxQTDNGMVNHdEJTVGRoWlRSQk5FWkxOSGhZYldKeldWRmxaR0Z2VmxoMU1VVldiRFExTkZCWVIxaG5aMjB2ZVFwT01qUlpRbXNyYzFSWWRFNUpUMjVyU21Rd1NFZE5VRzlYT1U1SlRFUk5aM2tyYTB0VmRFWkJVakV5T1Rad1lsaHJUM3A1ZVRWSk5IQjJSV3BzTlRSV0NuVkNWRzF2WW1aRlJFUlFNbk5YV2sxa1RrbFNlRlZUVVdwV2JHRm9Na3B5TVhGTFdFOWtOVlpJTTBaVU1ucDRlbXRJZGpkMGJrZHVWblpSZEc5cU1Xb0tOVzEzT1cxS0sydFRhMDFEY1VoRFZEZElXRGRuVWxkeWRERmlTekZSTkRoMlVYbHZObGx5VG01MmVrZExaMEZPZUhZNWNrZE9Na3RPWm5wclowSjNTQXA2T1RGU2QwOVZUbnBDVUhsc00yMUZRUzh5Wm5OUlVrWXlPRVZ6YURrMFprOUdTVmRYUnpOeVdHTjBRa1UyWm5oMWNUVmlhVUYwZG01SFoxVkthbWhYQ2tkcWREVTNVREpFZWtkNU5rMTBWM2RSUzJJMlRsZ3haMVZpZFZsQldYZHZOelpRU1RsaWVuWlFlVU53UTJFeWFXaEplR1YzYTNOWlNHSndVMWhDUkdVS0syZHZhR05KY21oNlYybE9hamMwUXpCNVRXMXZURzl4WkhWNFpHVk9OM2RrYWpnNVJWTlpTbXRaZG5kU2F6RkZRWHAwWVZOeFlXMUNOV2RoYzA5UFRRb3dUVVp5TTA1a2FISkpVVFpVUmxOQ1VFOU5SV2xYTUU5bE9VdFRTbEZ3TW5oWlJuRUtMUzB0TFMxRlRrUWdRMFZTVkVsR1NVTkJWRVV0TFMwdExRbz0KICAgIHNlcnZlcjogaHR0cHM6Ly84LjQwLjEzNy43OjU0NDMKICBuYW1lOiBjbHVzdGVyCnVzZXJzOgotIG5hbWU6IGNmZS1tYXN0ZXIKICB1c2VyOgogICAgY2xpZW50LWNlcnRpZmljYXRlLWRhdGE6IExTMHRMUzFDUlVkSlRpQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENrMUpTVWN3ZWtORFFreDFaMEYzU1VKQlowbEpWRmRYUTBsUlpqZ3ZWa2wzUkZGWlNrdHZXa2xvZG1OT1FWRkZURUpSUVhkbllsRjRRM3BCU2tKblRsWUtRa0ZaVkVGclRrOU5Va2wzUlVGWlJGWlJVVWxFUVd4SVpGZEdkVm93VW5aaWJXTjRSVlJCVUVKblRsWkNRV05OUTBaT2IxcFhOV0ZoUjFaMVRWTlZkd3BKZDFsRVZsRlJTMFJDZUVsa1YwWXpXbGRyWjFaSFZtcGhSelYyWWtjNWJtRlhWbnBKUlU1MlRHbDNaMVJJVW10TlUwVjNTSGRaUkZaUlVVeEVRbWhRQ2xVeFRXZEthVUpVV2xoS01tRlhUbXhKUmxKMllqSjRla2xGVW14alNGRjRSV3BCVVVKblRsWkNRVTFOUTFVNVZGVjZUWFZOUTBKRVVWUkZaMDFDTkVjS1ExTnhSMU5KWWpORVVVVktRVkpaVW1JelRucE5NazVvVVVkb01WbFlaR3hoVXpWcVlqSXdkMGxDWTA1TmFrbDNUbXBCZVUxRVZYZE5hbEV5VjJoblVBcE5ha0V6VFZSQk1rMUVTWGRPVkVGNVRrUmFZVTFKUjNCTlVYTjNRMUZaUkZaUlVVZEZkMHBFVkdwRlUwMUNRVWRCTVZWRlEwSk5TbEl6Vm1oaWJXUkZDbUl5Tlc1TlVrVjNSSGRaUkZaUlVVaEZkMmhVWVVkV2RWZHRhR3hpYWtWc1RVTk5SMEV4VlVWRGFFMWpVMGhXYUdReVZuQkpSbEpzV1RKb2RXSXllSFlLV2pKc2JHTjVRa1JpZVRSelNVVjRNRnBFUldoTlFqaEhRVEZWUlVOM2QxbFVNVTVVU1VOWloxVXlWbmxrYld4cVdsTkNWV0l5T1hOamVVSkZXbGhDTUFwTlVrbDNSVUZaUkZaUlVVUkZkMnhRVlRGTmVreHFRV2RSTUVWNFJsUkJWRUpuVFhCQlVVVlVSRWhDYUZsWVRYUmlNakIwV1RJNWVWcFVRME5CYVVsM0NrUlJXVXBMYjFwSmFIWmpUa0ZSUlVKQ1VVRkVaMmRKVUVGRVEwTkJaMjlEWjJkSlFrRk9WV05hU1VacWQwWTNablU0YWpkMlJtdG9WbUZIVlhORVdsSUtkMGx2WnpOb1JISmhWemxEVFRaaVFqWmhaRXAxVEVOeWEzSnBSM1p3VGt0cFZWUm1hVkZZVFhaeVZWWk1iMmROUVdsUmJrazRSR1JoZGtGcmVYZDViZ294T0hCM2NGRjZZME5hYm01SVR6Rllaamw0VEN0SFdHTkhUV013Tm5OaFNVUk9lbmRzUTNacE9URlhNemgwVlVod2EwRjVibFpuVm0weFpuUm9OVFUxQ21OaFRXSXhWVkZEV1RGNGNpOVRTRk13WlVOaFNsUkVOQ3RqZVZwTlNuWjNSRzg0VlhoblRuRTFhMU5LVlZwTVEybEhlbUZ1V1dKdVNGVmtLeXR1ZWxJS2VHOVNPR05LVlhseGVtWXhlVmRqTjAxNGRUbDFaR0YwUm1WMll5czVURk5KTlRaM1MwYzFjbFE1WkVkUU5VNWlkelF6TVhKdVJFaFJURTkxYUZCTE5BcGFRamd5UXk5R2NHWnRZelJZVG05c1dEQTVXVUp1WTBSV1lrTnVTMlJFUVc1SWVtcGlWbnAwVVVGUWExUm9ORVYxV1hsMVNGQlhURFJDU1RkWE5sVjBDbWt3Y21weFZFTTBaVEZuYlRKNlpuTjJZa3MxVG1ocFVsaHdUblpETlVwbk1GSnRVR05CTjFsT05YRnBiMHhNTDFjMGJqbHZRa3htYzBkVGJuRkJia0lLZDBGTFMwSnlSRzUzV2xjelVVcEdWalp5UldsWk9FZFBUVk5aWjB4cFVuSnplVXhNZURGV05pc3dVbkpyUm0xRFpGUlRlVmxvTVZGQlJUSllRbGhVVVFwVVQwdFFSMlZYYjJndlFVbE9Vbk5NVDNSMWNVMUllVmQzUTFSaFIyazBTa2hXUVcxc0wxTTVaRzEzVjFrMU4xQnpTek5qUjIxS1NtUllWRWxFUmpKU0NsbG5iRGN3VVRWWWNFRmxRems1Tkc5WGRFWmtVMGRuTW5VdmNXdFJhbmR2UjNoSFpqUlNTemR2YzB4ME5rdEJUVUpTTjFJclJuaHlkMEUyYzJoRWFVUUtORXBsUkdZM2FUaFpZWFZFYW01T2NGRXpMMDV2WlVSS1lsRkZabFphYzNkSmQzcHFVVk5KVDFwelpubEJORUZNYUVOeWNqZEpialJtTDBKcFpteG9UQXBLYkUxUGJHTjBhSEUzWXpjdlRtNHpRV2ROUWtGQlIycG5aVGgzWjJWM2QwUm5XVVJXVWpCUVFWRklMMEpCVVVSQlowdHJUVUl3UjBFeFZXUktVVkZYQ2sxQ1VVZERRM05IUVZGVlJrSjNUVU5DWjJkeVFtZEZSa0pSWTBSQlZFRk5RbWRPVmtoU1RVSkJaamhGUVdwQlFVMUNPRWRCTVZWa1NYZFJXVTFDWVVFS1JrNTZWWEp2Wm5kR1RHOTJaR0pIZFhnd1F6ZHViRTAyVjBZNFpFMUpSMHhDWjA1V1NGSkZSV2RaVFhkbldVTkRRak5DYUZsWVRYUmlNakpEUVVsSllncExhVFZyV2xkYWFHUlhlREJNYms0eVdYazFhbUpJVm5wa1IxWjVURzE0ZGxreVJuTm5hRmx4VEcwNWRFeHVUakpaZVRWcVlraFdlbVJIVm5sTWJYaDJDbGt5Um5ObmFHOXhURzB4YUdKdFJtNWFVelY2WkcxTmRWa3llREZqTTFKc1kyazFjMkl5VG1oaVNXTkZjMEozUVVGWlkwVnpRbmRCUVc5alJXWjNRVUVLUVZsalJVTkRhVXBDTkdORlEwTnBTa0kwWTBWRFEybEtRbnBCVGtKbmEzRm9hMmxIT1hjd1FrRlJjMFpCUVU5RFFXZEZRVWRNVkdSUVVXbFBha1l6THdwWUt5OUZibm94T0RKVUt6bG1TMGsyYlhvclMwVjJOME42WTNKaFJ5OTVhM0I0YmxsT2JWaHhlbEYyS3preVYwOXhTemczY1VoR2VHNU1SME4yTDAxMENqSlJkRGtyVGtVeWRsbDZWRkpZWVZkdFVuaDVUVmNyVkVWTmN6bEdWVU5sYldobFJqbFpSVTF2TW1OTVJHeHZVbkZzZURseVEyVnJiRmhHTkZSNVJUQUtZVEIzVUZKTk9VVlZlVmxFVlRod01uaFZWSGRrVWt4NGJHVjBWVU13YVhWSmFYQldhVmRYT0dwM1NqRlNWQzh2TmxoRVFWVnpkVklyV1dOT1dFTnBkQW93VVZWNVRVaGxkRVk1TVRsRFlXazVNamhDUzJ4NFpHRjJZMHR5UTBwU2FXRkZUV3REYms4M1dFMXVRa1Z6WTBORE9HVk1LMFo0Um1WcmFuTnZjMDQ1Q2xJM09IbHhURXBuU1U5NFpEUTNTRWhtUVc4MlpVWk1TMGs0U1hCMVJYVXdTSFI1T0cxcVMxRjJNMHRwYXpab05YbFBVM2hrYzNwaVpERTJjamhEWkRJS1ptaE1LMDAyYUdVd2FTOHlWMFExZUZOWGQweElNMGRxY3pjeVVIcG1aMnR3U0dvdlRHaHlhbmxEV0ZKR2FHbDRaMUJMZDJ4TVp6TlRMekZzUTA1alNBcEthekZWWTBGSmRESTVhVWdyWlZSQlRXZHRUR1E0U0hwc1drWm5kemxQZUhoT2NFWm9XVzV6UTBwQ1EyOXVaVGhaVkc5SGFDdDFiMU5MVXpCWFFtZ3JDazFDUms5bmRXUXpPRGNyTmpnMVVIZ3dWa2RDVldWd2NuUmlUbWtyUkVaT09FbENibUUxV2s1b1NUSXJaMnBKVDJack9XdFdUbkEyZEdOdFNYSlVkVE1LVWtkNlJTOHZiazA0VUc1alRHNWFaVWRWVFRaMmF6YzVZM3BKVUROa2IzUlFSMWhNUzNCYVNXRm9RVE5VYVVaVE5WTlBNVWRrVjAwdk9Ib3djMjlST0FvckwwWXlibVJzZEhSUVVrc3pSM1JsZWxOWk1uQnRhVUpsVjFvM01IVkVOMlpLTnpKUE5qUkhVSE5sVDBzMU5VOUdSSGhpZEZWNVVHOHZiblk1VjFkSUNqSjBhVlpVZGxnMlpGcEZkR2hrYWs5Qk4xYzRaRXRSYmxoT2JrWkhVMk05Q2kwdExTMHRSVTVFSUVORlVsUkpSa2xEUVZSRkxTMHRMUzBLCiAgICBjbGllbnQta2V5LWRhdGE6IExTMHRMUzFDUlVkSlRpQlNVMEVnVUZKSlZrRlVSU0JMUlZrdExTMHRMUXBOU1VsS1NuZEpRa0ZCUzBOQlowVkJNVko0YTJkWFVFRllkQ3MzZVZCMU9GZFRSbFp2V2xOM1RteElRV2xwUkdWRlQzUndZakJKZW5CelNIQndNRzAwQ25OTGRWTjFTV0VyYXpCeFNsSk9LMHBDWTNrcmRGSlZkV2xCZDBOS1EyTnFkMDR4Y1RoRFZFeEVTMlpZZVc1RGJFUk9kMHB0WldOak4xWmtMek5GZGpRS1dtUjNXWGg2VkhGNGIyZE5NMUJEVlVzclRETldZbVo1TVZGbGJWRkVTMlJYUWxkaVZpc3lTRzV1YkhodmVIWldVa0ZLYWxoSGRqbEpaRXhTTkVwdmJBcE5VR28xZWtwcmQyMHZRVTlxZUZSSFFUSnliVkpKYkZKcmMwdEpZazV4WkdoMVkyUlNNemMyWms1SVIyaEllSGRzVkV0eVRpOVlTbHA2YzNwSE56STFDakZ4TUZZMk9YbzNNSFJKYW01eVFXOWliWFJRTVRCWkwyc3hka1JxWmxkMVkwMWtRWE0yTmtVNGNtaHJTSHBaVERoWGJDdGFlbWhqTW1sV1psUXhaMGNLWkhkT1ZuTkxZM0F3VFVOalprOU9kRmhQTVVGQksxSlBTR2RUTldwTE5HTTVXWFpuUldwMFluQlRNa3hUZFU5d1RVeG9OMWREWW1KT0szazVjM0pyTWdwSFNrWmxhekk0VEd0dFJGSkhXVGwzUkhSbk0yMXhTMmR6ZGpsaWFXWXlaMFYwSzNkYVMyVnZRMk5JUVVGdmIwZHpUMlpDYkdKa1FXdFdXSEZ6VTBwcUNuZFpOSGhLYVVGMVNrZDFla2x6ZGtoV1dISTNVa2QxVVZkWlNqRk9URXBwU0ZaQlFWUmFZMFprVGtKTk5HODRXalZoYVVnNFFXY3hSM2R6TmpJMmIzY0taa3BpUVVwT2IyRk1aMnRrVlVOaFdEbE1NVEppUWxwcWJuTXJkM0prZDJGWmEyd3haRTFuVFZoYVJtbERXSFpTUkd4bGEwSTBURE16YVdoaE1GWXhTUXBoUkdFM0szRlNRMUJEWjJKRldpOW9SWEoxYVhkMU0yOXZRWGRHU0hSSU5GaEhka0ZFY1hsRlQwbFFaMncwVGk5MVRIaG9jVFJQVDJNeWJFUm1PREpvQ2pSTmJIUkJVamxXYlhwQmFrUlBUa0pKWnpWdGVDOUpSR2RCZFVWTGRYWnphV1pvTHpoSFNpdFhSWE50VlhjMlZua3lSM0owZW5ZNE1tWmpRMEYzUlVFS1FWRkxRMEZuUW1nd2NWZHFObmxyVEc4NFIzTk5WRzB3TlVOT1RtZ3hXVmh4VWtWeWJHOXBOREZaWWxKU2JEZ3hVbUlySzFKWk0yTnpkbFZ1WkU1eFdBb3JPV1pyTkVsTmFWRlhhWE00UzNOeFZXWkVUbkphVjNjeWVrcFRVakpHV2xSMFdUQkhPVGN6WkhreVJrVjBlSEJoWjJaTlJrdGtVMEZ0VkhoV1F6Uk5Dbk5pYWs0eGFsUTVja1JMUTJreWVWSk5ka041WlZWc1YyWktlVkpGVUhneU1YbEpPV292U1cxU1REVmtWakJwWW5SUk1GZ3ZNRzVvU0M5b2VWaFZUVGtLTkZWVFpHdDRhVTU1ZHpCdFIzRTFlVWx2TDBNdk9YSmtZVTF6T0ROWFIxZ3lRMk0yS3pOQmJWaEdjbEl4YVZnNFJpdFhUemN4YTFZelRpczJTUzlqU1FwUUswOVFNMU5pUTBGTmNHMWpPVEpPUVRoMFVrbzFlRXROYm5oV2RtdzVVMng1WlVkWFExaEdVeTl3TURSU09XMUdNQ3RZZFZReFIyUnBXbTlpTWswekNtRnhTM0ZvVXpkWVVVTlNjRnBQZDJsNFYwcDVNMEl4TkRkU2MwOUVUemhvWXk5clFVaDNOMDFuYTBwUlkyOXhNM2ROYWs1dll6Wk5MMm9yVkZCUGNXc0tkR0pRTUZaRVltSnRjbkZaUmpOaE5DdFRTMnRrVGtzNFptOVFhMnRLYldzMmNDdE1RM0ExUW5oa05sTXpjRkUxZW1Gc1MxTm9RMlpXYUUwMVZGVmhWZ3BrUTNWalJ6ZFdPRzFqTW5CelRFZEVhM0JvUVRGUmVXZ3piMVprY2tOeVlWaDBUamhzVWtJelVsQjFZeTlLWm5vemJtbG9SMjlDY2tONVNIRXJXbGxrQ2xJMlprTjFNVmhSWmpCWVYwMUtZVlJPTTJ0eGVUWlpPRlJuYURsRVVrNXROVEZ4VDFCMFZVNU1kWEpOUlhnNGEzb3dReXRsS3pWVGNVMTRhMWg0ZWtrS2VtSTVkekoxUjI1dmFtdzBOMFUzY0V4aU5IZDZiMmR5ZW1aNmJTOU9VbUV5VVZONWNIcHhRM2hJWXpCcWRuZDVaMGxMU0hJclNUWkhkM2Q1ZGpSc1RncEtOa2wyT0cxRUszRllUVWxZVWs5b2VVWm1Ta1JOV0RVcmVrSmpkRzlHVjBkNWMweExTSEJLTlRrMFdXMDNWVUYzVVV0RFFWRkZRVGRrU3k5UmJXUlRDbGw2U0ZscVZtRlRVbVJ6VldoTU1uUjNTMFZWVUM5TGN6Tlhjbk15VmxGelJtaDViMWx2TDNkQ2JuTkpNbFZhWTFwWGFYWTRjVWt4ZUc4MlVuQjZOVllLZFRWWFZtMWxiMUZGYmtNd1pYWlZiVk5xU2xoRlNXNU1kR2RCVWtoUWEwaEllRGd2UnpoSk1raHZOalZuT1UweVFWcElkRkIwZDBKM1pGVTFUemQxVkFvck5WWTNOME5uYW1VNU5Ia3JjRzFLUkhod1RYY3Ziak5TY2tGa1RYQlFiRTFEU0ROVllucDJjelZ1ZFVKT2JWY3ZLMkp2VFcxaFlXdHNkMVptYVd0UkNsUnZha3hpTld3cmQwWndUR2hyUkROT1ZFRllRbEZrU2l0NlpqTm9VM3BvUjI5NmVYTmxaWGx2ZGxVNGVrcFJibkozVEZOaGJGZFRTamc0ZWxWUE5YTUtiM0prV0V0b1kySjZPR1l2WlhZeWJtWmlhRzQ1VldoNlRtRkViRGt4Tm1aeFFrVTBha3RxWjNWcE9HWk5OV2xNTW5kMlZtMU5VRVpsWTBGM09FTlhlZ3BvYkhoMVlWRkVOMmhTYW5CV2QwdERRVkZGUVRWWFdXWnpkbXBZYjAxVlozRktPRGRQVEhkMFRuSnNRbmxSYkU5RGEwZ3JhVFZaY1dKSVlUVlNaMEp6Q2xCalRFOVJZMmxFVWsxM0syZG9TaXRoVWxWU1NHTnZaV3hxWmt4MmVVOUJjRFZOWkUwMmVIRnBNVlZQWjFWUmNrTXhOelZhYURoMFZsTkthV1V3TDFFS1JGcG9RVXhJVW1zM1YwdExNRm94VWtsdWRWVlhWVWRCZUhKTmVYSlRlVUpEYkUxeWRHZ3JRU3N6V2tzd05sZFZjRWxRYmtsMFNVOWxWMjUyTURCVGRBcFdPSEY1Wm5aMVdDdHFXQzlLTUdobFlrTlpkbVpZUzJwQ1dFMXRWVmR0VGsxRmIxbERhM3BXU0dWbE4xWkNUa0kwUTBaeVJVSTBjMWRHUTBReVNUYzNDbkJKV0dJNE1pOHJSRmRoVEdOd1IwUklTSEpIVHpSTWVGcE1MMGRsZFRFM00yVXdkVFYwY0djM2F6VTVVSFJGUzFoR2N6bGpRMkpTWlRkd1dXNWFlV3NLVFU1bFEzZERXR2QwUVdWbWNrbE9XV2hLVWxvMVNrSnRXQ3QwTlU4NEsxWlVaMjFCY3pKRlVWbFJTME5CVVVGbWRtUkJVRWxrUlhGTmFETjNRakI2ZHdwcEsxQTJURFJNUVZGbU9UZzFXSFpUT1ZwR01VWkVibkZJV25OUWVFcDRTbXRUVWtkTk5VUnFZa0Y1U0hWelUyOXZjVU52UkV4aVQyMWFSbXhCU1hSNUNtMXdOVTFDZFc4NFdIVnRiRFpITlVzNVZXeFVZalV4VjNSM2JuRlFOSEZRYlRSalFrcEVRME5HZVV4MVJEbHJaMDFOUVRWNU4yaGtha3c0UldKMmMwWUtZbXQxY0dwT1NuaE9TbHB2Vm1KV0swNXpWU3N5WlZKMEwzbHhUMDh3VWxjeVZWZGxWMmhvUVZGWFdtVlROMnd6Y2xacGJFSlJRVXhMTVVSVWNsVXpkd3BwUm5seFNqUlBXRVZ5YzFCNlkwRXZRMjFKTnpSU2FVOVFXaXR4ZUZCNlpuRlNSMkpWUnpkWVpXVXplR2xWWnk5cVpsVlJZVlJKVVhGYU1qRnVWek14Q2pGdlEzWjJjV3RpU3pSRFkybFVXSFpSTTBaUFEyUkJVRlV6VlZSMVVIQTVabmR4VVVSV01HeFBSR2RwT0c5WmNEQk5Mek5VVjBSbWJuWnBVbWhVVFUwS2RWb3hla0Z2U1VKQlNGQkhiWFpGUlhwcE9FSjZiak5NTHpKUFpUbFhURTVHVUhGV2FUWkdOWFJVU2xZd05IUjVWVUZsV1ZwM2FUQnlUWGhsYlc5SE5ncFpNRWhoWlRWdmJGYzRTV2hLUm1KRlUycDRjR1Z4UlZscGIwSjBORVZtTlRSYWQzb3ZNVlkxTVZneFNUbDFVV3QxYm1Sd2VrdE9VREV2VDFoMWRXaHFDamsxVUdKU1puVldVekJZVVROWFJuSlNORkpJUm1Oc1ZVOUtaSFZTZG1GcGRWSnJaMVpIYWtSbFdVRkdZUzlEZWtkeGMxSXlhbkZaZG05WFFVUlRMMjBLTWt0UVIzcHZSR1YwVGtWdVltdGtkREpyVkRCa1MwZFBaelYxVUUwelFXOWhSVGhEWlZKcVdsSlBUMXBzZEM5eWIzUTVSa3R3VUdGVGVYZE9kR0poYkFweWJrNW5TbFF2VjFwMk0yRkdSMHMwZEhvclRGcENlVnBtUkZwbGRVNVZUa2xCUkRSR04yRk9RbVpFTkZwdWJDOXFkMGhqT0V4RlJqQTJUMDlsYkROcENrTjVRbE5IWm1GMmRVdzJNbU5xVTNVM2VucFZaelZKYWtWaFZqSnpORVZEWjJkRlFVWndXWFJSYVZWbWMwVkxOV0ZUVms0cldHWlFUMmhWYlV0VlFrUUtVVkprY2tObmFISXJja2hDUnpjdmJESkhSMDlTY1RCMkwydEJjMHR5TldSUllXOXBMMHBaUnpOeVMwTTJZMmcyVm1sck5GQllOUzlhVEVWRlZsWkROQXB3VFZwVmNWbDNWMDh4Y0VGeFUza3JNMjUwYjNoSmRFUk5NWEZ2ZEc4eFVuVnVPV1kwTVROWWFVNDFXbkpEUVRWTmFYbzBiR2hwV2xoaWREQkRkalUyQ2toWE4xbG5WRWRXZDBsWVltSnFTM05MTmtadVJIQkJlbkZwYVZNd1NHZFNWMFp6UWtVd1JWSmlTekpWYTNOMmFVdEhVV3AzUlVaU1ZrMXNjR3BzUTFRS2MxUmxaalJIYkd0V2NraDFiVkkzZDNobWFUVmpORmhMVWxoR1RuZEZObkoxZUdoa1RrZHFUV3BsTW5wTE5uSnZSVlpMVTNCdWFXSjBTMHBKWVZsVmN3cEVla1ZGZUZRM2VIRTRVR3RMY2tSMmJWWlZVbGQxWjFoV2NuQTNObGRUTW5vemNHUkhibFZRU1dkVFdraHJjM3BhTVdGS01HZEpOWEJSUFQwS0xTMHRMUzFGVGtRZ1VsTkJJRkJTU1ZaQlZFVWdTMFZaTFMwdExTMEsKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IGNsdXN0ZXIKICAgIHVzZXI6IGNmZS1tYXN0ZXIKICBuYW1lOiBkZWZhdWx0Q29udGV4dApjdXJyZW50LWNvbnRleHQ6IGRlZmF1bHRDb250ZXh0Cg==","storages":"[{\"username\": \"test\",\"password\": \"test\",\"ip\": \"8.40.111.70\",\"port\": 8088},{\"username\": \"test\",\"password\": \"test\",\"ip\": \"127.0.0.1\",\"port\": 8088}]"})";
    auto k8sApi = KubeHelper::GetKubernetesApiFromAppEnv(authExtendInfo);
    EXPECT_TRUE(k8sApi);
}

/**
 * 测试用例：测试GetKubernetesApiFromAppEnv函数失败
 * 前置条件：config参数错误
 * Check点：返回空的KubernetesApi。
 */
TEST_F(TransformerTest, GetKubernetesApiFromAppEnv_ShouldFailed) {
    std::string authExtendInfo = R"({"config":"123","storages":"[{\"username\": \"test\",\"password\": \"test\",\"ip\": \"8.40.111.70\",\"port\": 8088},{\"username\": \"test\",\"password\": \"test\",\"ip\": \"127.0.0.1\",\"port\": 8088}]"})";
    auto k8sApi = KubeHelper::GetKubernetesApiFromAppEnv(authExtendInfo);
    EXPECT_FALSE(k8sApi);
}

/**
 * 测试用例：测试GetStorageClientFromStorageParam函数成功
 * 前置条件：认证参数正常。
 * Check点：错误码为0。
 */
TEST_F(TransformerTest, GetStorageClientFromStorageParam_ShouldSuceess) {
    Stub stub;
    stub.set(ADDR(StorageClient, Create), Stub_StorageClientCreate);
    StorageParam storageParam;
    storageParam.username = "abc";
    storageParam.password = "123";
    storageParam.ip = "127.0.0.1";
    storageParam.ipList = "127.0.0.1,127.0.0.2";
    storageParam.port = 8088;
    // auto [ret, storageClient] = KubeHelper::GetStorageClientFromStorageParam(storageParam);
    // EXPECT_EQ(ret, Module::SUCCESS);
}

/**
 * 测试用例：测试GetStateFulSetFromExtendInfo函数成功
 * 前置条件：认证参数正常。
 * Check点：错误码为0。
 */
TEST_F(TransformerTest, GetStateFulSetFromExtendInfo_ShouldSuceess) {
    std::string appExtendInfo = "{\"sts\":\"{\\\"id\\\":\\\"3bb6d270-0f6d-4f0b-bea1-bccc5332163b\\\",\\\"name\\\":\\\"adaptermdb-1-1-m\\\",\\\"nameSpace\\\":\\\"ns000000000000000000001\\\",\\\"pods\\\":[{\\\"name\\\":\\\"adaptermdb-1-1-m-0\\\",\\\"pvs\\\":[{\\\"lunName\\\":\\\"1-adaptermdb-1-1-m-0-backup\\\",\\\"name\\\":\\\"pv-adaptermdb-1-1-m-0-backup\\\",\\\"pvcName\\\":\\\"gmdbbackup-adaptermdb-1-1-m-0\\\",\\\"size\\\":\\\"50Gi\\\",\\\"storageUrl\\\":\\\"https://8.40.111.70:8088/deviceManager/rest\\\",\\\"volumeName\\\":\\\"gmdbbackup\\\"},{\\\"lunName\\\":\\\"1-adaptermdb-1-1-m-0-redo\\\",\\\"name\\\":\\\"pv-adaptermdb-1-1-m-0-redo\\\",\\\"pvcName\\\":\\\"gmdbredo-adaptermdb-1-1-m-0\\\",\\\"size\\\":\\\"85Gi\\\",\\\"storageUrl\\\":\\\"https://8.40.111.70:8088/deviceManager/rest\\\",\\\"volumeName\\\":\\\"gmdbredo\\\"},{\\\"lunName\\\":\\\"1-adaptermdb-1-1-m-0-data\\\",\\\"name\\\":\\\"pv-adaptermdb-1-1-m-0-data\\\",\\\"pvcName\\\":\\\"gmdbdata-adaptermdb-1-1-m-0\\\",\\\"size\\\":\\\"80Gi\\\",\\\"storageUrl\\\":\\\"https://8.40.111.70:8088/deviceManager/rest\\\",\\\"volumeName\\\":\\\"gmdbdata\\\"},{\\\"lunName\\\":\\\"1-adaptermdb-1-1-m-0-lredo\\\",\\\"name\\\":\\\"pv-adaptermdb-1-1-m-0-lredo\\\",\\\"pvcName\\\":\\\"gmdblredo-adaptermdb-1-1-m-0\\\",\\\"size\\\":\\\"85Gi\\\",\\\"storageUrl\\\":\\\"https://8.40.111.70:8088/deviceManager/rest\\\",\\\"volumeName\\\":\\\"gmdblredo\\\"}]}],\\\"replicasNum\\\":1,\\\"volumeNames\\\":[\\\"gmdbredo\\\",\\\"gmdbdata\\\",\\\"gmdblredo\\\",\\\"gmdbbackup\\\"]}\\n\"}\n";
    auto stateFulSet = KubeHelper::GetStateFulSetFromExtendInfo(appExtendInfo);
    EXPECT_TRUE(stateFulSet);
    EXPECT_EQ(stateFulSet->name, "adaptermdb-1-1-m");
    EXPECT_EQ(stateFulSet->pods[0].pvs.size(), 4);
}

}