---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: scheduler
  name: scheduler
  namespace: default
spec:
  replicas: 1
  selector:
      matchLabels:
          k8s-app: scheduler
  template:
    metadata:
      labels:
        k8s-app: scheduler
        name: lala
    spec:
      containers:
      - image: emei-il.huawei.com/dev/scheduler
        name: scheduler
        imagePullPolicy: Always
        env:
            - name: SERVICE_MODE
              value: fake
            - name: LOGLEVEL
              valueFrom:
                  configMapKeyRef:
                      name: service-env-config
                      key: LOGLEVEL
            - name: SCHEDULER_MISFIRE_GRACE_SEC
              valueFrom:
                  configMapKeyRef:
                      name: service-env-config
                      key: SCHEDULER_MISFIRE_GRACE_SEC
            - name: KAFKA_BROKER_ADDR
              valueFrom:
                  configMapKeyRef:
                      name: service-env-config
                      key: KAFKA_BROKER_ADDR
---
apiVersion: v1
kind: Service
metadata:
  name: scheduler
  labels:
    k8s-app: scheduler
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    k8s-app: scheduler
