{{- $deploytype:= include "getDeployType" . | default "" }}
{{- if eq $deploytype "d10" }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-pm-resource-manager
  namespace: dpa
spec:
  entryPoints:
    - third
    - third6
    - third_node
    - internal
  routes:
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && Path(`/v1/resource`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/environments`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/virtual-resource`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/virtual-machines`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/compute-resources`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`) && PathPrefix(`/v1/free-effective-capacity`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`) && PathPrefix(`/v1/v-center/register/storages`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/protected-objects`) && !Path(`/v1/protected-objects-cyber`,`/v1/protected-objects-cyber/batch`,`/v1/protected-objects/status/action/activate-cyber`,`/v1/protected-objects/status/action/deactivate-cyber`,`/v1/protected-objects/{resource_id}/action/backup-cyber`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/resource-catalogs`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/protected-copy-objects`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
  tls:
    secretName: secret-pm-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-pm-resource-manager-except-post
  namespace: dpa
spec:
  entryPoints:
    - third
    - third6
    - third_node
    - internal
  routes:
    - match: Method(`GET`,`PUT`,`DELETE`) && PathPrefix(`/v1/resource/`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
  tls:
    secretName: secret-pm-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-pm-resource-manager-only-post
  namespace: dpa
spec:
  entryPoints:
    - third
    - third6
    - third_node
    - internal
  routes:
    - match: Method(`POST`) && PathPrefix(`/v1/resource/action/`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`POST`) && Path(`/v1/resource/host/{host_id:[0-9a-zA-Z\-]{1,64}}/action/sync-snmp-conf`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`POST`) && Path(`/v1/resource/host/{host_id:^[0-9a-zA-Z\-]{1,64}$}/asm-auth`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
  tls:
    secretName: secret-pm-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-pm-resource-manager-mtls
  namespace: dpa
spec:
  entryPoints:
    - agent
    - agent6
    - third
  routes:
    - match: HostRegexp(`CDMWebServer`) && Method(`POST`) && Path(`/v1/resource/host/`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
    - match: HostRegexp(`CDMWebServer`) && Method(`GET`) && Path(`/v1/internal/environments`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
    - match: HostRegexp(`CDMWebServer`) && Method(`GET`,`PUT`) && Path(`/v1/internal/service-links`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
  tls:
    secretName: secret-pm-tls
    options:
      name: tls-option-pm-mtls
{{- end }}