{{- $deploytype:= include "getDeployType" . | default "" }}
{{- if eq $deploytype "d10" }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-pm-replication
  namespace: dpa
spec:
  entryPoints:
    - replica
  routes:
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && Path(`/v1/auth/token`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
    - match: Method(`POST`) && Path(`/v1/clusters/target/relation`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`) && Path(`/v1/users/{id:[0-9a-fA-F]+}`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`) && Path(`/v1/users/quota/action/check`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`) && Path(`/v1/clusters/details`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`) && Path(`/v1/clusters/status`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`) && Path(`/v1/local-storage/service-ips`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`) && PathPrefix(`/v1/storages/nas/distribution`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`) && Path(`/v1/multiple-storage-pool/remote-dp-user-info`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`) && Path(`/v1/storage-user-auths/users/{id:[\w\-]+}`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`POST`, `DELETE`) && Path(`/v1/storage-policy-relation/policies/{id:[\w\-]+}`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`, `POST`) && Path(`/v1/storage-units`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`) && Path(`/v1/manual-replication/check-units`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
  tls:
    secretName: secret-pm-tls
{{- end }}