{{- $deploytype:= include "getDeployType" . | default "" }}
{{- if eq $deploytype "d10" }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-protectengine-search
  namespace: dpa
spec:
  entryPoints:
    - third
    - third6
    - third_node
    - internal
  routes:
    - match: Method(`POST`) && Path(`/v1/search/file`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
  tls:
    secretName: secret-pm-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-protectengine-anonymization
  namespace: dpa
spec:
  entryPoints:
    - third
    - third6
    - third_node
    - internal
  routes:
    - match: Method(`POST`) && Path(`/v1/anonymization/report/download`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`,`PUT`) && Path(`/v1/anonymization/identification/result`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`POST`) && Path(`/v1/anonymization/anonymization-job`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/anonymization/mask-rule`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/anonymization/ident-rule`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`,`PUT`,`DELETE`) && Path(`/v1/anonymization/policy`,`/v1/anonymization/policy/reference`,`/v1/anonymization/policy/{id:\w{8}(-\w{4}){3}-\w{12}}`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`GET`) && Path(`/v1/anonymization/policy-details`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
    - match: Method(`POST`) && Path(`/v1/anonymization-job/verification`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
  tls:
    secretName: secret-pm-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-dataenableengine-server-flr
  namespace: dpa
spec:
  entryPoints:
    - third
    - third6
    - third_node
    - internal
  routes:
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/flr`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
  tls:
    secretName: secret-pm-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress-route-dataenableengine-server-anti
  namespace: dpa
spec:
  entryPoints:
    - third
    - third6
    - third_node
    - internal
  routes:
    - match: Method(`GET`,`PUT`,`POST`,`DELETE`) && PathPrefix(`/v1/anti`)
      kind: Rule
      services:
        - name: pm-nginx
          port: 30093
          scheme: https
          serversTransport: serverstransport-traefik-backend
      middlewares:
        - name: middleware-pm-replace-path-regex
        - name: middleware-pm-jwt-token-auth
  tls:
    secretName: secret-pm-tls
{{- end }}