--
-- Name: COPIES_ANTI_RANSOMWARE; Type: TABLE; Schema: PUBLIC; Owner: GAUSSDB; Tablespace:
--
CREATE TABLE IF NOT EXISTS PUBLIC.COPIES_ANTI_RANSOMWARE
(
    COPY_ID VARCHAR(64) NOT NULL ,
    STATUS  INTEGER NOT NULL , -- 0：准备中；1:进行中；2：未感染；3：已感染；4：异常；
    MODEL VARCHAR(64) ,
    DETECTION_START_TIME VARCHAR(64),
    DETECTION_END_TIME VARCHAR(64),
    DETECTION_DURATION INTEGER,
    REPORT TEXT
);
alter table COPIES_ANTI_RANSOMWARE add column tenant_id varchar(64);
alter table COPIES_ANTI_RANSOMWARE add column tenant_name varchar(512);
ALTER TABLE COPIES_ANTI_RANSOMWARE ADD TOTAL_FILE_SIZE BIGINT;                        -- 副本检测结果 总文件大小
ALTER TABLE COPIES_ANTI_RANSOMWARE ADD CHANGED_FILE_COUNT BIGINT;                     -- 副本检测结果 修改文件数量
ALTER TABLE COPIES_ANTI_RANSOMWARE ADD ADDED_FILE_COUNT BIGINT;                       -- 副本检测结果 新增文件数量
ALTER TABLE COPIES_ANTI_RANSOMWARE ADD DELETED_FILE_COUNT BIGINT;                     -- 副本检测结果 删除文件数量
ALTER TABLE COPIES_ANTI_RANSOMWARE ADD HANDLE_DETECT_INFECT BOOLEAN DEFAULT FALSE;    -- 副本检测结果 误报处理
ALTER TABLE COPIES_ANTI_RANSOMWARE ADD GENERATE_TYPE CHARACTER VARYING(64);           -- 副本检测结果 生成方式 IO_DETECT 实时检测 COPY_DETECT 智能侦测
ALTER TABLE COPIES_ANTI_RANSOMWARE ADD BACKUP_SOFTWARE CHARACTER VARYING(1024) DEFAULT NULL;   -- 副本检测结果 备份软件
ALTER TABLE COPIES_ANTI_RANSOMWARE ADD INFECTED_FILE_COUNT BIGINT;                             -- 副本检测结果 异常文件数量
