CREATE TABLE if NOT EXISTS PUBLIC.T_DISTRIBUTED_LOCK (
    ID VARCHAR(64) NOT NULL PRIMARY KEY,
    `KEY` VARCHAR(256) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(1024),
    UNLOCK_TIME TIMESTAMP NOT NULL,
    LOCK_TIME TIMESTAMP NOT NULL,
    OWNER VARCHAR(256)
    );

CREATE TABLE if not exists PUBLIC.T_CONFIG
(
    UUID        VARCHAR(64)  NOT NULL,
    KEY         VARCHAR(128) NOT NULL,
    VALUE       TEXT,
    CONSTRAINT CONFIG_pkey PRIMARY KEY (KEY)
    );
